// 추가 설명 (카드 「네 걸음」의 스텝 2) — 1~32과. 원본: j-work/프로젝트/못삼영-재정비/규격/초안/N과.js
// 줄 형식은 data.js와 같다(## 소제목 · @compare · = 공식 · ! 주의 · ~ 아하 · + 핵심 · > 정답: 접이식). 「상황:」·「이름: 대사」 줄은 대화 상자로 그려진다.

const extraData = {
  1: [
    "## 상황",
    "동네 뉴스에 자막이 떴다. 단어는 똑같은데 뜻은 정반대다.",
    "## 대화 A",
    "친구: What is the news?",
    "나: Mina loves Jun.",
    "Mina(누가) → loves(한다) → Jun(누구를). 사랑하는 쪽은 미나다.",
    "## 대화 B",
    "친구: Is it the same news?",
    "나: No. Jun loves Mina.",
    "단어는 같은데 Jun이 앞으로 오니 사랑하는 쪽이 준으로 바뀐다.",
    "@compare 한국어 :: 조사가 역할을 알려 준다 :: 미나가 준을 / 준을 미나가 :: 영어 :: 자리가 역할을 알려 준다 :: Mina loves Jun / Jun loves Mina",
    "= 영어는 **자리**가 뜻이다. 주어 → 동사 → 목적어",
    "## 연습",
    "상황: 준이 미나를 좋아한다. 영어로 하면?",
    "____ ____ ____ (Jun likes Mina / Mina likes Jun)",
    "> 정답: Jun likes Mina — 좋아하는 사람이 맨 앞, 좋아하는 대상이 맨 뒤.",
    "## 기차로 보면",
    "@train 주어 · 동사 · 목적어",
    "Mina(주어) loves(동사) Jun(목적어). 세 칸은 이 순서로만 달립니다.",
    "! 틀려도 됩니다. 아는 단어로 이 순서만 지키면 영어가 됩니다.",
    "~ 한국어는 '가·를'이 역할을 알려 주니 순서가 자유롭고, 영어는 조사가 없어서 **자리**가 그 일을 합니다.",
    "## 비교",
    "순서 지킴 — I eat pizza. (나는 피자를 먹어요.)",
    "순서 어김 — Pizza eat I. (뜻이 안 통해요.)",
    "## 연습",
    "A: What does she like?",
    "B: She ____ ____. (likes music / music likes)",
    "> 정답: likes music — 동사가 가운데, 목적어가 맨 뒤.",
    "+ 영어는 자리가 뜻이다. 주어 → 동사 → 목적어, 이 순서만 지키면 아는 단어로도 문장이 된다."
  ],
  2: [
    "## 상황",
    "미나가 영어 동화책을 폈다. 첫 줄에서 어디를 봐야 할지 모르겠다.",
    "## 대화 A",
    "미나: What does the first line say?",
    "준: The dog runs.",
    "The dog(누가) → runs(한다). 짧은 줄은 기관차 두 칸이 전부입니다.",
    "## 대화 B",
    "미나: And the next line?",
    "준: The dog runs in the park every day.",
    "뒤에 in the park, every day가 붙어도 앞 두 칸은 The dog → runs 그대로. 뒤는 짐칸입니다.",
    "@compare 기관차 두 칸 :: 문장의 뼈대, 누가 → 한다 :: The dog runs / Mina sleeps :: 짐칸 :: 뼈대 뒤에 실리는 말 :: in the park / every day",
    "= 문장은 **기관차 두 칸**(주어 → 동사)이 끌고, 뒤에 짐칸이 따라온다",
    "## 연습",
    "상황: 아기가 밤마다 운다. The baby cries every night. 뼈대 두 칸은?",
    "____ (The baby cries / cries every night)",
    "> 정답: The baby cries — 누가(The baby) → 한다(cries). every night는 짐칸.",
    "## 두 질문으로 찾기",
    "상황: 준이 뼈대 찾는 요령을 알려 준다.",
    "준: Ask two questions. Who? And what does the person do?",
    "미나: My friend lives in Seoul. Who? My friend. What? Lives.",
    "「누가?」의 답이 주어(My friend), 「뭘 해?」의 답이 동사(lives)입니다. in Seoul은 짐칸이죠.",
    "! 짐칸이 아무리 길어도 동사가 짐칸 뒤로 밀리지 않습니다.",
    "~ 짧은 줄이든 긴 줄이든 그림은 같습니다. 기관차가 앞에서 끌고, 짐칸이 뒤따라옵니다.",
    "## 비교",
    "짧은 줄 — Mina sleeps. (미나가 자요.)",
    "긴 줄 — Mina sleeps at ten every night. (미나는 밤마다 열 시에 자요.)",
    "## 연습",
    "상황: 미나가 친구에게 준의 소식을 전한다.",
    "Jun waits at the bus stop. 뼈대: ____ (Jun waits / at the bus stop)",
    "> 정답: Jun waits — 누가(Jun) → 한다(waits). at the bus stop은 짐칸.",
    "+ 문장 앞의 기관차 두 칸이 주어와 동사다. 뒤에 짐칸이 아무리 실려도 그 두 칸은 그대로다."
  ],
  3: [
    "## 상황",
    "급식 시간. 새로 온 친구 엠마가 준에게 이것저것 묻는다.",
    "## 대화 A",
    "엠마: What do you eat?",
    "준: I eat gimbap.",
    "우리말을 영어 순서로 바꾼 「나는 먹는다 김밥을」을 세 칸에 놓았습니다. I → eat → gimbap.",
    "## 대화 B",
    "엠마: And what do you like?",
    "준: I like music.",
    "세 칸 틀은 그대로입니다. 칸 안의 낱말만 eat → like, gimbap → music으로 갈아 끼웠어요.",
    "@compare 우리말 옮겨 놓기 :: 동사를 두 번째 칸으로 :: 나는 김밥을 먹는다 → 나는 먹는다 김밥을 :: 낱말 갈아 끼우기 :: 틀은 그대로, 낱말만 바꾼다 :: I eat gimbap / I like music",
    "= **세 칸 틀**은 주어 → 동사 → 목적어. 우리말을 이 순서로 바꾼 다음 낱말을 놓는다",
    "## 연습",
    "상황: 준이 엠마에게 '나는 너의 노래를 좋아해'라고 말하고 싶다. 우리말을 먼저 바꾸면 '나는 좋아해 너의 노래를'이다.",
    "____ (I like your song / I your song like)",
    "> 정답: I like your song — 주어 → 동사 → 목적어. 동사는 두 번째 칸이다.",
    "## 세 번째 칸은 길어도 한 칸",
    "상황: 엠마가 강아지 사진을 보여 준다.",
    "엠마: I love my little dog.",
    "준: Wow. I love your little dog too.",
    "my little dog은 낱말이 셋이지만 목적어 한 칸입니다. 칸 하나에는 여러 낱말이 탈 수 있어요.",
    "! 「~을·~를」에 해당하는 영어 낱말은 없습니다. 목적어 자리에 서면 그 일을 합니다.",
    "~ 2과에서 기관차 뒤에 실린 짐칸 가운데 「무엇을」 자리가 이 세 번째 칸(목적어)입니다. 그림은 한 장이에요.",
    "## 비교",
    "짧은 칸 — I know Mina. (나는 미나를 알아요.)",
    "긴 칸 — I know your best friend. (나는 네 제일 친한 친구를 알아요.)",
    "## 연습",
    "상황: 엠마가 준에게 필요한 게 뭐냐고 물었다.",
    "엠마: What do you need?",
    "준: I ____ ____. (need help / help need)",
    "> 정답: need help — 주어 I 다음에 동사 need, 마지막 칸에 목적어 help.",
    "+ 세 칸 틀은 주어 → 동사 → 목적어. 우리말을 이 순서로 바꿔 낱말을 놓으면 되고, 칸이 길어도 한 칸이다."
  ],
  4: [
    "## 상황",
    "공원 사진 속 문장에서 미나가 멈췄다. 동사가 안 보인다.",
    "## 대화 A",
    "미나: Who is happy?",
    "준: The man with a red hat is happy.",
    "The man with a red hat 전체가 첫 칸(주어). 그 뒤의 is가 동사예요.",
    "## 대화 B",
    "미나: I see two verbs here!",
    "준: The man who is wearing blue jeans is happy.",
    "앞의 is는 who is wearing 속, 남자를 설명하는 말이에요. 진짜 동사는 첫 칸 뒤의 is.",
    "@compare 동사 없는 긴 첫 칸 :: 꾸미는 말에 동사가 없다 :: The man with a red hat :: 동사 든 긴 첫 칸 :: who 뒤에 동사가 숨어 있다 :: The man who is wearing blue jeans",
    "= 긴 주어도 **첫 칸 한 덩어리**. 덩어리를 한 단어(He·She·It·They)로 바꾸면 남는 동사가 진짜 동사",
    "## 연습",
    "상황: 진짜 동사는 무엇일까?",
    "The girl who sits next to me is kind. ____ (sits / is)",
    "> 정답: is — 덩어리를 She로 바꾸면 She is kind. 남는 동사가 is.",
    "## 한 단어로 바꿔 보기",
    "상황: 준이 요령을 알려 준다.",
    "준: Try this. The girl who sings in the hall is my sister.",
    "미나: The girl who sings in the hall → She. So, She is my sister!",
    "덩어리를 She로 바꾸니 She is my sister. 남는 is가 진짜 동사.",
    "! 처음 보이는 동사가 진짜 동사는 아닙니다.",
    "~ 첫 칸이 길든 짧든 기차는 하나입니다. 동사 칸은 그 덩어리 뒤에 옵니다.",
    "## 비교",
    "짧은 첫 칸 — He is my teacher. (그는 선생님이에요.)",
    "긴 첫 칸 — The man who helps Mina is my teacher. (미나를 돕는 남자는 선생님이에요.)",
    "## 연습",
    "미나: The dog that barks at night sleeps on my bed.",
    "준: So the real verb is ____. (barks / sleeps)",
    "> 정답: sleeps — 덩어리를 It으로 바꾸면 It sleeps on my bed. barks는 설명 속 동사.",
    "+ 긴 주어는 한 덩어리다. He·She·It·They로 바꿔 보면 남는 동사가 진짜 동사다."
  ],
  5: [
    "## 상황",
    "반려동물 가게 앞. 엠마가 진열대를 보며 준과 이야기한다.",
    "## 대화 A",
    "엠마: Do you have a pet?",
    "준: Yes. I have a dog.",
    "개가 한 마리라서 dog 앞에 a 딱지를 붙였습니다. a는 여러 마리 중 아무 한 마리라는 표시예요.",
    "## 대화 B",
    "준: And you? Do you have a pet?",
    "엠마: Yes. I have two dogs at home.",
    "두 마리 이상이면 dogs, 뒤에 s 딱지를 붙입니다. two가 있어도 s는 꼭 붙여요.",
    "@compare 하나 :: 앞에 a(an) 딱지 :: a dog / an egg :: 여럿 :: 뒤에 s 딱지 :: dogs / two eggs",
    "= 셀 수 있는 것은 **딱지**로 숫자를 밝힌다. 하나면 a(an) 같은 앞말, 여럿이면 -s",
    "## 연습",
    "상황: 준의 가방에 펜이 세 자루 있다.",
    "I have three ____. (pen / pens)",
    "> 정답: pens — 셋이니까 여럿 딱지 s. three가 있어도 s는 붙는다.",
    "## a가 an이 될 때",
    "상황: 준이 과일 가게에서 주문한다.",
    "준: I want an apple.",
    "엠마: Sorry. I have only oranges today.",
    "apple은 「애」처럼 모음 소리로 시작해서 an, 자음 소리로 시작하는 말 앞에는 a를 씁니다. 철자가 아니라 소리를 봐요.",
    "! a는 「콕 집은 그 하나」가 아닙니다. 아무 하나예요. 콕 집을 때는 the를 씁니다. a 자리에는 the·my도 올 수 있어요.",
    "~ 하나면 a, 여럿이면 s. 그림은 하나, 딱지입니다. 딱지를 보면 하나인지 여럿인지 알 수 있어요.",
    "## 비교",
    "하나 — I have an idea. (나는 생각이 하나 있어요.)",
    "여럿 — I have ideas. (나는 생각이 여러 개 있어요.)",
    "## 연습",
    "엠마: What is that?",
    "준: It is ____ orange. (a / an)",
    "> 정답: an — orange는 모음 소리로 시작해서 an.",
    "+ 하나인 셀 수 있는 것은 혼자 서지 못한다. 앞에 a(an)나 the·my 같은 말이 붙고, 여럿이면 -s가 붙는다."
  ],
  6: [
    "## 상황",
    "엠마가 새 방을 보여 준다. 준이 방에 뭐가 있는지 묻는다.",
    "## 대화 A",
    "준: What is on the desk?",
    "엠마: There is a book on the desk.",
    "하나라서 is + a book입니다. 스위치가 「하나」 쪽에 켜졌어요.",
    "## 대화 B",
    "준: And on the shelf?",
    "엠마: There are books on the shelf.",
    "여럿이라서 are + books. 스위치가 「여럿」 쪽으로 넘어가니 be 동사와 명사가 함께 바뀌었죠.",
    "@compare 하나 스위치 :: is + a 붙은 명사 :: There is a book / There is an egg :: 여럿 스위치 :: are + s 붙은 명사 :: There are books / There are two eggs",
    "= 숫자 **스위치** 하나로 be 동사와 명사가 함께 바뀐다. 하나면 is + a, 여럿이면 are + s",
    "## 연습",
    "상황: 서랍 속에 열쇠가 세 개 있다.",
    "There ____ three keys in the drawer. (is / are)",
    "> 정답: are — three keys는 여럿이라 스위치가 「여럿」. be 동사도 are.",
    "## 불규칙한 복수",
    "상황: 엠마가 학교 사진 두 장을 보여 준다.",
    "엠마: There is one child in the first photo.",
    "준: There are three children in the second one.",
    "child의 복수는 childs가 아니라 children입니다. person의 복수는 people입니다.",
    "이렇게 s 없이 모양이 바뀌는 복수도 있어요.",
    "! 숫자를 빼먹으면 틀립니다. There is book이 아니라 There is a book이에요.",
    "~ 하나면 스위치는 단수, 둘부터는 복수입니다. 명사도 be 동사도 같은 쪽으로 같이 넘어가요.",
    "## 비교",
    "단수 — There is an egg in the bowl. (그릇에 달걀이 하나 있어요.)",
    "복수 — There are eggs in the bowl. (그릇에 달걀이 여러 개 있어요.)",
    "## 연습",
    "상황: 준이 교실 사진을 설명한다.",
    "준: There are five ____ in the room. (person / people)",
    "> 정답: people — 다섯 명이라 복수. person의 복수는 people.",
    "+ 영어는 하나냐 여럿이냐를 밝힌다. 숫자 스위치가 넘어가면 명사와 be 동사가 함께 바뀐다."
  ],
  7: [
    "## 상황",
    "운동을 마친 엠마가 준의 집에 놀러 왔다. 준이 냉장고 안을 보며 말한다.",
    "## 대화 A",
    "엠마: What do you have?",
    "준: I have two apples.",
    "apple은 하나, 둘 셀 수 있는 알갱이입니다. 그래서 two apples처럼 s 딱지가 붙어요.",
    "## 대화 B",
    "엠마: And something to drink?",
    "준: I have water.",
    "water는 알갱이가 아니라 줄줄 흐르는 물이라 하나, 둘로 못 셉니다. 그래서 a도 s도 안 붙어요.",
    "@compare 알갱이 :: 하나, 둘 셀 수 있다 :: an apple / two apples :: 물 :: 그냥은 셀 수 없다 :: water / milk",
    "= 세는 것은 **알갱이**, 못 세는 것은 **물**이다. 물은 **그릇**에 담아야 센다",
    "## 연습",
    "상황: 엠마가 목이 말라서 준에게 부탁한다.",
    "Can I have ____ of water? (a glass / glass)",
    "> 정답: a glass — 물은 못 세니 그릇(glass)을 센다. 그릇이 하나라서 a.",
    "## 그릇에 담으면 셀 수 있어요",
    "상황: 엠마와 준이 카페에서 주문한다.",
    "직원: What would you like?",
    "엠마: A glass of milk, please.",
    "준: Two cups of tea, please.",
    "milk와 tea는 그냥은 못 세지만 그릇을 세면 됩니다. two cups의 s는 tea가 아니라 그릇 cups에 붙었어요.",
    "! 셀 수 없다는 건 '적다'는 뜻이 아닙니다. 물이 아무리 많아도 water는 water 그대로예요.",
    "~ 사과는 알갱이라 바로 세고, 물은 그릇에 담아 셉니다. 물은 대표 예예요. 돈·잠·시간도 물처럼 그냥은 못 셉니다.",
    "## 비교",
    "알갱이 — I need two eggs. (나는 달걀이 두 개 필요해요.)",
    "물 — I need milk. (나는 우유가 필요해요.)",
    "## 연습",
    "엠마: What do you need for the trip?",
    "준: I need ____. (money / a money)",
    "> 정답: money — money는 못 세는 것이라 a도 s도 안 붙는다.",
    "+ 알갱이는 바로 세고, 못 세는 물은 그릇에 담아야 센다. 그릇에 a나 s 딱지가 붙는다."
  ],
  8: [
    "## 한눈에",
    "1과 — 기차 — Mina loves Jun. (미나가 준을 사랑해요.)",
    "2과 — 기관차 — The dog runs in the park. (개가 공원에서 달려요.)",
    "3과 — 세 칸 틀 — I like music. (나는 음악을 좋아해요.)",
    "4과 — 긴 첫 칸 — The man with a red hat is happy. (빨간 모자를 쓴 남자는 행복해요.)",
    "5과 — 딱지 — I have a dog. (나는 개가 한 마리 있어요.)",
    "6과 — 스위치 — There are books on the shelf. (선반에 책이 여러 권 있어요.)",
    "7과 — 그릇 — Two cups of tea, please. (차 두 잔 주세요.)",
    "= 1월은 **자리**로 뜻을 만들고, 명사에 **숫자**를 밝히고, 지금 하는 말에서 he·she·it으로 바뀌는 주어의 동사에 **s**를 붙인다",
    "@compare he · she · it으로 바뀌는 하나 :: 동사에 s가 붙는다 :: He likes pizza / She has a dog :: I · you · we · they :: 동사는 그대로 :: I work / They like pizza",
    "~ 한 달의 뼈대는 셋입니다: 자리, 숫자, s. 나·너가 아닌 하나(3인칭 단수)의 현재 동사에만 s가 붙어요.",
    "## 연습",
    "상황: 준의 여동생은 매일 피아노를 친다. 동생을 she로 바꿔 본다.",
    "My sister ____ the piano. (plays / play)",
    "> 정답: plays — my sister는 she로 바뀌는 하나(3인칭 단수)라서 동사에 s.",
    "## 연습",
    "상황: 방과 후에 뭘 하는지 엠마가 묻는다.",
    "엠마: What do you do after school?",
    "준: I ____ soccer. (play / plays)",
    "> 정답: play — I는 하나여도 3인칭이 아니라서 s가 안 붙는다.",
    "+ 1월의 뼈대는 자리(기차)와 숫자, 그리고 지금 말할 때 he·she·it 뒤 동사의 s다. I와 You에는 s가 없다."
  ],
  9: [
    "## 상황",
    "점심시간 교실. 준이 자리에 앉아 웃고 있고, 미나가 다가온다.",
    "## 대화 A",
    "미나: What do you do at lunch?",
    "준: I eat pizza.",
    "eat은 「먹다」라는 뜻이 꽉 찬 동사입니다. 빼면 문장이 무너지죠. 물이 가득한 컵이에요.",
    "## 대화 B",
    "미나: How are you today?",
    "준: I am happy.",
    "am에는 뜻이 없습니다. 나와 행복을 등호(=)처럼 잇기만 해요. 물이 없는 **빈 컵**입니다.",
    "@compare 일반 동사 :: 뜻이 꽉 찬 컵 :: I eat pizza / She runs fast :: be 동사 :: 뜻이 빈 컵, 등호처럼 잇는다 :: I am happy / She is tall",
    "= be 동사는 뜻이 없는 **빈 컵**. 주어 = 상태를 **등호**처럼 잇는다",
    "## 연습",
    "상황: 시험이 끝나서 준이 지쳤다.",
    "I ____ tired. (am / eat)",
    "> 정답: am — 지친 '상태'를 잇는 자리라서 뜻 없는 be가 들어간다.",
    "## 컵에는 사람도 담깁니다",
    "상황: 새 학기 첫날. 미나가 교문 앞에 서 있는 어른을 가리킨다.",
    "미나: Who is he?",
    "준: He is my teacher.",
    "is my teacher = 그는 내 선생님. happy 대신 이름(my teacher)이 담겼어요.",
    "! be 동사를 「~이다」로 외워도 됩니다. 다만 그건 번역일 뿐, 하는 일은 등호(=)예요.",
    "~ 컵은 같습니다. happy는 상태를, my teacher는 누구인지를 알려 줘요.",
    "## 비교",
    "일반 동사 — She eats lunch. (그녀는 점심을 먹어요.)",
    "be 동사 — She is a student. (그녀는 학생이에요.)",
    "## 연습",
    "상황: 미나가 준의 친구를 칭찬한다.",
    "She ____ kind. (is / eats)",
    "> 정답: is — She = kind를 잇는 자리. 뜻이 필요한 게 아니라 잇는 말이 필요하다.",
    "+ be 동사는 뜻이 없는 빈 컵이다. 뜻이 없어서 상태든 이름이든 담고, 주어와 뒤를 등호처럼 잇는다."
  ],
  10: [
    "## 상황",
    "체육 시간이 끝났다. 준이 땀을 닦으며 벤치에 털썩 앉는다.",
    "## 대화 A",
    "미나: What do you do after class?",
    "준: I play basketball. I run a lot.",
    "play와 run은 손발이 움직이는 **행동**입니다. 「농구를 한다」 「많이 달린다」.",
    "## 대화 B",
    "미나: How are you now?",
    "준: I am tired. I am hungry.",
    "am tired는 움직임이 아닙니다. 지금 내 가슴에 달린 **명찰**이에요. 「지금 나는 이렇다」.",
    "@compare 행동 :: 손발이 하는 일 :: I run every day / She eats lunch :: 상태 :: 지금 달린 명찰 :: I am tired / She is a teacher",
    "= 행동은 **손발**이 하는 일, 상태(be)는 지금 나에게 달린 **명찰**",
    "## 연습",
    "상황: 준이 숨을 헐떡이며 물을 찾는다.",
    "He ____ thirsty. (is / runs)",
    "> 정답: is — 달리는 행동이 아니라 목마른 '상태'를 말하니까 be가 온다.",
    "## 명찰에는 장소도 붙습니다",
    "상황: 준의 엄마가 전화로 아들을 찾는다.",
    "엄마: Where is Jun?",
    "미나: He is in the gym. He is with his team.",
    "is in the gym은 「지금 체육관에 있다」는 명찰입니다. 「어디에 있나」도 상태예요.",
    "! be 동사는 「~이다」만이 아닙니다. 「~에 있다」도 됩니다.",
    "~ 명찰 종류는 달라도 하나입니다. tired든 teacher든 gym이든 「나는 이렇다」를 알려 주는 표시죠.",
    "## 비교",
    "행동 — She plays tennis. (그녀는 테니스를 쳐요.)",
    "상태 — She is at the court. (그녀는 코트에 있어요.)",
    "## 연습",
    "미나: Is your brother sleepy?",
    "준: Yes. He ____ sleepy. (is / sleeps)",
    "> 정답: is — sleepy는 상태를 알려 주는 말이라 앞에 be가 필요하다.",
    "+ 행동은 손발이 하는 일이고, 상태는 be가 다는 명찰이다. be 뒤에 tired·teacher·in the gym 같은 말이 오면 상태다."
  ],
  11: [
    "## 상황",
    "영화관 매표소. 미나 일행이 줄을 서서 표를 산다.",
    "## 대화 A",
    "직원: Is he with you?",
    "미나: Yes. He is my brother. I am his sister.",
    "한 명씩 이야기입니다. I는 전용석 am, 한 명(He)은 is 자리에 앉아요.",
    "## 대화 B",
    "직원: Are you ready?",
    "미나: Yes. We are ready. They are my cousins.",
    "You도, 여럿(We·They)도 are 자리에 앉습니다. 몇 명이든 자리는 하나예요.",
    "@compare am·is 자리 :: I는 am, 한 명·하나는 is :: I am kind / He is kind :: are 자리 :: You와 여럿은 are :: You are kind / They are kind",
    "= **좌석 셋**: I는 am, 한 명·하나는 is, You와 여럿은 are",
    "## 연습",
    "상황: 표를 산 뒤 미나와 준이 줄에 섰다.",
    "Mina and Jun ____ in line. (is / are)",
    "> 정답: are — 미나와 준, 둘이니까 여럿 자리 are.",
    "## 사물도 앉습니다",
    "상황: 미나가 영화 정보를 묻는다.",
    "미나: Is the movie good?",
    "준: Yes. It is funny. The tickets are cheap.",
    "It은 하나라서 is, tickets는 여럿이라서 are. 사람이든 사물이든 같은 자리표예요.",
    "! 「I는 am, You는 are, 나머지는 is」로 외우면 We·They에서 틀립니다. 여럿은 are예요.",
    "~ 자리는 셋뿐입니다. am은 나 하나, is는 한 명·하나, are는 나머지 모두가 앉아요.",
    "## 비교",
    "한 명 — She is kind. (그녀는 친절해요.)",
    "여럿 — They are kind. (그들은 친절해요.)",
    "## 연습",
    "미나: Is your sister at home?",
    "준: Yes. She ____ in the kitchen. (is / are)",
    "> 정답: is — She는 한 명이니까 is 자리.",
    "+ be 동사는 좌석이 셋이다. I는 am, 한 명·하나는 is, You와 여럿(We·They)은 are에 앉는다."
  ],
  12: [
    "## 상황",
    "주말 오후. 미나가 준에게 전화를 걸었다.",
    "## 대화 A",
    "미나: What do you do after school?",
    "준: I dance. I dance every day.",
    "I dance는 매일 되풀이하는 일입니다. 긴 영상처럼 길게 이어지는 이야기예요.",
    "## 대화 B",
    "미나: What are you doing now?",
    "준: I am dancing.",
    "am dancing은 지금 이 순간을 찍은 **사진 한 장**입니다. 지금 춤추는 모습이 담겨요.",
    "@compare 매일의 일 :: 늘 하는 일, 긴 영상 :: I dance every day / She sings at night :: 지금의 일 :: 이 순간의 사진 :: I am dancing / She is singing",
    "= 진행형은 **사진 한 장**: be + 동사-ing, 지금 이 순간의 모습",
    "## 연습",
    "상황: 아기 방을 들여다본다. 아기가 지금 자고 있다.",
    "Look! The baby ____. (sleeps / is sleeping)",
    "> 정답: is sleeping — Look!은 지금 이 순간을 가리킨다. 사진 한 장이다.",
    "## 사진 속 사람이 바뀌면",
    "상황: 미나가 창밖 운동장을 가리킨다.",
    "준: What are they doing?",
    "미나: They are dancing. He is watching. I am resting.",
    "사진 틀(be)은 am·is·are로 바뀌고, 안의 행동(-ing)만 달라요.",
    "! -ing만 붙이면 진행형이 아닙니다. 틀인 be가 빠지면 문장이 서지 않아요.",
    "~ 사진에는 언제나 틀(be)이 있고, 그 안에 지금의 행동(-ing)이 들어갑니다.",
    "## 비교",
    "습관 — I study every night. (저는 밤마다 공부해요.)",
    "사진 — I am studying now. (저는 지금 공부하고 있어요.)",
    "## 연습",
    "상황: 방문 너머에서 동생이 지금 막 노래를 하고 있다.",
    "Listen! She ____ a song. (sings / is singing)",
    "> 정답: is singing — 지금 들리는 노래는 사진 한 장, be + -ing.",
    "+ 진행형은 사진 한 장이다. be가 틀이고 -ing가 그 안의 행동이라, 지금 이 순간의 모습을 담는다."
  ],
  13: [
    "## 상황",
    "아침에 카페에 갔더니 유리창이 깨져 있었다.",
    "## 대화 A",
    "손님: Who broke the window?",
    "직원: I don't know. It was like this when I came in.",
    "broke = 누가 깼는지가 궁금할 때, 범인을 찾는 말",
    "## 대화 B",
    "손님: Is the shop open?",
    "직원: No. The window is broken, so the shop is closed.",
    "is broken = 지금 깨져 있는 상태만 말한다. 누가 깼는지는 관심 없다. 도장이 쾅 찍힌 **결과표**예요.",
    "@compare 일반 문장 :: 누가 했나 :: Who broke it / I broke it :: 수동태 :: 지금 어떤 결과인가 :: It is broken / The shop is closed",
    "= 이 과의 수동태는 **be + 과거분사**. 누가 했나는 빼고 **결과표**처럼 지금의 결과만 말한다",
    "## 연습",
    "상황: 가게 문 앞에 '영업 끝' 팻말이 걸려 있다.",
    "The shop ____ at the moment. (closes / is closed)",
    "> 정답: is closed — 누가 닫았는지는 중요하지 않고, 지금 닫혀 있는 결과가 중요하다.",
    "## 결과만 보이는 문장",
    "상황: 회의 전. 팀장이 자료를 묻자, 동료는 이미 끝내 놓았다.",
    "팀장: Can you send the report?",
    "동료: It is done. The file is saved in the folder.",
    "is done, is saved = 누가 했는지 말하지 않아도 되는 결과",
    "! 수동태는 '당했다'는 뜻이 아닙니다. 그냥 '그런 상태다'입니다.",
    "~ 결과표에는 도장 하나만 찍혀 있습니다. 누가 찍었는지는 빼고, **지금 그 일이 어떤 상태인지**만 남는 거죠.",
    "## 비교",
    "일반 — The boy broke the window. (그 아이가 창문을 깼어요.)",
    "수동태 — The window is broken. (창문이 깨져 있어요.)",
    "## 연습",
    "A: Where is the report?",
    "B: It ____ in the folder. (saves / is saved)",
    "> 정답: is saved — 누가 저장했는지 말하지 않고, 저장된 결과를 알려 준다.",
    "+ 이 과의 수동태는 be 동사 뒤에 과거분사를 붙여 만든다. 누가 했는지 대신 지금 어떤 결과인지를 말한다."
  ],
  14: [
    "## 상황",
    "학교 앞 횡단보도. 미나와 준이 나란히 서서 이야기한다. 하늘이 흐리다.",
    "## 대화 A",
    "미나: What are you going to do tonight?",
    "준: I am going to study English.",
    "마음속에서 이미 길에 올라선 일입니다. 발이 그쪽으로 향했으니 「공부할 거야」예요.",
    "## 대화 B",
    "준: Look at the sky. It is going to rain.",
    "미나: Really? We are going to get wet!",
    "검은 구름이 이미 비 쪽으로 가는 중입니다. 눈앞에 보이는 신호로도 「~할 것 같아」를 말해요.",
    "@compare 내 계획 :: 내가 이미 마음먹은 일 :: I am going to study / We are going to eat :: 눈앞 신호 :: 지금 보이는 것으로 아는 일 :: It is going to rain / The baby is going to cry",
    "= be going to는 **이미 출발한 발걸음**. 앞으로 일어날 일을 말한다",
    "## 연습",
    "상황: 하늘이 갑자기 어두워졌다.",
    "Look! It ____ rain. (is going to / goes to)",
    "> 정답: is going to — 구름이라는 신호가 보이니 앞으로 일어날 일, 발걸음이다.",
    "## 안 할 때와 물을 때",
    "상황: 미나가 노래자랑 신청서를 든 준에게 묻는다.",
    "미나: Are you going to sing?",
    "준: No, I am not going to sing. I am going to dance.",
    "물을 때는 be가 앞으로, 안 할 때는 be 뒤에 not이에요. 발걸음 그림은 그대로입니다.",
    "! 「가고 있다」는 그림이고 뜻은 「~할 거야」입니다. going to 뒤에는 동사 원래 모양이 와요.",
    "~ 계획이든 눈앞의 신호든, 발이 이미 그쪽으로 향했다는 점은 같습니다.",
    "## 비교",
    "지금 — I am studying. (저는 지금 공부하고 있어요.)",
    "앞으로 — I am going to study. (저는 공부할 거예요.)",
    "## 연습",
    "미나: When are you going to eat?",
    "준: We ____ eat at six. (are going to / is going to)",
    "> 정답: are going to — 주어 We는 are 자리. 그 뒤에 going to와 동사.",
    "+ be going to는 이미 출발한 발걸음이다. 계획이든 눈앞의 신호든, 앞으로 일어날 일을 말한다."
  ],
  15: [
    "## 상황",
    "월요일 아침 교실. 미나가 준에게 어제 어디 있었는지 묻는다.",
    "## 대화 A",
    "미나: Where were you yesterday?",
    "준: I was at home. I was sick.",
    "어제 칸에서는 I가 was 자리에 앉습니다. 오늘의 am이 어제 칸으로 한 칸 옮겨 간 거예요.",
    "## 대화 B",
    "미나: Were your parents at home?",
    "준: Yes. They were there. We were at the table.",
    "You·We·They는 오늘 are였으니 어제는 were입니다. 자리표가 한 칸씩 옮겨 가요.",
    "@compare 오늘 칸 :: am · is · are :: I am tired / They are here :: 어제 칸 :: was · were :: I was tired / They were here",
    "= 과거 be는 **어제 칸**으로 옮긴 be. am·is는 was, are는 were",
    "## 연습",
    "상황: 어제 미나는 콘서트장에 있었다.",
    "I ____ at the concert yesterday. (was / were)",
    "> 정답: was — 주어 I는 오늘 am이었으니 어제 칸에서는 was.",
    "## 옛날 모습도 어제 칸입니다",
    "상황: 학교 복도에 옛날 공연 포스터가 붙어 있다. 미나가 포스터 속 사람을 가리킨다.",
    "미나: Was he a singer?",
    "준: Yes. He was a singer. Now he is a teacher.",
    "어제 칸의 모습은 was가, 지금의 모습은 is가 맡습니다.",
    "! was는 「그때 그랬다」만 말합니다. 지금은 어떤지는 앞뒤 말이 알려 줘요.",
    "~ 어제 칸에서도 자리표는 그대로입니다. I·He·She는 was, You·We·They는 were예요.",
    "## 비교",
    "오늘 — She is tired. (그녀는 지금 피곤해요.)",
    "어제 — She was tired. (그녀는 그때 피곤했어요.)",
    "## 연습",
    "미나: Where were the keys?",
    "준: They ____ on the table. (was / were)",
    "> 정답: were — keys는 여럿이라 They. are를 어제 칸으로 옮기면 were.",
    "+ 과거 be는 오늘의 be를 어제 칸으로 옮긴 것이다. am·is는 was, are는 were로 옮겨 앉는다."
  ],
  16: [
    "## 한눈에",
    "9과 — 빈 컵 — You are kind. (당신은 친절해요.)",
    "10과 — 명찰 — I am hungry. (저는 배고파요.)",
    "11과 — 좌석 — We are here. (우리는 여기 있어요.)",
    "12과 — 사진 — He is watching. (그는 보고 있어요.)",
    "13과 — 결과표 — The door is locked. (문이 잠겨 있어요.)",
    "14과 — 발걸음 — I am going to study. (저는 공부할 거예요.)",
    "15과 — 어제 칸 — She was tired. (그녀는 피곤했어요.)",
    "= 이번 달 일곱 그림이 달라도 be는 다 같은 be. **다섯 얼굴**이 된다",
    "상태 · 진행 · 수동 · 미래 · 과거. 앞의 넷은 be 뒤에 오는 말이, 과거는 be의 모양이 정해요.",
    "@compare 진행 :: 하고 있는 중 (-ing) :: The door is closing / She is cooking :: 수동 :: 된 결과 (과거분사) :: The door is closed / The food is cooked",
    "~ be 뒤에 -ing가 오면 사진, 과거분사가 오면 결과표입니다. be는 같고 뒤에 온 말만 달라요.",
    "## 연습",
    "상황: 미나가 어젯밤 일을 떠올린다.",
    "We ____ very tired last night. (are / were)",
    "> 정답: were — last night은 어제 칸. We의 are를 어제 칸으로 옮기면 were.",
    "## 연습",
    "상황: 준이 지금 막 주방에서 저녁을 만들고 있다.",
    "He ____ dinner now. (is cooking / is cooked)",
    "> 정답: is cooking — 사람이 지금 요리하는 중이니 사진 한 장(-ing). 수동은 결과다.",
    "+ be 하나로 상태·진행·수동·미래·과거가 다 만들어진다. 뒤에 오는 말과 be의 모양이 얼굴을 정한다."
  ],
  17: [
    "## 상황",
    "전학 온 삼돌이가 옥상에서 노을을 보고 있다. 못난이가 다가와 말을 건다.",
    "## 대화 A",
    "못난이: What do you have in your bag?",
    "삼돌이: I have a book and a pen.",
    "손에 잡히는 물건도 have로 나와 이어 줍니다. 끈 끝에 책과 펜이 매달린 그림이죠.",
    "## 대화 B",
    "못난이: You look sad. What's wrong?",
    "삼돌이: I have a problem. I have no plan.",
    "문제도, 계획 없음도 have로 말합니다. 손에 안 잡혀도 끈은 이어져요. have no는 '끈이 없다'입니다.",
    "@compare 물건 :: 손에 잡히는 것 :: I have a pen / I have a car :: 관계·마음 :: 손에 안 잡히는 것 :: I have a sister / I have a dream",
    "= have는 나와 무언가를 잇는 **끈**이다. 잡히든 안 잡히든 상관없다",
    "## 연습",
    "상황: 못난이에게는 오빠가 한 명 있다.",
    "She ____ a brother. (have / has)",
    "> 정답: has — 주어가 She면 have가 has로 바뀐다. 끈은 그대로다.",
    "## 시간도 끈으로 이어집니다",
    "상황: 민준이 삼돌이에게 다가와 묻는다.",
    "민준: Do you have time?",
    "삼돌이: Yes, I have time.",
    "시간도 생각도 꿈도 끈 끝에 매달립니다. 눈에 안 보여도 have로 나와 이어져요.",
    "! happy 같은 형용사는 have가 아니라 be입니다. I am happy (O), I have happy (X).",
    "~ 책도 문제도 시간도 결국 같은 그림입니다. 나와 이어진 끈이죠.",
    "## 비교",
    "I·you·we·they — I have a dream. (나에게는 꿈이 있어요.)",
    "he·she·it — She has a dream. (그녀에게는 꿈이 있어요.)",
    "## 연습",
    "상황: 옆 반 아이들에게는 새 선생님이 있다.",
    "They ____ a new teacher. (have / has)",
    "> 정답: have — 주어가 They면 has가 아니라 have다.",
    "+ have는 소유가 아니라 끈이다. 물건·사람·시간·꿈을 나와 이어 준다."
  ],
  18: [
    "## 상황",
    "아침 동아리실. 못난이가 밤새 쓴 노트가 책상 위에 놓여 있다. 민준이 들어온다.",
    "## 대화 A",
    "민준: When did you write it?",
    "못난이: I wrote it last night.",
    "wrote는 '어젯밤'이라는 그때 하나만 가리킵니다. 그 일은 그때 끝난 이야기예요.",
    "## 대화 B",
    "민준: Is the song ready now?",
    "못난이: Yes. I have finished it.",
    "have finished는 끝낸 일이 지금도 내 곁에 있다는 말입니다. 그래서 지금 '다 됐다'가 돼요.",
    "@compare 과거형 :: 그때 있었던 일 :: I wrote it last night / I went to Seoul last year :: 현재완료 :: 지금과 이어진 일 :: I have written it / I have been to Seoul",
    "= 현재완료는 과거와 지금을 잇는 **다리**다. have + 과거분사",
    "## 연습",
    "상황: 못난이는 작년에 서울에 갔다. 때가 딱 정해진 일이다.",
    "I ____ to Seoul last year. (went / have been)",
    "> 정답: went — last year처럼 때가 딱 있으면 과거형이다.",
    "## I've로 줄여 말해요",
    "상황: 못난이가 하품을 한다. 민준이 걱정한다.",
    "민준: Have you slept?",
    "못난이: No. I've stayed up all night.",
    "I've는 I have를 줄인 말입니다. 말할 때는 거의 이렇게 줄여요.",
    "! last night 같은 딱 정해진 때와는 have를 못 씁니다. 그럴 땐 과거형이에요.",
    "~ 과거에 끝난 일이 다리를 건너 지금 여기 도착한 거죠.",
    "## 비교",
    "과거형 — I wrote it last night. (어젯밤에 썼어요.)",
    "현재완료 — I have written it. (다 써 놨어요. 지금도 여기 있어요.)",
    "## 연습",
    "상황: 삼돌이가 두리안 이야기를 꺼낸다.",
    "삼돌이: Have you ever eaten durian?",
    "못난이: No, I ____ never eaten it. (have / am)",
    "> 정답: have — '먹어 본 적 없다'는 have + 과거분사(eaten)로 만든다. am은 뜻이 이어지지 않는다.",
    "+ 현재완료는 have + 과거분사. 지난 일이 지금과 이어질 때 쓰는 다리다."
  ],
  19: [
    "## 상황",
    "저녁, 동아리실이다. 삼돌이는 가방을 싸고, 못난이는 노트를 펼친다.",
    "## 대화 A",
    "못난이: Can you stay?",
    "삼돌이: No. I have to go home by nine.",
    "엄마가 정한 시간처럼 밖에서 온 이유도 have to로 말합니다. 남이 짐을 내 어깨에 얹어 준 그림이에요.",
    "## 대화 B",
    "삼돌이: Why are you still here?",
    "못난이: I have to finish this song.",
    "아무도 시키지 않았어도 내가 꼭 해야 한다고 느끼는 일이면 have to를 씁니다. 짐이 안에서 생겨 내가 멘 그림이에요.",
    "@compare 밖에서 온 짐 :: 규칙·상황이 시킨 일 :: I have to go home / You have to wear a uniform :: 안에서 온 짐 :: 꼭 해야 한다고 느끼는 일 :: I have to finish this song / I have to try",
    "= have to는 해야 할 일을 **어깨에 멘 짐**으로 갖고 있다는 말이다. 짐이 어디서 왔든 같다",
    "## 연습",
    "상황: 학교 규칙 때문에 못난이는 교복을 입어야 한다.",
    "She ____ wear a uniform. (have to / has to)",
    "> 정답: has to — 주어가 She라서 have가 has로 바뀐다.",
    "## 짐이 없을 때",
    "상황: 삼돌이가 못난이를 도우려 한다.",
    "삼돌이: Let me help you.",
    "못난이: You don't have to help. It's late.",
    "삼돌이: I know. I want to.",
    "don't have to는 짐이 없다는 말입니다. '안 해도 돼'예요.",
    "! don't have to는 '하지 마'가 아닙니다. '안 해도 된다'예요.",
    "~ 규칙이 얹었든 마음이 얹었든 짐은 짐입니다. have to는 그 짐을 멘 사람의 말이죠.",
    "## 비교",
    "have to — I have to go. (나는 가야 해요.)",
    "don't have to — I don't have to go. (나는 안 가도 돼요.)",
    "## 연습",
    "상황: 내일은 시험이 없다. 삼돌이는 공부하지 않아도 된다.",
    "I ____ study tonight. (have to / don't have to)",
    "> 정답: don't have to — 시험이 없어서 짐이 없다. 안 해도 된다.",
    "+ have to는 해야 할 일을 짐처럼 메고 있다는 말이다. 규칙이 시켜도, 꼭 해야 한다고 느껴도 쓴다."
  ],
  20: [
    "## 상황",
    "연습 사이 쉬는 시간, 연습실이다. 땀범벅이 된 삼돌이와 못난이가 바닥에 앉는다.",
    "## 대화 A",
    "삼돌이: I'm tired. Let's have a break.",
    "못난이: Good idea. Let's have a drink too.",
    "have a break는 쉬는 시간이 든 상자를 여는 말입니다. have a drink는 마시기 상자예요. take a break도 같은 뜻이에요.",
    "## 대화 B",
    "민준: What do you do after practice?",
    "못난이: I have dinner, and then I have a shower.",
    "밥 먹기도 씻기도 경험 한 상자입니다. 매일 하는 일도 have 뒤에 명사만 바꿔 말해요.",
    "@compare 쉬고 노는 상자 :: 기분 좋은 시간 :: have fun / have a break :: 매일 하는 상자 :: 일상의 일 :: have dinner / have a shower",
    "= have + 명사는 그 명사가 든 **경험 상자**를 여는 말이다. 상자 안 명사가 활동을 정한다",
    "## 연습",
    "상황: 연습이 끝났다. 삼돌이가 저녁을 같이 먹자고 한다.",
    "Let's ____ dinner together. (have / go)",
    "> 정답: have — 저녁 상자를 연다. have dinner가 저녁을 먹는다는 뜻이다.",
    "## 한번 해보는 상자",
    "상황: 삼돌이가 새 동작을 보여 준다.",
    "삼돌이: Have a look.",
    "못난이: Wow. Can I have a try?",
    "have a look은 한번 보는 것, have a try는 한번 해 보는 것입니다.",
    "! have fun에는 a를 안 붙입니다. have a fun은 틀린 말이에요.",
    "~ 상자에 무슨 명사가 들었나만 보면 뜻이 나옵니다. 쉼도 밥도 샤워도 같은 그림이에요.",
    "## 비교",
    "소유 — I have a car. (나는 차가 있어요.)",
    "경험 — I have lunch. (나는 점심을 먹어요.)",
    "## 연습",
    "상황: 삼돌이가 오늘 밤을 신나게 보내자고 한다.",
    "Let's ____ fun tonight. (have / have a)",
    "> 정답: have — fun에는 a를 붙이지 않는다. Let's have fun이다.",
    "+ have + 명사는 그 명사가 든 활동을 한다는 말이다. 차 같은 물건이면 '가지고 있다'는 뜻이다."
  ],
  21: [
    "## 상황",
    "연습이 끝난 밤, 어둑한 복도다. 삼돌이와 못난이가 신발끈을 묶는다.",
    "## 대화 A",
    "못난이: Why are you smiling?",
    "삼돌이: I got a letter from my friend.",
    "없던 편지가 문턱을 넘어 들어왔습니다. got은 그렇게 없던 것이 내게 생기는 순간을 말해요.",
    "## 대화 B",
    "못난이: You look tired.",
    "삼돌이: Yes. I get tired after practice.",
    "피곤하지 않던 내가 피곤한 쪽으로 문턱을 넘습니다. get tired는 '피곤해진다'예요.",
    "@compare have :: 방 안에 이미 있는 상태 :: I have a letter / I have money :: get :: 문턱을 넘는 순간 :: I got a letter / I get tired",
    "= have는 방 안에 **있는** 것, get은 문턱을 **넘는** 순간이다. get이 나오면 뭔가 바뀐다",
    "## 연습",
    "상황: 겨울에는 해가 일찍 져서 금방 어두워진다.",
    "It ____ dark early in winter. (gets / has)",
    "> 정답: gets — 밝던 것이 어두워지는 변화다. 주어가 It이라 gets다.",
    "## 몸도 말도 문턱을 넘습니다",
    "상황: 연습 세 시간째, 삼돌이 얼굴이 새빨갛다.",
    "민준: Your face is red.",
    "삼돌이: I get hot when I dance.",
    "덥지 않던 몸이 더워지는 쪽으로 넘어갑니다.",
    "민준: Left, then right. Now spin.",
    "삼돌이: Oh, I get it!",
    "말이 문턱을 넘어 마음에 들어옵니다. I get it은 '알겠어요'예요.",
    "! get 뒤에 형용사가 오면 '~해지다', 받거나 생기는 것이 오면 '받다·생기다'입니다.",
    "~ 편지가 들어오든 몸이 더워지든 말이 마음에 들어오든 그림은 하나입니다. 문턱을 넘는 순간이죠.",
    "## 비교",
    "have — I have money. (나는 돈이 있어요.)",
    "get — I got money. (나는 돈을 받았어요.)",
    "## 연습",
    "상황: 방금 삼돌이 폰에 문자가 들어왔다.",
    "Just now, I ____ a message. (got / have)",
    "> 정답: got — Just now는 방금 들어온 순간이다. 들어오는 순간은 get이다.",
    "+ have는 방 안에 있는 상태, get은 문턱을 넘는 순간이다. 편지가 오든 몸이 바뀌든 말이 들어오든 get은 변화다."
  ],
  22: [
    "## 상황",
    "비 오는 아침, 학교 가는 길이다. 삼돌이와 못난이가 정류장에서 만난다.",
    "## 대화 A",
    "못난이: How do you go to school?",
    "삼돌이: I take the bus.",
    "내가 손을 뻗어 버스를 잡아탑니다. take는 무언가를 손으로 집어 갖는 손이에요.",
    "## 대화 B",
    "못난이: How long does it take from your house to school?",
    "삼돌이: Yes. It takes an hour.",
    "이번엔 손을 뻗는 쪽이 사람이 아닙니다. 그 길이 한 시간을 가져가요. 그래서 '한 시간 걸린다'예요.",
    "@compare 사람이 집는다 :: 내가 손을 뻗어 잡는다 :: I take the bus / I take a picture :: 일이 가져간다 :: 그 일이 시간을 가져간다 :: It takes an hour / It takes time",
    "= take는 **손 뻗기**다. 내 손이든 일의 손이든 무언가를 손으로 집어 갖는다",
    "## 연습",
    "상황: 못난이는 아침마다 약을 먹는다.",
    "She ____ medicine every morning. (take / takes)",
    "> 정답: takes — 주어가 She라서 takes다. I라면 take가 된다.",
    "## 명사를 집으면 행동이 됩니다",
    "상황: 연습이 길어져 삼돌이가 하품을 한다.",
    "못난이: You look tired. Take a break.",
    "삼돌이: OK. I'll take a walk.",
    "take a break는 쉬는 시간을, take a walk는 산책을 집어 드는 말입니다.",
    "! It takes time의 주어는 It입니다. take 앞에 꼭 사람이 와야 하는 건 아니에요.",
    "~ 손을 뻗는 건 사람일 때도, 일일 때도 있습니다. 무엇이든 손으로 집어 갖는 그림이죠.",
    "## 비교",
    "사람이 — I take the bus. (나는 버스를 타요.)",
    "일이 — It takes an hour. (한 시간 걸려요.)",
    "## 연습",
    "상황: 집에서 학교까지 30분이 걸린다.",
    "It ____ thirty minutes. (takes / take)",
    "> 정답: takes — 주어가 It이면 takes다. 일이 30분을 가져가는 그림이다.",
    "+ take는 손을 뻗어 무언가를 집어 갖는 그림이다. 사람도 일도 주어가 되고, 버스도 시간도 집어 간다."
  ],
  23: [
    "## 상황",
    "도서관 앞이다. 삼돌이가 책 한 권 이야기를 꺼낸다.",
    "## 대화 A",
    "못난이: Do you have a new book?",
    "삼돌이: Yes. I got it yesterday. Now I have it.",
    "got은 책이 내게 오던 순간, have는 지금 내 것인 상태입니다. 영상 끝에 사진이 남았어요.",
    "## 대화 B",
    "못난이: Can I read it?",
    "삼돌이: Sure. Take it.",
    "이번엔 책이 오는 게 아니라 손이 나갑니다. 삼돌이가 내민 책을 못난이가 손을 뻗어 집어 드는 행동, take예요.",
    "@compare get :: 나에게 오는 과정 :: I got a book / I get tired :: take :: 내가 손을 뻗어 집는 행동 :: I take a book / I take a bus",
    "= have는 **사진**(상태), get은 **영상**(오는 과정), take는 **손**(뻗는 행동)이다",
    "## 연습",
    "상황: 통장에 돈이 들어 있다.",
    "I ____ money in the bank. (have / take)",
    "> 정답: have — 지금 통장에 들어 있는 상태다. 상태는 have다.",
    "## 일자리로 보면",
    "상황: 민준이 새 아르바이트 이야기를 한다.",
    "못난이: Do you have a job now?",
    "민준: Yes. I got an offer, and I took the job.",
    "got an offer는 제안이 오는 과정, took the job은 손을 뻗어 받아들이는 행동입니다.",
    "~ 책 한 권, 일자리 하나. 대상은 같고 사진이냐 영상이냐 손이냐만 다릅니다.",
    "## 비교",
    "have — I have a job. (나는 일자리가 있어요.)",
    "get — I got a job. (나는 일자리를 얻었어요.)",
    "take — I took the job. (나는 그 일자리를 받아들였어요.)",
    "## 연습",
    "상황: 삼돌이가 도서관에서 책을 집어 든다.",
    "Can I ____ this book home? (take / have)",
    "> 정답: take — 책을 집으로 가져가는 행동이다. 가져가는 방향은 take다.",
    "+ 같은 책도 have는 사진, get은 영상, take는 손이다. 세 동사는 상태·과정·행동으로 나뉜다."
  ],
  24: [
    "## 한눈에",
    "17과 — 끈 — I have a sister. (나에게는 여동생이 있어요.)",
    "18과 — 다리 — I have been to Seoul. (서울에 가 본 적이 있어요.)",
    "19과 — 짐 — I have to call my mom. (엄마에게 전화해야 해요.)",
    "20과 — 상자 — I have dinner. (나는 저녁을 먹어요.)",
    "21과 — 문턱 — I get hungry. (나는 배가 고파져요.)",
    "22과 — 손 뻗기 — I take a picture. (나는 사진을 찍어요.)",
    "23과 — 사진·영상·손 — I got a book. (나는 책을 얻었어요.)",
    "= 셋째 달은 세 동사다. have는 **이어져** 있고, get은 문턱을 **넘고**, take는 손을 **뻗는다**",
    "@compare get :: 받거나 변한다 :: I got a gift / I get hungry :: take :: 내가 뻗어 가져온다 :: I take a picture / I take a break",
    "~ 세 동사가 묻는 건 하나입니다. 그 일이 나에게 이어져 있나, 들어오나, 내가 집어 오나.",
    "## 연습",
    "상황: 버스가 느려서 집에서 학교까지 한 시간이 걸린다.",
    "It ____ an hour. (takes / gets)",
    "> 정답: takes — 일이 한 시간을 가져간다. 걸린다는 말은 take다.",
    "## 연습",
    "상황: 삼돌이는 엄마가 정한 규칙 때문에 아홉 시까지 집에 가야 한다.",
    "I ____ go home by nine. (have to / take)",
    "> 정답: have to — 해야 할 일을 짐처럼 메고 있다. 규칙이 시켜도 have to다.",
    "+ 셋째 달의 뼈대는 세 동사다. 이어진 것(have), 들어오는 것(get), 내가 집는 것(take)."
  ],
  25: [
    "## 상황",
    "하교한 지호가 우체국 앞에 섰다. 손에는 엄마께 보낼 카드가 있다.",
    "## 대화 A",
    "친구: Where are you going?",
    "지호: I'm going to the post office.",
    "지호의 몸이 화살표를 따라 우체국에 도착합니다. to 뒤에는 도착하는 곳이 옵니다.",
    "## 대화 B",
    "친구: What will you do with that card?",
    "지호: I'll send it to my mom.",
    "이번엔 몸이 아니라 카드가 날아갑니다. 화살촉 끝에서 엄마가 받습니다.",
    "@compare 몸이 가요 :: 내가 도착점으로 간다 :: go to the library / walk to the park :: 물건이 가요 :: 카드와 말이 사람에게 도착한다 :: send it to my mom / say hi to him",
    "= to는 **화살표**입니다. 몸이든 물건이든 끝에는 **도착점**이 있습니다",
    "## 연습",
    "상황: 지호가 동생에게 사탕을 건넨다.",
    "I give the candy ____ my brother. (to / in)",
    "> 정답: to — 사탕이 손을 떠나 동생에게 도착합니다.",
    "## 마음이 먼저 가면",
    "상황: 시계를 본 지호가 하품을 한다.",
    "친구: Are you tired?",
    "지호: Yes. I want to sleep.",
    "몸은 아직 여기 있고, 마음만 먼저 '자기'로 갑니다. 마음도 화살표를 탄 거죠.",
    "! to 뒤에는 장소만 오는 게 아닙니다. 아직 안 한 행동이 올 때도 있습니다.",
    "~ 몸이 가든, 카드가 가든, 마음이 가든 그림은 하나입니다. 화살촉 끝의 **도착점**이죠.",
    "## 비교",
    "몸 — She walks to the park. (그녀는 공원으로 걸어가요.)",
    "말 — He says hello to me. (그는 나에게 인사해요.)",
    "## 연습",
    "상황: 지호가 할머니께 편지를 부친다.",
    "I send this letter ____ my grandma. (to / at)",
    "> 정답: to — 편지가 날아가서 할머니께 도착합니다.",
    "+ to는 화살표 하나입니다. 몸도 물건도 마음도 화살촉 끝의 도착점으로 갑니다."
  ],
  26: [
    "## 상황",
    "수아가 현관을 나서려는데 엄마가 뒤에서 부른다.",
    "## 대화 A",
    "엄마: Did you lock the door?",
    "수아: Yes. I remember locking it.",
    "-ing는 이미 한 일을 떠올립니다. 뒤를 돌아보는 그림이죠.",
    "## 대화 B",
    "엄마: Lock it again tonight.",
    "수아: OK. I'll remember to lock it.",
    "to는 앞으로 할 일로 가는 화살표입니다. 아직 안 한 일이에요.",
    "@compare -ing :: 이미 한 일을 떠올린다 :: remember locking it :: to :: 앞으로 할 일로 간다 :: remember to lock it",
    "= remember·forget 같은 낱말 뒤에서 -ing는 **뒤돌아보기**, to는 **앞으로 가는 화살표**입니다",
    "## 연습",
    "상황: 수아가 어제 창문을 닫은 걸 기억한다.",
    "I remember ____ the window yesterday. (closing / to close)",
    "> 정답: closing — 이미 한 일을 뒤돌아보니 -ing입니다.",
    "## to는 목적도 됩니다",
    "상황: 수아가 빵집에 들어왔다.",
    "친구: Why did you come here?",
    "수아: I came here to buy bread.",
    "빵을 사는 일로 가는 화살표입니다. '사려고'라는 목적이 됩니다.",
    "! to 뒤의 동사는 -s나 -ed를 붙이지 않고 원래 모양 그대로 씁니다.",
    "~ remember 같은 낱말에서는 뒤를 보면 -ing, 앞을 보면 to. 화살표는 늘 앞으로 갑니다.",
    "## 비교",
    "뒤돌아봄 — I remember meeting her. (그녀를 만난 걸 기억해요.)",
    "앞으로 감 — Remember to call her. (그녀에게 전화할 것을 잊지 마세요.)",
    "## 연습",
    "엄마: Why did you go to the market?",
    "수아: I went there ____ eggs. (to buy / buy)",
    "> 정답: to buy — 사는 일은 아직 안 한 행동이라 to를 붙입니다.",
    "+ to 부정사는 앞으로 가는 화살표입니다. remember 같은 낱말에서 -ing는 한 일, to는 안 한 일을 봅니다."
  ],
  27: [
    "## 상황",
    "하윤이 아빠 생일 케이크를 사 들고 집에 들어왔다.",
    "## 대화 A",
    "동생: Who is the cake for?",
    "하윤: It's for my dad.",
    "케이크가 걸어가진 않습니다. 하윤의 마음이 아빠를 향해요. for 뒤에 그 사람이 옵니다.",
    "## 대화 B",
    "아빠: Thank you for the cake.",
    "하윤: You're welcome, Dad.",
    "이번엔 아빠의 마음입니다. 고마운 마음이 케이크를 향해요. for 뒤에 고마운 **이유**가 옵니다.",
    "@compare to :: 몸이나 물건이 도착한다 :: go to the shop :: for :: 마음이 향한다 :: a cake for my dad / thank you for the cake",
    "= for는 **마음의 방향**입니다. 마음이 향한 사람이나 이유 앞에 붙습니다",
    "## 연습",
    "상황: 친구가 우산을 빌려줬다. 하윤이 인사한다.",
    "Thank you ____ the umbrella. (for / in)",
    "> 정답: for — 고마운 마음이 우산을 향합니다. 고마운 이유가 for 뒤에 옵니다.",
    "## 기다리는 마음도 for",
    "상황: 비 오는 정류장에 하윤이 서 있다.",
    "친구: Who are you waiting for?",
    "하윤: I'm waiting for my sister.",
    "몸은 정류장에 있어도 마음은 동생을 향해 있습니다. 그 방향이 for예요.",
    "! Thank you for를 '~를 위해'로 옮기지 마세요. for 뒤는 고마운 이유입니다.",
    "~ 선물도, 고마움도, 기다림도 마음이 어디를 보느냐의 문제입니다. 그 방향이 for죠.",
    "## 비교",
    "몸 — She goes to the shop. (그녀는 가게로 가요.)",
    "마음 — This gift is for her. (이 선물은 그녀를 위한 거예요.)",
    "## 연습",
    "상황: 하윤이 내일 시험 공부를 한다.",
    "I'm studying ____ the test. (for / at)",
    "> 정답: for — 마음이 시험을 향해 있습니다.",
    "+ for는 마음의 방향입니다. 마음이 향한 사람, 기다리는 대상, 고마운 이유 앞에 씁니다."
  ],
  28: [
    "## 상황",
    "학교에 가려던 유리가 현관에서 허둥댄다.",
    "## 대화 A",
    "유리: Where is my phone?",
    "동생: It's in your bag.",
    "가방은 눈에 보이는 **테두리**입니다. 폰이 그 테두리 안에 들어 있어요.",
    "## 대화 B",
    "동생: Why are you running?",
    "유리: I'm in a hurry.",
    "서두름에는 눈에 안 보이는 테두리가 있습니다. 유리가 그 안에 들어가 있는 거죠.",
    "@compare 눈에 보이는 테두리 :: 가방·방·나라 안이다 :: in your bag / in Seoul :: 눈에 안 보이는 테두리 :: 때나 상황 안이다 :: in the evening / in a hurry",
    "= in은 **테두리**입니다. 공간이든 때든 상황이든 그 안에 있으면 in입니다",
    "## 연습",
    "상황: 열쇠가 서랍 속에 있다.",
    "The key is ____ the drawer. (in / to)",
    "> 정답: in — 서랍이라는 테두리 안에 열쇠가 들어 있습니다.",
    "## 때도 테두리입니다",
    "상황: 저녁에 학교에서 파티가 열린다.",
    "친구: When is the party?",
    "유리: The party is in the evening.",
    "저녁이라는 시간 테두리 안에 파티가 들어 있어요. 시계에 선은 없어도 테두리는 있습니다.",
    "! 정확한 시각 하나는 in이 아니라 at입니다. in seven o'clock은 틀린 말이에요.",
    "~ 가방이든 저녁이든 서두름이든, 테두리를 그리고 그 안에 있으면 그림은 in입니다.",
    "## 비교",
    "공간 — I live in Seoul. (나는 서울에 살아요.)",
    "상황 — She is in trouble. (그녀는 곤란한 상황이에요.)",
    "## 연습",
    "상황: 유리가 운동하는 때를 말한다. 아침이다.",
    "I exercise ____ the morning. (in / at)",
    "> 정답: in — 아침이라는 시간 테두리 안에서 운동합니다.",
    "+ in은 테두리 안입니다. 공간이든 때든 상황이든 테두리를 그리고 그 안에 들어가 있는 그림입니다."
  ],
  29: [
    "## 상황",
    "학교 축제 날. 유나가 정문 앞에서 친구를 기다린다.",
    "## 대화 A",
    "친구: Where are you?",
    "유나: I'm at the gate.",
    "정문이라는 정확한 **한 점**에 핀을 꽂은 거죠. 넓은 학교가 아니라 딱 그 자리입니다.",
    "## 대화 B",
    "친구: When does the show start?",
    "유나: It starts at two o'clock.",
    "하루라는 긴 선 위에 2시라는 점 하나를 찍었습니다. 시각도 한 점이에요.",
    "@compare in :: 넓은 테두리 안 :: in the school / in the afternoon :: at :: 콕 찍은 한 점 :: at the gate / at two o'clock",
    "= at은 **핀 하나**입니다. 장소도 시각도 눈길도 딱 한 점만 콕 찍습니다",
    "## 연습",
    "상황: 유나가 정문에서 만나자고 한다.",
    "Let's meet ____ the gate. (at / for)",
    "> 정답: at — 정문이라는 정확한 한 점에서 만납니다.",
    "## 눈길도 한 점입니다",
    "상황: 무대 위에 가수 한 명이 올라왔다.",
    "친구: What are you looking at?",
    "유나: I'm looking at the singer.",
    "눈길이 가수 한 사람에게 꽂힙니다. 그 한 점에 초점이 맞았어요.",
    "! 정확한 시각은 in이 아니라 at입니다. 아침·저녁처럼 넓은 때는 in입니다.",
    "~ 정문이든 2시든 가수의 얼굴이든, 콕 찍은 한 점이면 그림은 at입니다.",
    "## 비교",
    "점 — She is good at singing. (그녀는 노래를 잘해요.)",
    "넓이 — She lives in Korea. (그녀는 한국에 살아요.)",
    "## 연습",
    "상황: 안내판에 콘서트가 7시 정각에 시작한다고 적혀 있다.",
    "The concert starts ____ seven o'clock. (at / in)",
    "> 정답: at — 7시라는 정확한 한 점입니다.",
    "+ at은 지도에 핀을 꽂는 것과 같습니다. 위치 하나, 시각 하나, 눈길 하나를 콕 찍습니다."
  ],
  30: [
    "## 상황",
    "체육관 벽에 공연 포스터가 붙어 있다. 도현이 그 앞에 서 있다.",
    "## 대화 A",
    "친구: Where is the poster?",
    "도현: It's on the wall.",
    "포스터가 벽에 딱 **붙어** 있습니다. 위에 얹힌 게 아니라 닿아 있는 거죠.",
    "## 대화 B",
    "친구: Do you want some cake?",
    "도현: No, thanks. I'm on a diet.",
    "이번엔 물건이 아니라 사람이 붙었습니다. 다이어트라는 활동에 도현이 붙어 있어요.",
    "@compare 물건 :: 면에 닿아 있다 :: on the wall / on the shelf :: 활동·날짜 :: 활동이나 날에 붙어 있다 :: on a diet / on Friday",
    "= on은 **접촉**입니다. 물건은 면에, 사람은 활동에 딱 붙어 있습니다",
    "## 연습",
    "상황: 그림이 벽에 걸려 있다.",
    "The picture is ____ the wall. (on / for)",
    "> 정답: on — 그림이 벽에 닿아 붙어 있습니다.",
    "## 날짜에도 붙습니다",
    "상황: 게시판에 공연 안내가 붙었다.",
    "친구: When is the show?",
    "도현: The show is on Friday.",
    "달력의 금요일이라는 날에 공연이 딱 붙어 있습니다.",
    "! on은 '위'만이 아닙니다. 벽에도 천장에도 닿아 있으면 on입니다.",
    "~ 벽이든 다이어트든 금요일이든, 딱 붙어 있으면 그림은 on입니다.",
    "## 비교",
    "물건 — The cat is on the sofa. (고양이가 소파에 있어요.)",
    "활동 — She is on a trip. (그녀는 여행 중이에요.)",
    "## 연습",
    "친구: Where is Mina?",
    "도현: She is ____ a trip. (on / at)",
    "> 정답: on — 여행이라는 활동에 붙어 있습니다.",
    "+ on은 위가 아니라 접촉입니다. 물건은 면에, 사람은 활동이나 날짜에 닿아 있는 그림입니다."
  ],
  31: [
    "## 상황",
    "일요일 공원. 하나가 벤치에 앉은 민호를 만났다. 옆에 낯선 남자애가 서 있고, 민호 옷은 젖어 있다.",
    "## 대화 A",
    "하나: Who is that boy?",
    "민호: He is a friend of mine.",
    "'내 친구들'이라는 큰 무리에서 나온 한 명입니다. of는 이렇게 **머릿속** 관계를 말해요.",
    "## 대화 B",
    "하나: Why are you wet?",
    "민호: I fell off my bike.",
    "이번엔 몸입니다. 자전거에 붙어 있던 민호가 **실제로** 떨어져 나왔어요. 그래서 off입니다.",
    "@compare of :: 큰 것에서 나온 한 부분 (머릿속 관계) :: a friend of mine / a cup of tea :: off :: 붙어 있던 것이 떨어짐 (몸·물건·명단) :: fall off my bike / get off the bus",
    "= of와 off는 **떨어져 나옴**입니다. of는 **머릿속 관계**, off는 **붙어 있던 것이 떨어짐**",
    "## 연습",
    "상황: 민호가 종점에서 버스를 내린다.",
    "He gets ____ the bus. (off / of)",
    "> 정답: off — 버스에 붙어 있던 몸이 실제로 떨어져 나옵니다.",
    "## 한 잔도 of",
    "상황: 카페에서 민호가 컵을 든다.",
    "하나: What is that?",
    "민호: It's a cup of tea.",
    "차라는 큰 것에서 나온 한 잔입니다. 몸으로 뗀 게 아니라 머릿속에서 나눈 관계예요.",
    "! off는 '끄다'만이 아닙니다. 붙어 있던 것이 떨어지면 다 off입니다. 명단에서 빠지는 것도요.",
    "~ 친구든 차 한 잔이든 자전거든 그림은 '떨어져 나옴'입니다. 머릿속에서 나누면 of, 몸으로 떨어지면 off죠.",
    "## 비교",
    "of — the top of the hill (언덕의 꼭대기)",
    "off — Jump off the wall. (담에서 뛰어내려요.)",
    "## 연습",
    "상황: 종이가 책상에서 바닥으로 떨어졌다.",
    "It fell ____ the desk. (off / of)",
    "> 정답: off — 책상에 있던 종이가 실제로 떨어져 나왔습니다.",
    "+ of는 머릿속 관계, off는 붙어 있던 것이 떨어짐입니다. 둘 다 '떨어져 나옴'이라는 한 뿌리에서 나왔습니다."
  ],
  32: [
    "## 한눈에",
    "25과 — 화살표 — I go to the library. (나는 도서관에 가요.)",
    "26과 — 앞으로 가는 화살표 — I'll remember to lock it. (그걸 잠그는 걸 잊지 않을게요.)",
    "27과 — 마음의 방향 — This gift is for her. (이 선물은 그녀를 위한 거예요.)",
    "28과 — 테두리 — She is in the kitchen. (그녀는 부엌 안에 있어요.)",
    "29과 — 한 점 — She is good at chess. (그녀는 체스를 잘해요.)",
    "30과 — 접촉 — The book is on the shelf. (책이 선반에 있어요.)",
    "31과 — 떨어져 나옴 — The cat jumped off the sofa. (고양이가 소파에서 뛰어내렸어요.)",
    "= 전치사는 외우는 게 아니라 **그림**입니다. 문장을 만나면 어떤 그림인지만 고르면 됩니다",
    "@compare at :: 콕 찍은 한 점 :: at the gate / at two o'clock :: in :: 테두리 안 :: in the bag / in the evening",
    "~ 점이면 at, 테두리면 in, 붙었으면 on. 새 문장을 만나도 **그림부터** 물어보면 됩니다.",
    "## 연습",
    "상황: 게시판에 공연 날짜가 적혀 있다.",
    "The show is ____ Friday. (on / in)",
    "> 정답: on — 금요일이라는 날짜에 딱 붙어 있습니다.",
    "## 연습",
    "상황: 정류장에서 버스를 기다린다.",
    "I'm waiting ____ the bus. (for / to)",
    "> 정답: for — 마음이 버스를 향해 기다립니다.",
    "+ 전치사는 단어가 아니라 그림입니다. 이번 달 일곱 그림이 머리에 있으면 새 문장도 읽힙니다."
  ],
};

// 카드 위 캐릭터의 시작 그림(images/ch/<이름>.webp). 원본 표: 시범/캐릭터배정.json
const faceData = {
  1: "cheer_active",
  2: "thinking",
  3: "default_active",
  4: "surprised",
  5: "thinking_active",
  6: "default",
  7: "cheer",
  8: "happy",
  9: "surprised_active",
  10: "default",
  11: "thinking",
  12: "default_active",
  13: "tired",
  14: "cheer_active",
  15: "sad",
  16: "happy",
  17: "default",
  18: "thinking_active",
  19: "tired_active",
  20: "default_active",
  21: "surprised",
  22: "cheer_active",
  23: "thinking",
  24: "happy",
  25: "cheer",
  26: "thinking_active",
  27: "default_active",
  28: "default",
  29: "surprised",
  30: "thinking",
  31: "tired_active",
  32: "happy",
};
