// 연습문제 — 과당 7문제
// t: scene 장면 · choice 고르기 · fill 채우기 · order 조립 · analyze 분석

const quizData = {
  1: { core: "영어는 주어 → 동사 → 목적어 순서. 순서가 바뀌면 뜻이 바뀐다.", qs: [
    {"t": "scene", "ctx": "EP.1, 민준이 못난이 노트를 보고", "q": "민준: I ______ you.", "opts": ["need", "needs", "needing", "to need"], "a": "need", "why": "주어 I 다음 바로 동사. 이 세 단어가 오늘 배울 전부다."},
    {"t": "choice", "q": "다음 중 영어 순서로 맞는 것은?", "opts": ["I pizza eat", "I eat pizza", "Eat I pizza", "Pizza I eat"], "a": "I eat pizza"},
    {"t": "choice", "q": "She music likes가 틀린 이유는?", "opts": ["동사가 빠져서", "목적어가 동사보다 앞에 있어서", "주어가 없어서", "단어가 모자라서"], "a": "목적어가 동사보다 앞에 있어서"},
    {"t": "fill", "q": "We ______ English.", "lead": "빈칸에 동사를 넣으세요", "a": "study", "hint": "study"},
    {"t": "fill", "q": "They ______ soccer.", "lead": "우리말을 영어 순서로 바꿔 쓰세요", "a": "play"},
    {"t": "order", "words": ["soccer", "They", "play"], "q": "단어를 순서대로 놓으세요", "a": "They play soccer."},
    {"t": "analyze", "q": "아래 문장의 주어·동사·목적어를 찾으세요\nMy friend loves music.", "a": "주어 My friend / 동사 loves / 목적어 music"},
  ] },
  2: { core: "문장 맨 앞은 언제나 주어 + 동사. 뒤에 뭐가 붙어도 안 변한다.", qs: [
    {"t": "scene", "ctx": "EP.2, 삼돌이가 민준을 밀어내며", "q": "삼돌이: I ______ do groups.", "opts": ["don't", "not", "no", "doesn't"], "a": "don't", "why": "주어 I 다음 바로 동사 자리. 거절도 순서를 지킨다."},
    {"t": "choice", "q": "The boy eats apples every day에서 동사는?", "opts": ["The boy", "eats", "apples", "every day"], "a": "eats"},
    {"t": "choice", "q": "주어와 동사가 바르게 짝지어진 것은?", "opts": ["My friend / in Seoul", "My friend / lives", "lives / in Seoul", "Seoul / lives"], "a": "My friend / lives"},
    {"t": "fill", "q": "______ sleeps early.", "lead": "주어를 넣으세요", "a": "She", "hint": "She"},
    {"t": "fill", "q": "Dogs ______ fast.", "lead": "동사를 넣으세요", "a": "run", "hint": "run"},
    {"t": "order", "words": ["every", "eats", "day", "The boy", "apples"], "q": "단어를 순서대로 놓으세요", "a": "The boy eats apples every day."},
    {"t": "analyze", "q": "이 문장에서 '누가 뭘 하는지'만 뽑으세요\nMy little sister draws pictures in her room.", "a": "My little sister draws", "why": "나머지는 다 덧붙임"},
  ] },
  3: { core: "주어 + 동사 + 목적어. 아는 단어를 그 자리에 놓으면 끝.", qs: [
    {"t": "scene", "ctx": "EP.3, 민준이 노트를 다 읽었다고 말하며", "q": "민준: I ______ it. All of it.", "opts": ["read", "reading", "reads", "to read"], "a": "read", "why": "I(주어) read(동사) it(목적어). 세 칸이 다 찼다."},
    {"t": "choice", "q": "'나는 마라탕을 먹는다'를 영어 순서로 하면?", "opts": ["I malatang eat", "Eat malatang I", "I eat malatang", "Malatang I eat"], "a": "I eat malatang"},
    {"t": "choice", "q": "목적어가 있는 문장은?", "opts": ["She sleeps", "Birds fly", "We study English", "It rains"], "a": "We study English"},
    {"t": "fill", "q": "I eat ______.", "lead": "목적어를 넣으세요", "a": "pizza", "hint": "pizza"},
    {"t": "fill", "q": "They ______ soccer.", "lead": "동사를 넣으세요", "a": "like", "hint": "like"},
    {"t": "order", "words": ["English", "study", "We"], "q": "단어를 순서대로 놓으세요", "a": "We study English."},
    {"t": "analyze", "q": "두 문장의 뜻 차이를 말해보세요\n① I love you. ② You love me.", "a": "단어는 같고 순서만 다른데 사랑하는 사람이 바뀐다"},
  ] },
  4: { core: "주어가 아무리 길어도 **첫 번째 동사** 앞까지가 전부 주어.", qs: [
    {"t": "scene", "ctx": "EP.4 **[대사 추가 제안]**", "q": "*현재 EP.4는 대사가 다 짧아서 긴 주어가 없다. 삼돌이가 노트 조각을 건네는 장면에 이 한 줄을 넣으면 딱 맞는다.*\n삼돌이: The person who wrote this ______ brave.", "opts": ["is", "are", "be", "being"], "a": "is", "why": "The person who wrote this 전체가 주어. 첫 동사는 is."},
    {"t": "choice", "q": "The man with a red hat is happy에서 주어는?", "opts": ["The man", "The man with a red hat", "a red hat", "is happy"], "a": "The man with a red hat"},
    {"t": "choice", "q": "긴 주어를 찾는 방법은?", "opts": ["가장 긴 단어를 찾는다", "첫 번째 동사를 찾는다", "맨 앞 세 단어를 본다", "물음표를 찾는다"], "a": "첫 번째 동사를 찾는다"},
    {"t": "fill", "q": "The girls in my class ______ kind.", "lead": "동사를 넣으세요", "a": "are", "hint": "are"},
    {"t": "fill", "q": "The boy who sits next to me ______ in Busan.", "lead": "동사를 넣으세요", "a": "lives", "hint": "lives"},
    {"t": "order", "words": ["is", "The cat", "on the sofa", "sleeping"], "q": "단어를 순서대로 놓으세요", "a": "The cat on the sofa is sleeping."},
    {"t": "analyze", "q": "어디까지가 주어인가\nThe man with a red hat who is wearing blue jeans is happy.", "a": "The man with a red hat who is wearing blue jeans", "why": "마지막 is 앞까지"},
  ] },
  5: { core: "a는 특정한 하나, -s는 종류 전체. 둘 다 없으면 틀린 문장.", qs: [
    {"t": "scene", "ctx": "EP.5, 삼돌이가 조건을 거는 장면", "q": "삼돌이: ...______ week.", "opts": ["One", "Ones", "A weeks", "Week"], "a": "One", "why": "딱 한 주. 숫자를 밝혔기 때문에 약속이 된다."},
    {"t": "choice", "q": "I like a dog의 뜻은?", "opts": ["개를 다 좋아해", "특정한 개 한 마리를 좋아해", "개가 싫어", "개를 키운다"], "a": "특정한 개 한 마리를 좋아해"},
    {"t": "choice", "q": "틀린 문장은?", "opts": ["I have a dog", "I have dogs", "I have dog", "I have two dogs"], "a": "I have dog", "why": "숫자를 안 밝혔다"},
    {"t": "fill", "q": "I have ______ apple.", "lead": "a를 넣을지 -s를 붙일지 정하세요", "a": "an"},
    {"t": "fill", "q": "I like ______.", "lead": "같은 방법으로", "a": "books"},
    {"t": "order", "words": ["a", "bought", "I", "car"], "q": "단어를 순서대로 놓으세요", "a": "I bought a car."},
    {"t": "analyze", "q": "두 문장이 어떻게 다른가\n① She likes a cat. ② She likes cats.", "a": "①은 특정한 고양이 한 마리, ②는 고양이라는 동물 전체"},
  ] },
  6: { core: "한 개면 단수, 여러 개면 복수. 영어는 반드시 밝힌다.", qs: [
    {"t": "scene", "ctx": "EP.6, 삼돌이가 전학을 통보하며", "q": "삼돌이: I transfer next ______.", "opts": ["month", "months", "a months", "monthes"], "a": "month", "why": "다음 달 하나. 여러 달이면 뜻이 달라진다."},
    {"t": "choice", "q": "There ______ apples. 빈칸은?", "opts": ["is", "are", "am", "be"], "a": "are"},
    {"t": "choice", "q": "복수형이 특별한 단어는?", "opts": ["book → books", "car → cars", "person → people", "dog → dogs"], "a": "person → people"},
    {"t": "fill", "q": "There ______ an apple on the table.", "lead": "빈칸을 채우세요", "a": "is"},
    {"t": "fill", "q": "I have ______.", "lead": "복수로 바꿔 쓰세요", "a": "books"},
    {"t": "order", "words": ["are", "There", "three", "cats"], "q": "단어를 순서대로 놓으세요", "a": "There are three cats."},
    {"t": "analyze", "q": "우리말과 영어의 차이\n한국어 \"사과 있다\"는 되는데 영어 \"There is apple\"은 왜 안 될까?", "a": "한국어는 숫자를 안 따져도 되고 영어는 반드시 밝혀야 하기 때문"},
  ] },
  7: { core: "셀 수 없는 명사엔 a도 s도 안 붙는다. 단, 잔·달러를 빌리면 셀 수 있다.", qs: [
    {"t": "scene", "ctx": "EP.7, 밤새 연습한 민준이", "q": "민준: I lost ______.", "opts": ["count", "a count", "counts", "the counts"], "a": "count", "why": "셀 수 없을 만큼 했다는 뜻. 그래서 a도 s도 안 붙는다."},
    {"t": "choice", "q": "셀 수 없는 명사는?", "opts": ["apple", "book", "water", "car"], "a": "water"},
    {"t": "choice", "q": "a glass of water가 뜻하는 것은?", "opts": ["물 전체", "물 한 잔", "유리컵", "물이 없음"], "a": "물 한 잔"},
    {"t": "fill", "q": "I need ______ money.", "lead": "알맞게 채우세요", "a": "(아무것도 안 씀)", "hint": "a / 아무것도 안 씀"},
    {"t": "fill", "q": "I need ______ book.", "lead": "같은 방법으로", "a": "a"},
    {"t": "order", "words": ["of", "two", "water", "glasses"], "q": "단어를 순서대로 놓으세요", "a": "two glasses of water"},
    {"t": "analyze", "q": "왜 셀 수 있게 되었나\nmoney는 셀 수 없는데 two dollars는 왜 될까?", "a": "달러라는 단위를 빌려왔기 때문. 그릇을 씌우면 셀 수 있게 된다"},
  ] },
  8: { core: "단수 주어 → 동사에 s. 복수 주어 → 동사에 s 없음.", qs: [
    {"t": "scene", "ctx": "EP.8, 못난이가 삼돌이 집 앞에서 쏟아내며", "q": "못난이: She ______. She hides. She disappears.", "opts": ["run", "runs", "running", "ran"], "a": "runs", "why": "주어 She가 단수라서 동사마다 s가 붙는다. 세 번 다."},
    {"t": "choice", "q": "맞는 문장은?", "opts": ["He like pizza", "He likes pizza", "They likes pizza", "He liking pizza"], "a": "He likes pizza"},
    {"t": "choice", "q": "They ______ hard. 빈칸은?", "opts": ["works", "work", "working", "to work"], "a": "work"},
    {"t": "fill", "q": "She ______ English every day.", "lead": "알맞은 형태로", "a": "studies", "hint": "study"},
    {"t": "fill", "q": "He ______ a book.", "lead": "같은 방법으로", "a": "has", "hint": "have"},
    {"t": "order", "words": ["pizza", "likes", "My brother"], "q": "단어를 순서대로 놓으세요", "a": "My brother likes pizza."},
    {"t": "analyze", "q": "왜 반대인가\n명사는 여러 개일 때 s가 붙는데, 동사는 왜 하나일 때 s가 붙을까?", "a": "명사에 s가 없으면 동사가 대신 받는다. 둘 중 하나에만 s가 있어서 공평해진다"},
  ] },
  9: { core: "be 동사는 뜻이 없다. 주어와 상태를 등호처럼 잇기만 한다.", qs: [
    {"t": "scene", "ctx": "EP.9, 돌아온 삼돌이를 보고", "q": "못난이: You'______ here.", "opts": ["re", "s", "m", "ve"], "a": "re", "why": "You are here의 줄임. are는 뜻이 없다. You와 here를 잇기만 한다."},
    {"t": "choice", "q": "be 동사가 하는 일은?", "opts": ["달린다", "연결한다", "먹는다", "사랑한다"], "a": "연결한다"},
    {"t": "fill", "q": "I ______ happy.", "lead": "빈칸을 채우세요", "a": "am", "hint": "am / is / are"},
    {"t": "fill", "q": "She ______ tall.", "lead": "같은 방법으로", "a": "is"},
    {"t": "order", "words": ["smart", "You", "are"], "q": "단어를 순서대로 놓으세요", "a": "You are smart."},
    {"t": "order", "words": ["a", "is", "He", "teacher"], "q": "단어를 순서대로 놓으세요", "a": "He is a teacher."},
    {"t": "analyze", "q": "왜 빈 컵인가\nbe 동사에 뜻이 없는 게 왜 오히려 좋을까?", "a": "뜻이 없으니 어떤 상태든 담을 수 있다. 물도 커피도 담기는 빈 컵처럼"},
  ] },
  10: { core: "행동은 일반 동사, 상태는 be 동사. be가 보이면 상태 이야기다.", qs: [
    {"t": "scene", "ctx": "EP.10, 무너진 민준이 애써 버티며", "q": "민준: I ______ fine.", "opts": ["am", "do", "have", "feel"], "a": "am", "why": "괜찮다는 건 행동이 아니라 상태다. 그런데 손은 떨리고 있다."},
    {"t": "choice", "q": "상태를 말하는 문장은?", "opts": ["She runs", "She eats", "She is tired", "She sings"], "a": "She is tired"},
    {"t": "fill", "q": "He ______ a teacher.", "lead": "빈칸을 채우세요", "a": "is", "hint": "is"},
    {"t": "fill", "q": "They ______ kind.", "lead": "같은 방법으로", "a": "are", "hint": "are"},
    {"t": "order", "words": ["tired", "am", "I"], "q": "단어를 순서대로 놓으세요", "a": "I am tired."},
    {"t": "order", "words": ["is", "The room", "clean"], "q": "단어를 순서대로 놓으세요", "a": "The room is clean."},
    {"t": "analyze", "q": "무엇이 다른가\n① I run every day. ② I am tired.", "a": "①은 하는 일(행동), ②는 지금 어떤지(상태)"},
  ] },
  11: { core: "I는 am, You는 are, 나머지는 is. 주어를 먼저 보고 고른다.", qs: [
    {"t": "scene", "ctx": "EP.11, 웃음을 참지 못하면서", "q": "삼돌이: I ______ not laughing.", "opts": ["am", "is", "are", "be"], "a": "am", "why": "주어가 I니까 am. 어깨는 들썩이는데 말은 아니라고 한다."},
    {"t": "choice", "q": "He ______ smart. 빈칸은?", "opts": ["am", "is", "are", "be"], "a": "is"},
    {"t": "fill", "q": "You ______ my friend.", "lead": "빈칸을 채우세요", "a": "are"},
    {"t": "fill", "q": "We ______ ready.", "lead": "같은 방법으로", "a": "are"},
    {"t": "order", "words": ["happy", "I", "am"], "q": "단어를 순서대로 놓으세요", "a": "I am happy."},
    {"t": "order", "words": ["are", "You", "late"], "q": "단어를 순서대로 놓으세요", "a": "You are late."},
    {"t": "analyze", "q": "한국어와 무엇이 다른가\n한국어는 \"나는/너는/그는 행복하다\"로 다 같은데 영어는 왜 다를까?", "a": "영어는 주어마다 자기 be 동사를 따로 준다"},
  ] },
  12: { core: "be + 동사ing = 지금 그 행동을 하고 있는 **상태**.", qs: [
    {"t": "scene", "ctx": "EP.12, 지우려는 민준을 막고", "q": "못난이: I'm still ______.", "opts": ["decide", "deciding", "decided", "to decide"], "a": "deciding", "why": "아직 정하는 중이라는 상태. 답을 미룬 게 아니라 진행 중이다."},
    {"t": "choice", "q": "진행형 문장은?", "opts": ["I eat lunch", "I am eating lunch", "I ate lunch", "I will eat lunch"], "a": "I am eating lunch"},
    {"t": "fill", "q": "She is ______.", "lead": "진행형으로 바꾸세요", "a": "running", "hint": "run"},
    {"t": "fill", "q": "He is ______.", "lead": "같은 방법으로", "a": "sleeping", "hint": "sleep"},
    {"t": "order", "words": ["studying", "are", "We"], "q": "단어를 순서대로 놓으세요", "a": "We are studying."},
    {"t": "order", "words": ["is", "The baby", "crying"], "q": "단어를 순서대로 놓으세요", "a": "The baby is crying."},
    {"t": "analyze", "q": "왜 be 동사가 들어가나\n먹는 건 행동인데 I am eating에는 왜 be가 있을까?", "a": "be가 행동을 상태로 바꿨다. 움직이는 걸 사진처럼 멈춰 세운 것"},
  ] },
  13: { core: "누가 했는지보다 지금 어떤 **결과**인지를 말한다.", qs: [
    {"t": "scene", "ctx": "EP.13 **[대사 추가 제안]**", "q": "*현재 EP.13엔 수동태 대사가 없다. 삼돌이가 바뀐 안무를 지적하는 장면에 이 한 줄이 들어가면 맞는다.*\n삼돌이: My part ______ changed. Without asking.", "opts": ["is", "am", "are", "do"], "a": "is", "why": "누가 바꿨는지는 이미 안다. 바뀌어 있다는 결과가 중요하다."},
    {"t": "choice", "q": "수동태 문장은?", "opts": ["I broke it", "It is broken", "I break it", "Break it"], "a": "It is broken"},
    {"t": "fill", "q": "The door ______ closed.", "lead": "빈칸을 채우세요", "a": "is", "hint": "is"},
    {"t": "fill", "q": "The work is ______.", "lead": "같은 방법으로", "a": "finished", "hint": "finished"},
    {"t": "order", "words": ["cooked", "The food", "is"], "q": "단어를 순서대로 놓으세요", "a": "The food is cooked."},
    {"t": "order", "words": ["is", "window", "The", "broken"], "q": "단어를 순서대로 놓으세요", "a": "The window is broken."},
    {"t": "analyze", "q": "왜 누가 했는지 안 쓰나\nIt is broken. 여기서 부순 사람을 왜 말하지 않을까?", "a": "지금 부러진 상태가 중요하지 누가 했는지는 관심 밖이기 때문"},
  ] },
  14: { core: "be going to = 지금 그 방향으로 가고 있다. 그래서 곧 한다.", qs: [
    {"t": "scene", "ctx": "EP.14 **[대사 추가 제안]**", "q": "*going to는 지금 EP.19에 들어가 있다. 자리를 바꾸거나, 공연 이틀 전 다투는 이 장면에 넣는 게 맞다.*\n민준: We ______ going to run it again.", "opts": ["are", "is", "am", "be"], "a": "are", "why": "아직 시작 안 했지만 이미 그쪽으로 가고 있다."},
    {"t": "choice", "q": "I am going to study의 진짜 뜻은?", "opts": ["공부했다", "공부하러 가고 있다", "공부하기 싫다", "공부를 끝냈다"], "a": "공부하러 가고 있다"},
    {"t": "fill", "q": "She is ______ to leave.", "lead": "빈칸을 채우세요", "a": "going", "hint": "going"},
    {"t": "fill", "q": "We ______ going to eat.", "lead": "같은 방법으로", "a": "are", "hint": "are"},
    {"t": "order", "words": ["to", "going", "I", "sleep", "am"], "q": "단어를 순서대로 놓으세요", "a": "I am going to sleep."},
    {"t": "order", "words": ["are", "They", "to", "going", "win"], "q": "단어를 순서대로 놓으세요", "a": "They are going to win."},
    {"t": "analyze", "q": "will과 무엇이 다른가\n① I will study. ② I am going to study.", "a": "①은 지금 막 정한 것, ②는 이미 그 방향으로 움직이는 중"},
  ] },
  15: { core: "was/were는 시간 표시가 아니라 \"지금은 다르다\"는 선언.", qs: [
    {"t": "scene", "ctx": "EP.15, 민준이 삼돌이에게 인정하며", "q": "민준: You ______ right.", "opts": ["were", "was", "are", "am"], "a": "were", "why": "주어가 You라서 were. 그때 네 말이 맞았다는 뒤늦은 인정."},
    {"t": "choice", "q": "I was happy가 품고 있는 뜻은?", "opts": ["지금도 행복하다", "지금은 다르다", "앞으로 행복할 것이다", "한 번도 행복한 적 없다"], "a": "지금은 다르다"},
    {"t": "fill", "q": "She ______ a student.", "lead": "과거형으로", "a": "was", "hint": "was"},
    {"t": "fill", "q": "We ______ fine yesterday.", "lead": "같은 방법으로", "a": "were", "hint": "were"},
    {"t": "order", "words": ["tired", "He", "was"], "q": "단어를 순서대로 놓으세요", "a": "He was tired."},
    {"t": "order", "words": ["were", "They", "here"], "q": "단어를 순서대로 놓으세요", "a": "They were here."},
    {"t": "analyze", "q": "숨은 뜻 찾기\nShe was a student. 이 문장은 말하지 않은 것 하나를 알려준다. 뭘까?", "a": "지금은 학생이 아니라는 것"},
  ] },
  16: { core: "상태·진행·수동·미래·과거. 전부 be 동사 하나에서 나온다.", qs: [
    {"t": "scene", "ctx": "EP.16 **[대사 추가 제안]**", "q": "*EP.16은 have 이야기라 be동사가 거의 없다. 민준이 못난이에게 묻는 이 장면 끝에 한 줄 넣으면 총정리와 맞는다.*\n민준: So the notebook ______ your voice.", "opts": ["is", "has", "does", "do"], "a": "is", "why": "노트가 곧 네 목소리다. 등호 하나로 두 개를 이었다."},
    {"t": "choice", "q": "be 동사가 만들 수 없는 것은?", "opts": ["진행형", "수동태", "미래", "명령문"], "a": "명령문"},
    {"t": "fill", "q": "I ______ scared before the show.", "lead": "알맞은 be 동사를", "a": "was", "hint": "was"},
    {"t": "fill", "q": "They are ______ for us.", "lead": "진행형으로", "a": "waiting", "hint": "waiting"},
    {"t": "order", "words": ["going", "am", "I", "to", "try"], "q": "단어를 순서대로 놓으세요", "a": "I am going to try."},
    {"t": "order", "words": ["is", "door", "The", "locked"], "q": "단어를 순서대로 놓으세요", "a": "The door is locked."},
    {"t": "analyze", "q": "하나로 묶기\nI am happy / I am eating / It is broken / I am going to study / I was happy\n이 다섯이 결국 다 말하는 것은?", "a": "지금(또는 그때) 어떤 상태인가"},
  ] },
  17: { core: "have는 소유가 아니라 **관계**. 물건·시간·생각·경험을 나와 잇는다.", qs: [
    {"t": "scene", "ctx": "EP.17 **[대사 추가 제안]**", "q": "*EP.17엔 현재완료(18과 문법)만 있고 순수한 have가 없다. 옥상에서 삼돌이가 털어놓는 자리에 한 줄.*\n삼돌이: I ______ a reason. I just never say it.", "opts": ["have", "has", "having", "am"], "a": "have", "why": "이유를 갖고 있다. 물건이 아닌 것도 have로 잇는다."},
    {"t": "choice", "q": "have를 쓸 수 없는 것은?", "opts": ["I have a car", "I have time", "I have a dream", "I have happy"], "a": "I have happy", "why": "상태는 be가 맡는다"},
    {"t": "fill", "q": "She ______ a sister.", "lead": "빈칸을 채우세요", "a": "has", "hint": "have / has"},
    {"t": "order", "words": ["an", "I", "idea", "have"], "q": "단어를 순서대로 놓으세요", "a": "I have an idea."},
    {"t": "order", "words": ["problem", "We", "a", "have"], "q": "단어를 순서대로 놓으세요", "a": "We have a problem."},
    {"t": "analyze", "q": "무엇을 잇고 있나\nI have a sister. 여동생을 '소유'한다는 게 이상하지 않나?", "a": "소유가 아니라 관계다. 나와 여동생이 이어져 있다는 뜻"},
    {"t": "analyze", "q": "왜 만능인가\nhave 하나로 물건·시간·꿈·문제를 다 말할 수 있는 이유는?", "a": "have는 '가진다'가 아니라 '나와 연결한다'는 뜻이기 때문"},
  ] },
  18: { core: "have + 과거분사 = 그 **경험을 지금 갖고 있다**.", qs: [
    {"t": "scene", "ctx": "EP.18, 밤새운 못난이를 보고", "q": "민준: ______ you been here all night?", "opts": ["Have", "Has", "Are", "Do"], "a": "Have", "why": "밤을 새운 경험을 지금 갖고 있냐는 물음."},
    {"t": "choice", "q": "I have been to Seoul의 뜻은?", "opts": ["서울에 있다", "서울에 갈 것이다", "서울에 가본 적이 있다", "서울에 산다"], "a": "서울에 가본 적이 있다"},
    {"t": "fill", "q": "I ______ eaten pizza before.", "lead": "빈칸을 채우세요", "a": "have", "hint": "have"},
    {"t": "order", "words": ["seen", "I", "have", "that movie"], "q": "단어를 순서대로 놓으세요", "a": "I have seen that movie."},
    {"t": "order", "words": ["ever", "you", "Have", "stayed"], "q": "단어를 순서대로 놓으세요", "a": "Have you ever stayed?"},
    {"t": "analyze", "q": "과거형과 무엇이 다른가\n① I went to Seoul. ② I have been to Seoul.", "a": "①은 그때 있었던 일, ②는 그 경험을 지금도 갖고 있다는 것"},
    {"t": "analyze", "q": "왜 have인가\n지나간 일인데 왜 have를 쓸까?", "a": "일은 지나갔지만 경험은 지금 내가 갖고 있기 때문"},
  ] },
  19: { core: "have to는 강요가 아니라 **그 이유를 내가 갖고 있다**는 뜻.", qs: [
    {"t": "scene", "ctx": "EP.19 **[대사 추가 제안]**", "q": "*have to는 지금 EP.18에 들어가 있다. 14과와 자리를 맞바꾸거나, 못난이가 떠나려다 멈추는 이 장면에 한 줄.*\n못난이: I ______ to know why you asked me.", "opts": ["have", "has", "having", "am"], "a": "have", "why": "알아야 할 이유를 내가 갖고 있다. 남이 시킨 게 아니다."},
    {"t": "choice", "q": "I have to go의 진짜 뜻은?", "opts": ["누가 나를 쫓아낸다", "가야 할 이유를 갖고 있다", "가고 싶지 않다", "이미 갔다"], "a": "가야 할 이유를 갖고 있다"},
    {"t": "fill", "q": "She ______ to study tonight.", "lead": "빈칸을 채우세요", "a": "has", "hint": "has"},
    {"t": "order", "words": ["to", "have", "I", "work"], "q": "단어를 순서대로 놓으세요", "a": "I have to work."},
    {"t": "order", "words": ["ask", "You", "to", "have"], "q": "단어를 순서대로 놓으세요", "a": "You have to ask."},
    {"t": "analyze", "q": "어디서 나온 이유인가\nI have to eat. 이 문장에서 먹어야 하는 이유는 어디서 왔나?", "a": "배가 고프다는 내 안의 이유. 밖에서 시킨 게 아니다"},
    {"t": "analyze", "q": "17과와 이어보기\nhave가 '갖고 있다'라면 have to는 무엇을 갖고 있는 걸까?", "a": "해야 할 이유. 물건 대신 이유를 갖고 있는 것"},
  ] },
  20: { core: "have + 명사 = 그 일을 **경험한다**. 밥도 샤워도 회의도 have로 한다.", qs: [
    {"t": "scene", "ctx": "EP.20 **[대사 추가 제안]**", "q": "*EP.20엔 have 표현이 없다. 셋이 넘어지며 웃는 장면 끝에 한 줄 넣으면 딱이다.*\n삼돌이: Okay. Let's ______ a break.", "opts": ["have", "has", "do", "make"], "a": "have", "why": "휴식을 '갖는다'. 영어는 쉬는 것도 경험으로 본다."},
    {"t": "choice", "q": "have와 어울리지 않는 것은?", "opts": ["have dinner", "have a shower", "have a walk", "have a car fast"], "a": "have a car fast"},
    {"t": "fill", "q": "Let's ______ fun.", "lead": "빈칸을 채우세요", "a": "have", "hint": "have"},
    {"t": "order", "words": ["a", "We", "meeting", "have"], "q": "단어를 순서대로 놓으세요", "a": "We have a meeting."},
    {"t": "order", "words": ["a", "had", "I", "good time"], "q": "단어를 순서대로 놓으세요", "a": "I had a good time."},
    {"t": "analyze", "q": "왜 have인가\n저녁을 '먹는' 건데 eat 대신 have dinner라고도 하는 이유는?", "a": "먹는 동작보다 저녁이라는 시간을 통째로 경험한다는 뜻이기 때문"},
    {"t": "analyze", "q": "묶어보기\nhave fun / have a break / have a walk / have a party\n이 넷의 공통점은?", "a": "전부 어떤 시간을 경험한다는 뜻"},
  ] },
  21: { core: "have는 이미 있는 **상태**, get은 갖게 되는 **과정**.", qs: [
    {"t": "scene", "ctx": "EP.21, 삼돌이가 뒤늦게 마음을 전하며", "q": "삼돌이: I mean— I ______ your words.", "opts": ["got", "have", "take", "am"], "a": "got", "why": "없던 것이 들어왔다. have면 원래부터 알았다는 뜻이 된다."},
    {"t": "choice", "q": "get이 나타내는 것은?", "opts": ["머무름", "변화", "사라짐", "반복"], "a": "변화"},
    {"t": "fill", "q": "I ______ hungry at night.", "lead": "빈칸을 채우세요", "a": "get", "hint": "get"},
    {"t": "order", "words": ["angry", "He", "easily", "gets"], "q": "단어를 순서대로 놓으세요", "a": "He gets easily angry."},
    {"t": "order", "words": ["a", "We", "teacher", "new", "got"], "q": "단어를 순서대로 놓으세요", "a": "We got a new teacher."},
    {"t": "analyze", "q": "어제 생긴 사람은\n① I have a bike. ② I got a bike.", "a": "② — get은 없다가 생기는 순간을 말한다"},
    {"t": "analyze", "q": "무엇이 변했나\nI get tired. 여기서 변하는 것은?", "a": "피곤하지 않던 상태가 피곤한 상태로 바뀐다"},
  ] },
  22: { core: "get은 받는 것, take는 **내가 손을 뻗어 가져오는** 것.", qs: [
    {"t": "scene", "ctx": "EP.22, 민준이 혼자 결정한 것을 밝히며", "q": "민준: I ______ the late slot. For the performance.", "opts": ["took", "got", "had", "was"], "a": "took", "why": "주어진 게 아니라 직접 골라서 잡아왔다. 그래서 삼돌이가 화를 낸다."},
    {"t": "choice", "q": "take가 어울리는 문장은?", "opts": ["I take a gift from Santa", "I take a bus every day", "I take tired", "I take happy"], "a": "I take a bus every day"},
    {"t": "fill", "q": "Let's ______ a picture.", "lead": "빈칸을 채우세요", "a": "take", "hint": "take"},
    {"t": "order", "words": ["medicine", "I", "take"], "q": "단어를 순서대로 놓으세요", "a": "I take medicine."},
    {"t": "order", "words": ["a", "She", "walk", "takes"], "q": "단어를 순서대로 놓으세요", "a": "She takes a walk."},
    {"t": "analyze", "q": "누가 움직였나\n① I get a gift. ② I take a book from the shelf.", "a": "①은 상대가 줘서 받은 것, ②는 내가 손을 뻗어 가져온 것"},
    {"t": "analyze", "q": "왜 시간에도 쓰나\nIt takes time. 시간을 어떻게 '가져갈' 수 있을까?", "a": "그 일이 시간을 끌어다 쓴다는 뜻. 가져가는 주체가 사람이 아닐 뿐 뜻은 같다"},
  ] },
  23: { core: "have 상태 · get 과정 · take 행동. 같은 대상도 동사에 따라 내 위치가 바뀐다.", qs: [
    {"t": "scene", "ctx": "EP.23, 셋이 거울 앞에 앉아", "q": "삼돌이: I ______ the moves. You have the words. He has the structure.", "opts": ["got", "take", "am", "do"], "a": "got", "why": "춤은 얻어낸 것, 가사는 갖고 있는 것. 한 문장에 두 동사가 나뉜다."},
    {"t": "choice", "q": "순서가 맞는 것은?", "opts": ["have 과정 / get 상태 / take 행동", "have 상태 / get 과정 / take 행동", "have 행동 / get 상태 / take 과정", "셋 다 같다"], "a": "have 상태 / get 과정 / take 행동"},
    {"t": "fill", "q": "I ______ money in the bank.", "lead": "알맞은 동사를", "a": "have", "hint": "have / get / take"},
    {"t": "order", "words": ["a", "I", "job", "got"], "q": "단어를 순서대로 놓으세요", "a": "I got a job."},
    {"t": "order", "words": ["the", "He", "job", "took"], "q": "단어를 순서대로 놓으세요", "a": "He took the job."},
    {"t": "analyze", "q": "셋을 나란히\nI have money. / I get money. / I take money.\n각각 어떤 상황인가?", "a": "통장에 있다 / 월급날 받는다 / ATM에서 꺼낸다"},
    {"t": "analyze", "q": "마음이 다르다\n같은 일자리인데 have·get·take를 쓰면 말하는 사람의 태도가 어떻게 달라지나?", "a": "have는 편안함, get은 기대, take는 결단"},
  ] },
  24: { core: "소유(have) · 변화(get) · 선택(take). 세 동사가 상황을 나눈다.", qs: [
    {"t": "scene", "ctx": "EP.24, 공연 전날 밤 아무도 집에 안 가고", "q": "못난이: We ______ time. One more run.", "opts": ["have", "has", "get", "take"], "a": "have", "why": "시간을 갖고 있다. 늦었지만 아직 우리 것이다."},
    {"t": "choice", "q": "현재완료를 만드는 동사는?", "opts": ["get", "take", "have", "do"], "a": "have"},
    {"t": "fill", "q": "I ______ to leave early.", "lead": "알맞은 동사로", "a": "had", "hint": "had"},
    {"t": "order", "words": ["been", "I", "have", "to Seoul"], "q": "단어를 순서대로 놓으세요", "a": "I have been to Seoul."},
    {"t": "order", "words": ["break", "Let's", "a", "have"], "q": "단어를 순서대로 놓으세요", "a": "Let's have a break."},
    {"t": "analyze", "q": "have의 네 얼굴\nI have a book / I have been to Seoul / I have to go / I have fun\n네 개가 각각 뭘 갖고 있나?", "a": "물건 / 경험 / 이유 / 시간"},
    {"t": "analyze", "q": "셋을 한 줄로\nhave·get·take를 각각 한 단어로 요약하면?", "a": "have 소유 · get 변화 · take 쟁취"},
  ] },
  25: { core: "to = 도착점이 있는 화살표. 몸이 가고, 물건이 가고, 마음이 간다.", qs: [
    {"t": "scene", "ctx": "EP.25, 삼돌이가 사라진 아침", "q": "못난이: I need ______ find her.", "opts": ["to", "for", "at", "on"], "a": "to", "why": "아직 못 찾았다. 마음만 먼저 화살표를 따라갔다."},
    {"t": "choice", "q": "to의 그림은?", "opts": ["테두리", "한 점", "화살표", "붙어있음"], "a": "화살표"},
    {"t": "fill", "q": "Give this ______ him.", "lead": "빈칸을 채우세요", "a": "to", "hint": "to"},
    {"t": "order", "words": ["to", "I", "school", "go"], "q": "단어를 순서대로 놓으세요", "a": "I go to school."},
    {"t": "order", "words": ["sleep", "to", "I", "need"], "q": "단어를 순서대로 놓으세요", "a": "I need to sleep."},
    {"t": "analyze", "q": "무엇이 가고 있나\n① I go to school. ② I want to eat.", "a": "①은 몸이 가고, ②는 마음이 간다. 화살표는 똑같다"},
    {"t": "analyze", "q": "아직 안 한 일\nI want to eat에서 나는 먹었나 안 먹었나?", "a": "안 먹었다. 마음만 그쪽으로 가 있다"},
  ] },
  26: { core: "-ing는 하던 걸 끊는 것, to는 새 행동으로 넘어가는 것.", qs: [
    {"t": "scene", "ctx": "EP.26, 옥상에서 삼돌이가", "q": "삼돌이: I came up ______ say goodbye.", "opts": ["to", "for", "saying", "at"], "a": "to", "why": "작별하려고 올라왔다. 그런데 아직 안 내려간다."},
    {"t": "choice", "q": "I stopped smoking의 뜻은?", "opts": ["담배를 피우려고 멈췄다", "담배를 끊었다", "담배를 사러 갔다", "멈추고 담배를 폈다"], "a": "담배를 끊었다"},
    {"t": "fill", "q": "I stopped ______ look at the view.", "lead": "빈칸을 채우세요", "a": "to", "hint": "to"},
    {"t": "order", "words": ["pass", "to", "I", "study hard", "the exam"], "q": "단어를 순서대로 놓으세요", "a": "I study hard to pass the exam."},
    {"t": "order", "words": ["be", "I", "to", "a doctor", "grew up"], "q": "단어를 순서대로 놓으세요", "a": "I grew up to be a doctor."},
    {"t": "analyze", "q": "무엇이 달라지나\n① I stopped smoking. ② I stopped to smoke.", "a": "①은 담배를 끊었고, ②는 담배 피우려고 하던 일을 멈췄다"},
    {"t": "analyze", "q": "목적인가 결과인가\nI woke up to find myself famous.\n여기서 to는 '~하려고'인가 '~해보니'인가?", "a": "해보니. 일어나려고 유명해진 게 아니라, 일어나 보니 유명해져 있었다"},
  ] },
  27: { core: "to는 몸의 이동, for는 **마음의 이동**.", qs: [
    {"t": "scene", "ctx": "EP.27, 민준이 마지막 동작을 넘기며", "q": "민준: I know. But it works better ______ you.", "opts": ["for", "to", "at", "in"], "a": "for", "why": "너를 생각해서 바꾼다. 몸이 아니라 마음이 움직였다."},
    {"t": "choice", "q": "for가 나타내는 것은?", "opts": ["범위 안", "누구를 위해서", "한 점", "붙어있음"], "a": "누구를 위해서"},
    {"t": "fill", "q": "Thank you ______ your help.", "lead": "빈칸을 채우세요", "a": "for", "hint": "for"},
    {"t": "order", "words": ["you", "This", "for", "is"], "q": "단어를 순서대로 놓으세요", "a": "This is for you."},
    {"t": "order", "words": ["the exam", "studying", "I'm", "for"], "q": "단어를 순서대로 놓으세요", "a": "I'm studying for the exam."},
    {"t": "analyze", "q": "to와 나란히\n① I go to school. ② I bought this for you.", "a": "①은 내 몸이 학교로, ②는 내 마음이 너에게로"},
    {"t": "analyze", "q": "왜 for인가\nI'm waiting for you. 기다리는 건 가만히 있는 건데 왜 방향을 나타내는 for를 쓸까?", "a": "몸은 멈춰 있어도 마음이 너를 향해 있기 때문"},
  ] },
  28: { core: "in = 어떤 **범위 안**. 공간·시간·상황 모두 테두리가 있다.", qs: [
    {"t": "scene", "ctx": "EP.28, 무대 직전 셋이 손을 포개고", "q": "민준: We're ______ this together.", "opts": ["in", "at", "on", "for"], "a": "in", "why": "같은 테두리 안에 셋이 들어와 있다."},
    {"t": "choice", "q": "in을 쓸 수 없는 것은?", "opts": ["in the box", "in Korea", "in the morning", "in 3 o'clock"], "a": "in 3 o'clock", "why": "정확한 시각은 at"},
    {"t": "fill", "q": "She was born ______ Busan.", "lead": "빈칸을 채우세요", "a": "in", "hint": "in"},
    {"t": "order", "words": ["trouble", "is", "He", "in"], "q": "단어를 순서대로 놓으세요", "a": "He is in trouble."},
    {"t": "order", "words": ["music", "I'm", "in", "interested"], "q": "단어를 순서대로 놓으세요", "a": "I'm interested in music."},
    {"t": "analyze", "q": "어떤 범위인가\n① in the box ② in the morning ③ in trouble", "a": "① 공간 ② 시간 ③ 상황. 전부 테두리 안이다"},
    {"t": "analyze", "q": "왜 나라는 범위인가\nShe was born in Korea. 나라는 왜 점이 아니라 범위일까?", "a": "나라는 넓은 땅이라 그 안 어딘가라는 뜻이 되기 때문"},
  ] },
  29: { core: "at = 넓이가 아니라 **위치 하나, 시각 하나, 대상 하나**를 콕 찍는다.", qs: [
    {"t": "scene", "ctx": "EP.29 **[대사 추가 제안]**", "q": "*EP.29는 대사가 하나도 없는 무대 장면이다. 민준이 삐끗하기 직전에 짧은 한 줄을 넣으면 긴장도 살고 문법도 산다.*\n민준: (속으로) Look ______ the light. Just the light.", "opts": ["at", "in", "on", "to"], "a": "at", "why": "관객 전체가 아니라 조명 한 점에 초점을 맞춘다."},
    {"t": "choice", "q": "at이 어울리는 것은?", "opts": ["at Korea", "at the morning", "at 3 o'clock", "at trouble"], "a": "at 3 o'clock"},
    {"t": "fill", "q": "Let's meet ______ the bus stop.", "lead": "빈칸을 채우세요", "a": "at", "hint": "at"},
    {"t": "order", "words": ["school", "I'm", "at"], "q": "단어를 순서대로 놓으세요", "a": "I'm at school."},
    {"t": "order", "words": ["math", "He's", "at", "good"], "q": "단어를 순서대로 놓으세요", "a": "He's good at math."},
    {"t": "analyze", "q": "in과 무엇이 다른가\n① I'm in Korea. ② I'm at school.", "a": "①은 넓은 범위 안, ②는 콕 찍은 한 지점"},
    {"t": "analyze", "q": "왜 잘하는 것에도 쓰나\nHe's good at math. 실력에 왜 '점'을 뜻하는 at을 쓸까?", "a": "여러 과목 중 수학 하나에 초점이 맞춰져 있기 때문"},
  ] },
  30: { core: "on = 위가 아니라 **접촉**. 물건도, 활동도, 상태도 닿아 있으면 on.", qs: [
    {"t": "scene", "ctx": "EP.30 **[대사 추가 제안]**", "q": "*EP.30은 대사가 한 줄뿐이다. 삼돌이가 민준을 구해내며 던지는 말 앞에 한 줄 붙이면 좋다.*\n삼돌이: You're still ______ the beat. Keep going, idiot.", "opts": ["on", "in", "at", "to"], "a": "on", "why": "박자에서 떨어지지 않았다는 뜻. 붙어 있으라는 말."},
    {"t": "choice", "q": "on이 어울리지 않는 것은?", "opts": ["on the table", "on Monday", "on vacation", "on Korea"], "a": "on Korea"},
    {"t": "fill", "q": "I'm ______ my way home.", "lead": "빈칸을 채우세요", "a": "on", "hint": "on"},
    {"t": "order", "words": ["the", "The book", "table", "is", "on"], "q": "단어를 순서대로 놓으세요", "a": "The book is on the table."},
    {"t": "order", "words": ["the", "I'm", "phone", "on"], "q": "단어를 순서대로 놓으세요", "a": "I'm on the phone."},
    {"t": "analyze", "q": "무엇에 붙어 있나\n① on the table ② on the phone ③ on vacation", "a": "① 책상 면 ② 통화라는 활동 ③ 휴가라는 상태"},
    {"t": "analyze", "q": "왜 위가 아닌가\non the wall은 벽 '위'가 아닌데 왜 on일까?", "a": "위가 아니라 닿아 있다는 뜻이기 때문"},
  ] },
  31: { core: "둘 다 '떨어져 나온다'에서 나왔다. of는 머리로, off는 몸으로.", qs: [
    {"t": "scene", "ctx": "EP.31, 삼돌이가 전학을 안 간다고 밝히며", "q": "민준: ______ the transfer list?\n삼돌이: ______ the list.", "opts": ["Off", "Of", "On", "At"], "a": "Off", "why": "명단에서 몸이 빠져나왔다. 실제로 벗어난 것."},
    {"t": "choice", "q": "of가 어울리는 것은?", "opts": ["take of your shoes", "a piece of cake", "turn of the light", "get of the bus"], "a": "a piece of cake"},
    {"t": "fill", "q": "Turn ______ the light.", "lead": "of 또는 off를 넣으세요", "a": "off"},
    {"t": "order", "words": ["mine", "a", "of", "friend"], "q": "단어를 순서대로 놓으세요", "a": "a friend of mine"},
    {"t": "order", "words": ["the", "Get", "bus", "off"], "q": "단어를 순서대로 놓으세요", "a": "Get off the bus."},
    {"t": "analyze", "q": "머리인가 몸인가\n① the leg of the table ② take off your shoes", "a": "①은 생각 속 관계, ②는 실제로 몸에서 떼어내는 동작"},
    {"t": "analyze", "q": "같은 뿌리\nof와 off가 원래 같은 단어였다면 공통된 뜻은 뭘까?", "a": "떨어져 나온다. 케이크에서 한 조각이 떨어지고, 발에서 신발이 떨어진다"},
  ] },
  32: { core: "전치사는 단어가 아니라 **그림**이다. 일곱 개면 끝난다.", qs: [
    {"t": "scene", "ctx": "EP.32, 편의점 앞 계단에서 셋이", "q": "못난이: We're ______ the same team.\n민준: ______ the same school.\n못난이: ______ the same mess.", "opts": ["on / At / In", "in / On / At", "at / In / On", "to / For / Of"], "a": "on / At / In", "why": "팀에 붙어 있고, 학교라는 점에 있고, 같은 상황 안에 있다. 세 전치사가 한 장면에 다 나온다."},
    {"t": "choice", "q": "그림이 잘못 짝지어진 것은?", "opts": ["to = 화살표", "in = 경계 안", "at = 한 점", "on = 범위 안"], "a": "on = 범위 안", "why": "on은 접촉"},
    {"t": "fill", "q": "The meeting is ______ Monday.", "lead": "알맞은 전치사를", "a": "on", "hint": "in / at / on"},
    {"t": "order", "words": ["us", "is", "This", "for"], "q": "단어를 순서대로 놓으세요", "a": "This is for us."},
    {"t": "order", "words": ["stage", "a", "We", "want", "bigger"], "q": "단어를 순서대로 놓으세요", "a": "We want a bigger stage."},
    {"t": "analyze", "q": "그림으로 나누기\nto / for / in / at / on / of / off\n일곱 개를 한 단어씩 그림으로 말해보세요.", "a": "화살표 / 마음의 방향 / 테두리 안 / 한 점 / 접촉 / 추상 관계 / 물리적 이탈"},
    {"t": "analyze", "q": "같은 자리, 다른 전치사\nin the same mess / at the same school / on the same team\n셋 다 '같은'인데 왜 전치사가 다를까?", "a": "상황은 테두리 안, 학교는 한 점, 팀은 붙어 있는 것이라서"},
  ] },
};
