// 연습문제 — 과당 7문제
// t: scene 장면(4지선다) · choice 고르기(4지선다) · order 순서 맞추기

const quizData = {
  1: { core: "영어는 주어 → 동사 → 목적어 순서. 순서가 바뀌면 뜻이 바뀐다.", qs: [
    {"t": "scene", "ctx": "EP.1, 민준이 못난이 노트를 보고", "q": "민준: I ______ you.", "opts": ["need", "needs", "needing", "to need"], "a": "need", "why": "주어 I 다음 바로 동사. 이 세 단어가 오늘 배울 전부다."},
    {"t": "choice", "q": "다음 중 영어 순서로 맞는 것은?", "opts": ["I pizza eat", "I eat pizza", "Eat I pizza", "Pizza I eat"], "a": "I eat pizza"},
    {"t": "choice", "q": "She music likes가 틀린 이유는?", "opts": ["동사가 빠져서", "목적어가 동사보다 앞에 있어서", "주어가 없어서", "단어가 모자라서"], "a": "목적어가 동사보다 앞에 있어서"},
    {"t": "choice", "q": "'그녀는 음악을 좋아한다'를 영어 순서로 하면?", "opts": ["She music loves", "She loves music", "Loves she music", "Music she loves"], "a": "She loves music"},
    {"t": "choice", "q": "다음 중 주어·동사·목적어가 모두 있는 문장은?", "opts": ["I sleep", "Birds fly", "We study English", "It rains"], "a": "We study English", "why": "sleep, fly, rain은 목적어가 필요 없는 동사다."},
    {"t": "order", "words": ["soccer", "They", "play"], "q": "단어를 순서대로 놓으세요", "a": "They play soccer."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["pictures", "draws", "My sister"], "a": "My sister draws pictures."},
  ] },
  2: { core: "문장 맨 앞은 언제나 주어 + 동사. 뒤에 뭐가 붙어도 안 변한다.", qs: [
    {"t": "scene", "ctx": "EP.2, 삼돌이가 민준을 밀어내며", "q": "삼돌이: I ______ do groups.", "opts": ["don't", "not", "no", "doesn't"], "a": "don't", "why": "주어 I 다음 바로 동사 자리. 거절도 순서를 지킨다."},
    {"t": "choice", "q": "The boy eats apples every day에서 동사는?", "opts": ["The boy", "eats", "apples", "every day"], "a": "eats"},
    {"t": "choice", "q": "주어와 동사가 바르게 짝지어진 것은?", "opts": ["My friend / in Seoul", "My friend / lives", "lives / in Seoul", "Seoul / lives"], "a": "My friend / lives"},
    {"t": "choice", "q": "`Dogs run fast`에서 주어는?", "opts": ["Dogs", "run", "fast", "run fast"], "a": "Dogs"},
    {"t": "choice", "q": "영어 문장에서 주어와 동사는 어디에 있나?", "opts": ["맨 뒤", "가운데", "맨 앞", "정해져 있지 않다"], "a": "맨 앞"},
    {"t": "order", "words": ["every", "eats", "day", "The boy", "apples"], "q": "단어를 순서대로 놓으세요", "a": "The boy eats apples every day."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["early", "sleeps", "She"], "a": "She sleeps early."},
  ] },
  3: { core: "주어 + 동사 + 목적어. 아는 단어를 그 자리에 놓으면 끝.", qs: [
    {"t": "scene", "ctx": "EP.3, 민준이 노트를 다 읽었다고 말하며", "q": "민준: I ______ it. All of it.", "opts": ["read", "reading", "reads", "to read"], "a": "read", "why": "I(주어) read(동사) it(목적어). 세 칸이 다 찼다."},
    {"t": "choice", "q": "'나는 마라탕을 먹는다'를 영어 순서로 하면?", "opts": ["I malatang eat", "Eat malatang I", "I eat malatang", "Malatang I eat"], "a": "I eat malatang"},
    {"t": "choice", "q": "목적어가 있는 문장은?", "opts": ["She sleeps", "Birds fly", "We study English", "It rains"], "a": "We study English"},
    {"t": "choice", "q": "`She likes pizza`에서 목적어는?", "opts": ["She", "likes", "pizza", "likes pizza"], "a": "pizza"},
    {"t": "choice", "q": "`I love you`와 `You love me`는 무엇이 다른가?", "opts": ["단어가 다르다", "길이가 다르다", "순서가 달라서 사랑하는 사람이 바뀐다", "뜻이 같다"], "a": "순서가 달라서 사랑하는 사람이 바뀐다"},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["soccer", "play", "They"], "a": "They play soccer."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["pizza", "eat", "I"], "a": "I eat pizza."},
  ] },
  4: { core: "주어가 아무리 길어도 **첫 번째 동사** 앞까지가 전부 주어.", qs: [
    {"t": "scene", "ctx": "EP.4", "q": "삼돌이: The person who wrote this ______ brave.", "opts": ["is", "are", "be", "being"], "a": "is", "why": "The person who wrote this 전체가 주어. 첫 동사는 is."},
    {"t": "choice", "q": "The man with a red hat is happy에서 주어는?", "opts": ["The man", "The man with a red hat", "a red hat", "is happy"], "a": "The man with a red hat"},
    {"t": "choice", "q": "긴 주어를 찾는 방법은?", "opts": ["가장 긴 단어를 찾는다", "첫 번째 동사를 찾는다", "맨 앞 세 단어를 본다", "물음표를 찾는다"], "a": "첫 번째 동사를 찾는다"},
    {"t": "choice", "q": "`The girls in my class ______ kind.` 빈칸은?", "opts": ["is", "are", "am", "be"], "a": "are", "why": "주어가 The girls in my class 전체. 여러 명이라 are."},
    {"t": "choice", "q": "`The man with a red hat wearing blue jeans is happy`에서 주어는 어디까지인가?", "opts": ["The man", "The man with a red hat", "The man with a red hat wearing blue jeans", "is happy"], "a": "The man with a red hat wearing blue jeans", "why": "wearing은 동사가 아니라 명사를 꾸미는 말이다. 진짜 첫 번째 동사는 마지막 is. 그 앞까지가 전부 주어다."},
    {"t": "order", "words": ["is", "The cat", "on the sofa", "sleeping"], "q": "단어를 순서대로 놓으세요", "a": "The cat on the sofa is sleeping."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["in Busan", "lives", "The boy who sits next to me"], "a": "The boy who sits next to me lives in Busan."},
  ] },
  5: { core: "a는 특정한 하나, -s는 종류 전체. 둘 다 없으면 틀린 문장.", qs: [
    {"t": "scene", "ctx": "EP.5, 삼돌이가 조건을 거는 장면", "q": "삼돌이: ...______ week.", "opts": ["One", "Ones", "A weeks", "Week"], "a": "One", "why": "딱 한 주. 숫자를 밝혔기 때문에 약속이 된다."},
    {"t": "choice", "q": "I like a dog의 뜻은?", "opts": ["개를 다 좋아해", "특정한 개 한 마리를 좋아해", "개가 싫어", "개를 키운다"], "a": "특정한 개 한 마리를 좋아해"},
    {"t": "choice", "q": "틀린 문장은?", "opts": ["I have a dog", "I have dogs", "I have dog", "I have two dogs"], "a": "I have dog", "why": "숫자를 안 밝혔다"},
    {"t": "choice", "q": "'나는 사과 한 개가 있어'를 영어로 하면?", "opts": ["I have apple", "I have an apple", "I have apples", "I have the apples"], "a": "I have an apple"},
    {"t": "choice", "q": "`She likes a cat`과 `She likes cats`의 차이는?", "opts": ["뜻이 같다", "앞은 특정한 한 마리, 뒤는 고양이 전체", "앞이 더 정중하다", "뒤가 틀린 문장이다"], "a": "앞은 특정한 한 마리, 뒤는 고양이 전체"},
    {"t": "order", "words": ["a", "bought", "I", "car"], "q": "단어를 순서대로 놓으세요", "a": "I bought a car."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["dogs", "like", "I"], "a": "I like dogs."},
  ] },
  6: { core: "한 개면 단수, 여러 개면 복수. 영어는 반드시 밝힌다.", qs: [
    {"t": "scene", "ctx": "EP.6, 삼돌이가 전학을 통보하며", "q": "삼돌이: I transfer next ______.", "opts": ["month", "months", "a months", "monthes"], "a": "month", "why": "다음 달 하나. 여러 달이면 뜻이 달라진다."},
    {"t": "choice", "q": "There ______ apples. 빈칸은?", "opts": ["is", "are", "am", "be"], "a": "are"},
    {"t": "choice", "q": "복수형이 특별한 단어는?", "opts": ["book → books", "car → cars", "person → people", "dog → dogs"], "a": "person → people"},
    {"t": "choice", "q": "`There ______ an apple on the table.` 빈칸은?", "opts": ["is", "are", "am", "be"], "a": "is"},
    {"t": "choice", "q": "영어로 `There is apple`이 안 되는 이유는?", "opts": ["동사가 틀려서", "숫자를 안 밝혀서", "단어가 어려워서", "순서가 틀려서"], "a": "숫자를 안 밝혀서"},
    {"t": "order", "words": ["are", "There", "three", "cats"], "q": "단어를 순서대로 놓으세요", "a": "There are three cats."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["books", "have", "I"], "a": "I have books."},
  ] },
  7: { core: "셀 수 없는 명사엔 a도 s도 안 붙는다. 단, 잔·달러를 빌리면 셀 수 있다.", qs: [
    {"t": "scene", "ctx": "EP.7, 밤새 연습한 민준이", "q": "민준: I lost ______.", "opts": ["count", "a count", "counts", "the counts"], "a": "count", "why": "셀 수 없을 만큼 했다는 뜻. 그래서 a도 s도 안 붙는다."},
    {"t": "choice", "q": "셀 수 없는 명사는?", "opts": ["apple", "book", "water", "car"], "a": "water"},
    {"t": "choice", "q": "a glass of water가 뜻하는 것은?", "opts": ["물 전체", "물 한 잔", "유리컵", "물이 없음"], "a": "물 한 잔"},
    {"t": "choice", "q": "`I need ______ money.` 빈칸에 들어갈 것은?", "opts": ["a", "an", "아무것도 안 씀", "the a"], "a": "아무것도 안 씀", "why": "money는 셀 수 없어서 a가 안 붙는다."},
    {"t": "choice", "q": "`two dollars`는 되는데 `two moneys`는 왜 안 될까?", "opts": ["dollar가 더 짧아서", "달러는 단위라서 셀 수 있고 money는 못 세서", "둘 다 된다", "money가 외래어라서"], "a": "달러는 단위라서 셀 수 있고 money는 못 세서"},
    {"t": "order", "words": ["of", "two", "water", "glasses"], "q": "단어를 순서대로 놓으세요", "a": "two glasses of water"},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["water", "need", "I"], "a": "I need water."},
  ] },
  8: { core: "단수 주어 → 동사에 s. 복수 주어 → 동사에 s 없음.", qs: [
    {"t": "scene", "ctx": "EP.8, 못난이가 삼돌이 집 앞에서 쏟아내며", "q": "못난이: She ______. She hides. She disappears.", "opts": ["run", "runs", "running", "ran"], "a": "runs", "why": "주어 She가 단수라서 동사마다 s가 붙는다. 세 번 다."},
    {"t": "choice", "q": "맞는 문장은?", "opts": ["He like pizza", "He likes pizza", "They likes pizza", "He liking pizza"], "a": "He likes pizza"},
    {"t": "choice", "q": "They ______ hard. 빈칸은?", "opts": ["works", "work", "working", "to work"], "a": "work"},
    {"t": "choice", "q": "`She ______ English every day.` 빈칸은?", "opts": ["study", "studies", "studying", "studied"], "a": "studies"},
    {"t": "choice", "q": "주어가 단수인데 왜 동사에 s가 붙을까?", "opts": ["동사가 더 중요해서", "명사에 s가 없으니 동사가 대신 받아서", "발음이 편해서", "규칙이 없어서"], "a": "명사에 s가 없으니 동사가 대신 받아서"},
    {"t": "order", "words": ["pizza", "likes", "My brother"], "q": "단어를 순서대로 놓으세요", "a": "My brother likes pizza."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a book", "has", "He"], "a": "He has a book."},
  ] },
  9: { core: "be 동사는 뜻이 없다. 주어와 상태를 등호처럼 잇기만 한다.", qs: [
    {"t": "scene", "ctx": "EP.9, 돌아온 삼돌이를 보고", "q": "못난이: You'______ here.", "opts": ["re", "s", "m", "ve"], "a": "re", "why": "You are here의 줄임. are는 뜻이 없다. You와 here를 잇기만 한다."},
    {"t": "choice", "q": "be 동사가 하는 일은?", "opts": ["달린다", "연결한다", "먹는다", "사랑한다"], "a": "연결한다"},
    {"t": "choice", "q": "`I ______ happy.` 빈칸은?", "opts": ["am", "is", "are", "be"], "a": "am"},
    {"t": "choice", "q": "be 동사에 뜻이 없는 게 왜 좋을까?", "opts": ["짧아서", "외우기 쉬워서", "뜻이 없으니 어떤 상태든 담을 수 있어서", "발음이 쉬워서"], "a": "뜻이 없으니 어떤 상태든 담을 수 있어서", "why": "빈 컵에 물도 커피도 담기는 것과 같다."},
    {"t": "order", "words": ["smart", "You", "are"], "q": "단어를 순서대로 놓으세요", "a": "You are smart."},
    {"t": "order", "words": ["a", "is", "He", "teacher"], "q": "단어를 순서대로 놓으세요", "a": "He is a teacher."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["tall", "is", "She"], "a": "She is tall."},
  ] },
  10: { core: "행동은 일반 동사, 상태는 be 동사. be가 보이면 상태 이야기다.", qs: [
    {"t": "scene", "ctx": "EP.10, 무너진 민준이 애써 버티며", "q": "민준: I ______ fine.", "opts": ["am", "do", "have", "know"], "a": "am", "why": "괜찮다는 건 행동이 아니라 상태다. 그런데 손은 떨리고 있다."},
    {"t": "choice", "q": "상태를 말하는 문장은?", "opts": ["She runs", "She eats", "She is tired", "She sings"], "a": "She is tired"},
    {"t": "choice", "q": "`They ______ kind.` 빈칸은?", "opts": ["am", "is", "are", "be"], "a": "are"},
    {"t": "choice", "q": "`I run every day`와 `I am tired`는 무엇이 다른가?", "opts": ["앞은 행동, 뒤는 상태", "앞은 과거, 뒤는 현재", "뜻이 같다", "뒤가 틀린 문장이다"], "a": "앞은 행동, 뒤는 상태"},
    {"t": "order", "words": ["tired", "am", "I"], "q": "단어를 순서대로 놓으세요", "a": "I am tired."},
    {"t": "order", "words": ["is", "The room", "clean"], "q": "단어를 순서대로 놓으세요", "a": "The room is clean."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a teacher", "is", "He"], "a": "He is a teacher."},
  ] },
  11: { core: "I는 am, You는 are, 나머지는 is. 주어를 먼저 보고 고른다.", qs: [
    {"t": "scene", "ctx": "EP.11, 웃음을 참지 못하면서", "q": "삼돌이: I ______ not laughing.", "opts": ["am", "is", "are", "be"], "a": "am", "why": "주어가 I니까 am. 어깨는 들썩이는데 말은 아니라고 한다."},
    {"t": "choice", "q": "He ______ smart. 빈칸은?", "opts": ["am", "is", "are", "be"], "a": "is"},
    {"t": "choice", "q": "`You ______ my friend.` 빈칸은?", "opts": ["am", "is", "are", "be"], "a": "are"},
    {"t": "choice", "q": "한국어는 '나는/너는/그는 행복하다'로 같은데 영어는 왜 다를까?", "opts": ["영어가 어려워서", "주어마다 자기 be 동사를 따로 주기 때문", "발음 때문에", "규칙이 없어서"], "a": "주어마다 자기 be 동사를 따로 주기 때문"},
    {"t": "order", "words": ["happy", "I", "am"], "q": "단어를 순서대로 놓으세요", "a": "I am happy."},
    {"t": "order", "words": ["are", "You", "late"], "q": "단어를 순서대로 놓으세요", "a": "You are late."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["ready", "are", "We"], "a": "We are ready."},
  ] },
  12: { core: "be + 동사ing = 지금 그 행동을 하고 있는 **상태**.", qs: [
    {"t": "scene", "ctx": "EP.12, 지우려는 민준을 막고", "q": "못난이: I'm still ______.", "opts": ["decide", "deciding", "decided", "to decide"], "a": "deciding", "why": "아직 정하는 중이라는 상태. 답을 미룬 게 아니라 진행 중이다."},
    {"t": "choice", "q": "진행형 문장은?", "opts": ["I eat lunch", "I am eating lunch", "I ate lunch", "I will eat lunch"], "a": "I am eating lunch"},
    {"t": "choice", "q": "`She is ______.` 뛰고 있다는 뜻이 되려면?", "opts": ["run", "runs", "running", "ran"], "a": "running"},
    {"t": "choice", "q": "먹는 건 행동인데 `I am eating`에는 왜 be가 있을까?", "opts": ["실수다", "be가 행동을 상태로 바꿔서", "발음 때문에", "eating이 명사라서"], "a": "be가 행동을 상태로 바꿔서", "why": "움직이는 걸 사진처럼 멈춰 세운 것이다."},
    {"t": "order", "words": ["studying", "are", "We"], "q": "단어를 순서대로 놓으세요", "a": "We are studying."},
    {"t": "order", "words": ["is", "The baby", "crying"], "q": "단어를 순서대로 놓으세요", "a": "The baby is crying."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["sleeping", "is", "He"], "a": "He is sleeping."},
  ] },
  13: { core: "누가 했는지보다 지금 어떤 **결과**인지를 말한다.", qs: [
    {"t": "scene", "ctx": "EP.13", "q": "삼돌이: My part ______ changed. Without asking.", "opts": ["is", "am", "are", "do"], "a": "is", "why": "누가 바꿨는지는 이미 안다. 바뀌어 있다는 결과가 중요하다."},
    {"t": "choice", "q": "수동태 문장은?", "opts": ["I broke it", "It is broken", "I break it", "Break it"], "a": "It is broken"},
    {"t": "choice", "q": "`The door ______ closed.` 빈칸은?", "opts": ["is", "am", "are", "do"], "a": "is"},
    {"t": "choice", "q": "`It is broken`에서 부순 사람을 왜 말하지 않을까?", "opts": ["몰라서", "지금 부러진 상태가 중요해서", "말하면 실례라서", "문법상 못 써서"], "a": "지금 부러진 상태가 중요해서"},
    {"t": "order", "words": ["cooked", "The food", "is"], "q": "단어를 순서대로 놓으세요", "a": "The food is cooked."},
    {"t": "order", "words": ["is", "window", "The", "broken"], "q": "단어를 순서대로 놓으세요", "a": "The window is broken."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["finished", "is", "The work"], "a": "The work is finished."},
  ] },
  14: { core: "be going to = 지금 그 방향으로 가고 있다. 그래서 곧 한다.", qs: [
    {"t": "scene", "ctx": "EP.14", "q": "민준: We ______ going to run it again.", "opts": ["are", "is", "am", "be"], "a": "are", "why": "아직 시작 안 했지만 이미 그쪽으로 가고 있다."},
    {"t": "choice", "q": "I am going to study의 진짜 뜻은?", "opts": ["공부했다", "공부하러 가고 있다", "공부하기 싫다", "공부를 끝냈다"], "a": "공부하러 가고 있다"},
    {"t": "choice", "q": "`She is ______ to leave.` 빈칸은?", "opts": ["go", "goes", "going", "went"], "a": "going"},
    {"t": "choice", "q": "`I will study`와 `I am going to study`의 차이는?", "opts": ["뜻이 같다", "앞은 지금 막 정한 것, 뒤는 이미 그 방향으로 가는 중", "앞이 더 먼 미래", "뒤가 틀린 문장"], "a": "앞은 지금 막 정한 것, 뒤는 이미 그 방향으로 가는 중"},
    {"t": "order", "words": ["to", "going", "I", "sleep", "am"], "q": "단어를 순서대로 놓으세요", "a": "I am going to sleep."},
    {"t": "order", "words": ["are", "They", "to", "going", "win"], "q": "단어를 순서대로 놓으세요", "a": "They are going to win."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["eat", "to", "going", "are", "We"], "a": "We are going to eat."},
  ] },
  15: { core: "was/were는 시간 표시가 아니라 \"지금은 다르다\"는 선언.", qs: [
    {"t": "scene", "ctx": "EP.15, 민준이 삼돌이에게 인정하며", "q": "민준: You ______ right.", "opts": ["were", "was", "are", "am"], "a": "were", "why": "주어가 You라서 were. 그때 네 말이 맞았다는 뒤늦은 인정."},
    {"t": "choice", "q": "I was happy가 품고 있는 뜻은?", "opts": ["지금도 행복하다", "지금은 다르다", "앞으로 행복할 것이다", "한 번도 행복한 적 없다"], "a": "지금은 다르다"},
    {"t": "choice", "q": "`She ______ a student.` 그때는 학생이었다는 뜻이 되려면?", "opts": ["is", "was", "are", "were"], "a": "was"},
    {"t": "choice", "q": "`She was a student`가 말하지 않고도 알려주는 것은?", "opts": ["학교 이름", "지금은 학생이 아니라는 것", "성적", "나이"], "a": "지금은 학생이 아니라는 것"},
    {"t": "order", "words": ["tired", "He", "was"], "q": "단어를 순서대로 놓으세요", "a": "He was tired."},
    {"t": "order", "words": ["were", "They", "here"], "q": "단어를 순서대로 놓으세요", "a": "They were here."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["fine", "were", "yesterday", "We"], "a": "We were fine yesterday."},
  ] },
  16: { core: "상태·진행·수동·미래·과거. 전부 be 동사 하나에서 나온다.", qs: [
    {"t": "scene", "ctx": "EP.16", "q": "민준: So the notebook ______ your voice.", "opts": ["is", "has", "does", "do"], "a": "is", "why": "노트가 곧 네 목소리다. 등호 하나로 두 개를 이었다."},
    {"t": "choice", "q": "be동사가 아니라 일반동사에만 있는 것은?", "opts": ["진행형", "수동태", "3인칭 단수 -s", "미래"], "a": "3인칭 단수 -s", "why": "he goes처럼 3인칭 단수 뒤에 -s 붙이는 건 일반동사만 한다. be동사는 원래부터 is로 바뀌어서 -s를 따로 안 붙인다."},
    {"t": "choice", "q": "`I ______ scared before the show.` 빈칸은?", "opts": ["am", "was", "are", "were"], "a": "was"},
    {"t": "choice", "q": "`I am happy` `I am eating` `It is broken` `I was happy`가 다 말하는 것은?", "opts": ["행동", "지금(또는 그때) 어떤 상태인가", "시간", "장소"], "a": "지금(또는 그때) 어떤 상태인가"},
    {"t": "order", "words": ["going", "am", "I", "to", "try"], "q": "단어를 순서대로 놓으세요", "a": "I am going to try."},
    {"t": "order", "words": ["is", "door", "The", "locked"], "q": "단어를 순서대로 놓으세요", "a": "The door is locked."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["for us", "waiting", "are", "They"], "a": "They are waiting for us."},
  ] },
  17: { core: "have는 소유가 아니라 **관계**. 물건·시간·생각·경험을 나와 잇는다.", qs: [
    {"t": "scene", "ctx": "EP.17", "q": "삼돌이: I ______ a reason. I just never say it.", "opts": ["have", "has", "having", "am"], "a": "have", "why": "이유를 갖고 있다. 물건이 아닌 것도 have로 잇는다."},
    {"t": "choice", "q": "have를 쓸 수 없는 것은?", "opts": ["I have a car", "I have time", "I have a dream", "I have happy"], "a": "I have happy", "why": "상태는 be가 맡는다"},
    {"t": "choice", "q": "`She ______ a sister.` 빈칸은?", "opts": ["have", "has", "having", "is"], "a": "has"},
    {"t": "order", "words": ["an", "I", "idea", "have"], "q": "단어를 순서대로 놓으세요", "a": "I have an idea."},
    {"t": "order", "words": ["problem", "We", "a", "have"], "q": "단어를 순서대로 놓으세요", "a": "We have a problem."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a sister", "has", "She"], "a": "She has a sister."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a dream", "have", "I"], "a": "I have a dream."},
  ] },
  18: { core: "have + 과거분사 = 그 **경험을 지금 갖고 있다**.", qs: [
    {"t": "scene", "ctx": "EP.18, 밤새운 못난이를 보고", "q": "민준: ______ you been here all night?", "opts": ["Have", "Has", "Are", "Do"], "a": "Have", "why": "밤을 새운 경험을 지금 갖고 있냐는 물음."},
    {"t": "choice", "q": "I have been to Seoul의 뜻은?", "opts": ["서울에 있다", "서울에 갈 것이다", "서울에 가본 적이 있다", "서울에 산다"], "a": "서울에 가본 적이 있다"},
    {"t": "choice", "q": "`I ______ eaten pizza before.` 빈칸은?", "opts": ["have", "has", "am", "was"], "a": "have"},
    {"t": "order", "words": ["seen", "I", "have", "that movie"], "q": "단어를 순서대로 놓으세요", "a": "I have seen that movie."},
    {"t": "order", "words": ["ever", "you", "Have", "stayed"], "q": "단어를 순서대로 놓으세요", "a": "Have you ever stayed?"},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["to Seoul", "been", "have", "I"], "a": "I have been to Seoul."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["in Busan", "lived", "have", "I"], "a": "I have lived in Busan."},
  ] },
  19: { core: "have to는 강요가 아니라 **그 이유를 내가 갖고 있다**는 뜻.", qs: [
    {"t": "scene", "ctx": "EP.19", "q": "못난이: I ______ to know why you asked me.", "opts": ["have", "has", "having", "am"], "a": "have", "why": "알아야 할 이유를 내가 갖고 있다. 남이 시킨 게 아니다."},
    {"t": "choice", "q": "I have to go의 진짜 뜻은?", "opts": ["누가 나를 쫓아낸다", "가야 할 이유를 갖고 있다", "가고 싶지 않다", "이미 갔다"], "a": "가야 할 이유를 갖고 있다"},
    {"t": "choice", "q": "`She ______ to study tonight.` 빈칸은?", "opts": ["have", "has", "having", "is"], "a": "has"},
    {"t": "order", "words": ["to", "have", "I", "work"], "q": "단어를 순서대로 놓으세요", "a": "I have to work."},
    {"t": "order", "words": ["ask", "You", "to", "have"], "q": "단어를 순서대로 놓으세요", "a": "You have to ask."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["sleep", "to", "have", "I"], "a": "I have to sleep."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["mom", "call", "to", "have", "I"], "a": "I have to call mom."},
  ] },
  20: { core: "have + 명사 = 그 일을 **경험한다**. 밥도 샤워도 회의도 have로 한다.", qs: [
    {"t": "scene", "ctx": "EP.20", "q": "삼돌이: Okay. Let's ______ a break.", "opts": ["have", "has", "do", "make"], "a": "have", "why": "휴식을 '갖는다'. 영어는 쉬는 것도 경험으로 본다."},
    {"t": "choice", "q": "have와 어울리지 않는 것은?", "opts": ["have dinner", "have a shower", "have a walk", "have a car fast"], "a": "have a car fast"},
    {"t": "choice", "q": "`Let's ______ fun.` 빈칸은?", "opts": ["have", "has", "do", "make"], "a": "have"},
    {"t": "order", "words": ["a", "We", "meeting", "have"], "q": "단어를 순서대로 놓으세요", "a": "We have a meeting."},
    {"t": "order", "words": ["a", "had", "I", "good time"], "q": "단어를 순서대로 놓으세요", "a": "I had a good time."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a walk", "have", "Let's"], "a": "Let's have a walk."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["dinner", "have", "We"], "a": "We have dinner."},
  ] },
  21: { core: "have는 이미 있는 **상태**, get은 갖게 되는 **과정**.", qs: [
    {"t": "scene", "ctx": "EP.21, 삼돌이가 뒤늦게 마음을 전하며", "q": "삼돌이: I mean— I ______ your words.", "opts": ["got", "have", "take", "am"], "a": "got", "why": "없던 것이 들어왔다. have면 원래부터 알았다는 뜻이 된다."},
    {"t": "choice", "q": "get이 나타내는 것은?", "opts": ["머무름", "변화", "사라짐", "반복"], "a": "변화"},
    {"t": "choice", "q": "`I ______ hungry at night.` 빈칸은?", "opts": ["get", "have", "take", "am"], "a": "get", "why": "배고프지 않던 상태가 배고픈 상태로 바뀐다."},
    {"t": "order", "words": ["angry", "He", "easily", "gets"], "q": "단어를 순서대로 놓으세요", "a": "He gets angry easily."},
    {"t": "order", "words": ["a", "We", "teacher", "new", "got"], "q": "단어를 순서대로 놓으세요", "a": "We got a new teacher."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["tired", "get", "I"], "a": "I get tired."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["money", "got", "I"], "a": "I got money."},
  ] },
  22: { core: "get은 받는 것, take는 **내가 손을 뻗어 가져오는** 것.", qs: [
    {"t": "scene", "ctx": "EP.22, 민준이 혼자 결정한 것을 밝히며", "q": "민준: I ______ the late slot. For the performance.", "opts": ["took", "got", "had", "was"], "a": "took", "why": "주어진 게 아니라 직접 골라서 잡아왔다. 그래서 삼돌이가 화를 낸다."},
    {"t": "choice", "q": "take가 어울리는 문장은?", "opts": ["I take a gift from Santa", "I take a bus every day", "I take tired", "I take happy"], "a": "I take a bus every day"},
    {"t": "choice", "q": "`Let's ______ a picture.` 빈칸은?", "opts": ["take", "get", "have", "make"], "a": "take"},
    {"t": "order", "words": ["medicine", "I", "take"], "q": "단어를 순서대로 놓으세요", "a": "I take medicine."},
    {"t": "order", "words": ["a", "She", "walk", "takes"], "q": "단어를 순서대로 놓으세요", "a": "She takes a walk."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a shower", "take", "I"], "a": "I take a shower."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a bus", "take", "I"], "a": "I take a bus."},
  ] },
  23: { core: "have 상태 · get 과정 · take 행동. 같은 대상도 동사에 따라 내 위치가 바뀐다.", qs: [
    {"t": "scene", "ctx": "EP.23, 셋이 거울 앞에 앉아", "q": "삼돌이: I ______ the moves. You have the words. He has the structure.", "opts": ["got", "take", "am", "do"], "a": "got", "why": "춤은 얻어낸 것, 가사는 갖고 있는 것. 한 문장에 두 동사가 나뉜다."},
    {"t": "choice", "q": "순서가 맞는 것은?", "opts": ["have 과정 / get 상태 / take 행동", "have 상태 / get 과정 / take 행동", "have 행동 / get 상태 / take 과정", "셋 다 같다"], "a": "have 상태 / get 과정 / take 행동"},
    {"t": "choice", "q": "`I ______ money in the bank.` 통장에 있다는 뜻이면?", "opts": ["have", "get", "take", "am"], "a": "have"},
    {"t": "order", "words": ["a", "I", "job", "got"], "q": "단어를 순서대로 놓으세요", "a": "I got a job."},
    {"t": "order", "words": ["the", "He", "job", "took"], "q": "단어를 순서대로 놓으세요", "a": "He took the job."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["money", "get", "I"], "a": "I get money."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["medicine", "take", "I"], "a": "I take medicine."},
  ] },
  24: { core: "소유(have) · 변화(get) · 선택(take). 세 동사가 상황을 나눈다.", qs: [
    {"t": "scene", "ctx": "EP.24, 공연 전날 밤 아무도 집에 안 가고", "q": "못난이: We ______ time. One more run.", "opts": ["have", "has", "get", "take"], "a": "have", "why": "시간을 갖고 있다. 늦었지만 아직 우리 것이다."},
    {"t": "choice", "q": "현재완료를 만드는 동사는?", "opts": ["get", "take", "have", "do"], "a": "have"},
    {"t": "choice", "q": "`I ______ to leave early.` 그래야 할 이유가 있었다는 뜻이면?", "opts": ["have", "had", "has", "having"], "a": "had"},
    {"t": "order", "words": ["been", "I", "have", "to Seoul"], "q": "단어를 순서대로 놓으세요", "a": "I have been to Seoul."},
    {"t": "order", "words": ["break", "Let's", "a", "have"], "q": "단어를 순서대로 놓으세요", "a": "Let's have a break."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["fun", "have", "I"], "a": "I have fun."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a car", "have", "I"], "a": "I have a car."},
  ] },
  25: { core: "to = 도착점이 있는 화살표. 몸이 가고, 물건이 가고, 마음이 간다.", qs: [
    {"t": "scene", "ctx": "EP.25, 삼돌이가 사라진 아침", "q": "못난이: I need ______ find her.", "opts": ["to", "for", "at", "on"], "a": "to", "why": "아직 못 찾았다. 마음만 먼저 화살표를 따라갔다."},
    {"t": "choice", "q": "to의 그림은?", "opts": ["테두리", "한 점", "화살표", "붙어있음"], "a": "화살표"},
    {"t": "choice", "q": "`Give this ______ him.` 빈칸은?", "opts": ["to", "for", "at", "on"], "a": "to"},
    {"t": "order", "words": ["to", "I", "school", "go"], "q": "단어를 순서대로 놓으세요", "a": "I go to school."},
    {"t": "order", "words": ["sleep", "to", "I", "need"], "q": "단어를 순서대로 놓으세요", "a": "I need to sleep."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["her", "to", "hello", "said", "I"], "a": "I said hello to her."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["me", "to", "Come"], "a": "Come to me."},
  ] },
  26: { core: "-ing는 하던 걸 끊는 것, to는 새 행동으로 넘어가는 것.", qs: [
    {"t": "scene", "ctx": "EP.26, 옥상에서 삼돌이가", "q": "삼돌이: I came up ______ say goodbye.", "opts": ["to", "for", "saying", "at"], "a": "to", "why": "작별하려고 올라왔다. 그런데 아직 안 내려간다."},
    {"t": "choice", "q": "I stopped smoking의 뜻은?", "opts": ["담배를 피우려고 멈췄다", "담배를 끊었다", "담배를 사러 갔다", "멈추고 담배를 폈다"], "a": "담배를 끊었다"},
    {"t": "choice", "q": "`I stopped ______ look at the view.` 보려고 멈췄다는 뜻이면?", "opts": ["to", "for", "looking", "at"], "a": "to"},
    {"t": "order", "words": ["pass", "to", "I", "study hard", "the exam"], "q": "단어를 순서대로 놓으세요", "a": "I study hard to pass the exam."},
    {"t": "order", "words": ["be", "I", "to", "a doctor", "grew up"], "q": "단어를 순서대로 놓으세요", "a": "I grew up to be a doctor."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["smoking", "stopped", "I"], "a": "I stopped smoking."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the view", "at", "look", "to", "stopped", "I"], "a": "I stopped to look at the view."},
  ] },
  27: { core: "to는 몸의 이동, for는 **마음의 이동**.", qs: [
    {"t": "scene", "ctx": "EP.27, 민준이 마지막 동작을 넘기며", "q": "민준: I know. But it works better ______ you.", "opts": ["for", "to", "at", "in"], "a": "for", "why": "너를 생각해서 바꾼다. 몸이 아니라 마음이 움직였다."},
    {"t": "choice", "q": "for가 나타내는 것은?", "opts": ["범위 안", "누구를 위해서", "한 점", "붙어있음"], "a": "누구를 위해서"},
    {"t": "choice", "q": "`Thank you ______ your help.` 빈칸은?", "opts": ["for", "to", "at", "in"], "a": "for"},
    {"t": "order", "words": ["you", "This", "for", "is"], "q": "단어를 순서대로 놓으세요", "a": "This is for you."},
    {"t": "order", "words": ["the exam", "studying", "I'm", "for"], "q": "단어를 순서대로 놓으세요", "a": "I'm studying for the exam."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["you", "for", "waiting", "I'm"], "a": "I'm waiting for you."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["your help", "for", "you", "Thank"], "a": "Thank you for your help."},
  ] },
  28: { core: "in = 어떤 **범위 안**. 공간·시간·상황 모두 테두리가 있다.", qs: [
    {"t": "scene", "ctx": "EP.28, 무대 직전 셋이 손을 포개고", "q": "민준: We're ______ this together.", "opts": ["in", "at", "on", "for"], "a": "in", "why": "같은 테두리 안에 셋이 들어와 있다."},
    {"t": "choice", "q": "in을 쓸 수 없는 것은?", "opts": ["in the box", "in Korea", "in the morning", "in 3 o'clock"], "a": "in 3 o'clock", "why": "정확한 시각은 at"},
    {"t": "choice", "q": "`She was born ______ Busan.` 빈칸은?", "opts": ["in", "at", "on", "to"], "a": "in"},
    {"t": "order", "words": ["trouble", "is", "He", "in"], "q": "단어를 순서대로 놓으세요", "a": "He is in trouble."},
    {"t": "order", "words": ["music", "I'm", "in", "interested"], "q": "단어를 순서대로 놓으세요", "a": "I'm interested in music."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["Korea", "in", "born", "was", "She"], "a": "She was born in Korea."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the morning", "in", "is", "The meeting"], "a": "The meeting is in the morning."},
  ] },
  29: { core: "at = 넓이가 아니라 **위치 하나, 시각 하나, 대상 하나**를 콕 찍는다.", qs: [
    {"t": "scene", "ctx": "EP.29", "q": "민준: (속으로) Look ______ the light. Just the light.", "opts": ["at", "in", "on", "to"], "a": "at", "why": "관객 전체가 아니라 조명 한 점에 초점을 맞춘다."},
    {"t": "choice", "q": "at이 어울리는 것은?", "opts": ["at Korea", "at the morning", "at 3 o'clock", "at trouble"], "a": "at 3 o'clock"},
    {"t": "choice", "q": "`Let's meet ______ the bus stop.` 빈칸은?", "opts": ["at", "in", "on", "to"], "a": "at"},
    {"t": "order", "words": ["school", "I'm", "at"], "q": "단어를 순서대로 놓으세요", "a": "I'm at school."},
    {"t": "order", "words": ["math", "He's", "at", "good"], "q": "단어를 순서대로 놓으세요", "a": "He's good at math."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["3 o'clock", "at", "arrived", "She"], "a": "She arrived at 3 o'clock."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["you", "at", "looking", "I'm"], "a": "I'm looking at you."},
  ] },
  30: { core: "on = 위가 아니라 **접촉**. 물건도, 활동도, 상태도 닿아 있으면 on.", qs: [
    {"t": "scene", "ctx": "EP.30", "q": "삼돌이: You're still ______ the beat. Keep going, idiot.", "opts": ["on", "in", "at", "to"], "a": "on", "why": "박자에서 떨어지지 않았다는 뜻. 붙어 있으라는 말."},
    {"t": "choice", "q": "on이 어울리지 않는 것은?", "opts": ["on the table", "on Monday", "on vacation", "on Korea"], "a": "on Korea"},
    {"t": "choice", "q": "`I'm ______ my way home.` 빈칸은?", "opts": ["on", "in", "at", "to"], "a": "on"},
    {"t": "order", "words": ["the", "The book", "table", "is", "on"], "q": "단어를 순서대로 놓으세요", "a": "The book is on the table."},
    {"t": "order", "words": ["the", "I'm", "phone", "on"], "q": "단어를 순서대로 놓으세요", "a": "I'm on the phone."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["Monday", "on", "is", "The meeting"], "a": "The meeting is on Monday."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["vacation", "on", "He's"], "a": "He's on vacation."},
  ] },
  31: { core: "둘 다 '떨어져 나온다'에서 나왔다. of는 머리로, off는 몸으로.", qs: [
    {"t": "scene", "ctx": "EP.31, 삼돌이가 전학을 안 간다고 밝히며", "q": "민준: ______ the transfer list?\n삼돌이: ______ the list.", "opts": ["Off", "Of", "On", "At"], "a": "Off", "why": "명단에서 몸이 빠져나왔다. 실제로 벗어난 것."},
    {"t": "choice", "q": "of가 어울리는 것은?", "opts": ["take of your shoes", "a piece of cake", "turn of the light", "get of the bus"], "a": "a piece of cake"},
    {"t": "choice", "q": "`Turn ______ the light.` 불을 끄라는 뜻이면?", "opts": ["off", "of", "on", "in"], "a": "off"},
    {"t": "order", "words": ["mine", "a", "of", "friend"], "q": "단어를 순서대로 놓으세요", "a": "a friend of mine"},
    {"t": "order", "words": ["the", "Get", "bus", "off"], "q": "단어를 순서대로 놓으세요", "a": "Get off the bus."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the table", "of", "the leg"], "a": "the leg of the table"},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["your shoes", "off", "Take"], "a": "Take off your shoes."},
  ] },
  32: { core: "전치사는 단어가 아니라 **그림**이다. 일곱 개면 끝난다.", qs: [
    {"t": "scene", "ctx": "EP.32, 편의점 앞 계단에서 셋이", "q": "못난이: We're ______ the same team.\n민준: ______ the same school.\n못난이: ______ the same mess.", "opts": ["on / At / In", "in / On / At", "at / In / On", "to / For / Of"], "a": "on / At / In", "why": "팀에 붙어 있고, 학교라는 점에 있고, 같은 상황 안에 있다. 세 전치사가 한 장면에 다 나온다."},
    {"t": "choice", "q": "그림이 잘못 짝지어진 것은?", "opts": ["to = 화살표", "in = 경계 안", "at = 한 점", "on = 범위 안"], "a": "on = 범위 안", "why": "on은 접촉"},
    {"t": "choice", "q": "`The meeting is ______ Monday.` 빈칸은?", "opts": ["on", "in", "at", "for"], "a": "on"},
    {"t": "order", "words": ["us", "is", "This", "for"], "q": "단어를 순서대로 놓으세요", "a": "This is for us."},
    {"t": "order", "words": ["stage", "a", "We", "want", "bigger"], "q": "단어를 순서대로 놓으세요", "a": "We want a bigger stage."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the same school", "at", "We're"], "a": "We're at the same school."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["team", "same", "the", "on", "We're"], "a": "We're on the same team."},
  ] },
  33: { core: "with = 나한테 딱 붙어서 함께. 사람이든 도구든 붙어 있으면 with.", qs: [
    {"t": "scene", "ctx": "EP.33, 종탑 아래 이른 아침", "q": "도윤: Okay. I'm coming ______ my camera.", "opts": ["with", "by", "from", "about"], "a": "with", "why": "카메라를 몸에 붙여서 같이 간다. 붙어서 함께 = with."},
    {"t": "choice", "q": "with의 그림은?", "opts": ["화살표", "붙어서 함께", "한 점", "경계 안"], "a": "붙어서 함께"},
    {"t": "choice", "q": "`I write ______ a pencil.` 빈칸은?", "opts": ["with", "from", "at", "of"], "a": "with", "why": "연필이 손에 붙어서 같이 움직인다."},
    {"t": "order", "words": ["with", "me", "Come"], "q": "단어를 순서대로 놓으세요", "a": "Come with me."},
    {"t": "order", "words": ["a pencil", "with", "write", "I"], "q": "단어를 순서대로 놓으세요", "a": "I write with a pencil."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["school", "with", "I", "my friend", "go to"], "a": "I go to school with my friend."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a red hat", "with", "girl", "The"], "a": "The girl with a red hat"},
  ] },
  34: { core: "by = 바로 곁. 곁에 있으니 옆 자리도, 방법도, 만든 사람도, 시한까지도 된다.", qs: [
    {"t": "scene", "ctx": "EP.34, 관리실 창가에서", "q": "강 할아버지: I sat ______ the window all night.", "opts": ["by", "from", "into", "about"], "a": "by", "why": "창문 바로 곁에 앉았다. 곁 = by."},
    {"t": "choice", "q": "`Come back ______ six.` (6시까지 돌아와)", "opts": ["by", "with", "from", "of"], "a": "by", "why": "6시라는 시각 곁까지 다가오면 된다. 늦어도 그때까지."},
    {"t": "choice", "q": "`This song was written ______ Mina.` (이 노래는 미나가 썼어)", "opts": ["by", "on", "in", "off"], "a": "by", "why": "노래 곁에 있는 사람, 곧 만든 사람이다."},
    {"t": "order", "words": ["by", "sits", "She", "the window"], "q": "단어를 순서대로 놓으세요", "a": "She sits by the window."},
    {"t": "order", "words": ["by", "train", "went", "there", "We"], "q": "단어를 순서대로 놓으세요", "a": "We went there by train."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["it", "by", "did", "myself", "I"], "a": "I did it by myself."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["six", "back", "by", "Come"], "a": "Come back by six."},
  ] },
  35: { core: "from = 화살표의 꼬리, 출발한 곳. to가 머리라면 from은 꼬리.", qs: [
    {"t": "scene", "ctx": "EP.35, 학교 뒷담장에서 소이를 만나", "q": "도윤: Where are you ______?\n소이: Busan. I came ______ Busan last week.", "opts": ["from / from", "to / to", "for / from", "at / of"], "a": "from / from", "why": "어디서 출발했는지 묻고 답한다. 꼬리 = from."},
    {"t": "choice", "q": "화살표의 꼬리, 출발한 곳을 가리키는 전치사는?", "opts": ["to", "from", "at", "in"], "a": "from"},
    {"t": "choice", "q": "`The gift is ______ my mom.` (엄마가 준 선물이야)", "opts": ["from", "to", "at", "in"], "a": "from", "why": "엄마 손에서 출발한 선물이다."},
    {"t": "order", "words": ["from", "I'm", "Korea"], "q": "단어를 순서대로 놓으세요", "a": "I'm from Korea."},
    {"t": "order", "words": ["cows", "from", "comes", "Milk"], "q": "단어를 순서대로 놓으세요", "a": "Milk comes from cows."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the fire", "from", "away", "Stay"], "a": "Stay away from the fire."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["from", "tower", "the", "fell", "It"], "a": "It fell from the tower."},
  ] },
  36: { core: "at은 정확한 한 점, about은 그 둘레를 빙 돈다. 그래서 '대략'과 '~에 대해'가 된다.", qs: [
    {"t": "scene", "ctx": "EP.36, 빈 교실에서 단서를 정리하며", "q": "하늘: What do you know ______ the bell?\n소이: There's an old story ______ it.", "opts": ["about / about", "at / on", "for / about", "to / of"], "a": "about / about", "why": "종 둘레를 맴도는 이야기다. 둘레 = about."},
    {"t": "choice", "q": "`It's ______ three o'clock.` (대략 3시쯤이야)", "opts": ["about", "in", "for", "of"], "a": "about", "why": "3시 한 점이 아니라 그 둘레다."},
    {"t": "choice", "q": "at과 about의 차이는?", "opts": ["at은 한 점, about은 둘레", "at은 둘레, about은 한 점", "둘 다 한 점", "둘 다 둘레"], "a": "at은 한 점, about은 둘레"},
    {"t": "order", "words": ["about", "talk", "Let's", "the plan"], "q": "단어를 순서대로 놓으세요", "a": "Let's talk about the plan."},
    {"t": "order", "words": ["a dog", "is", "book", "about", "This"], "q": "단어를 순서대로 놓으세요", "a": "This book is about a dog."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["about", "you", "are", "thinking", "What"], "a": "What are you thinking about?"},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["students", "twenty", "came", "About"], "a": "About twenty students came."},
  ] },
  37: { core: "over = 떨어져서 위로 넘는다, under = 그 밑에. on은 닿아 있고 over는 떨어져 있다.", qs: [
    {"t": "scene", "ctx": "EP.37, 뒷문 밖 울타리 앞", "q": "하늘: Then we go ______ the fence.\n도윤: There's something ______ this stone.", "hint": "울타리는 넘어가고, 돌은 밑을 들여다본다", "opts": ["over / under", "under / over", "on / in", "at / by"], "a": "over / under", "why": "울타리 위로 넘고, 돌 아래를 본다. 위 = over, 아래 = under."},
    {"t": "choice", "q": "`A plane flew ______ the house.` (닿지 않고 집 위를 날았다)", "opts": ["over", "on", "under", "into"], "a": "over", "why": "닿아 있으면 on, 떨어져서 위로 지나가면 over."},
    {"t": "choice", "q": "`The cat is under the table.`의 뜻은?", "opts": ["고양이가 식탁 위에 있다", "고양이가 식탁 밑에 있다", "고양이가 식탁 옆에 있다", "고양이가 식탁 안에 있다"], "a": "고양이가 식탁 밑에 있다"},
    {"t": "order", "words": ["over", "fence", "Jump", "the"], "q": "단어를 순서대로 놓으세요", "a": "Jump over the fence."},
    {"t": "order", "words": ["under", "cat", "is", "The", "the table"], "q": "단어를 순서대로 놓으세요", "a": "The cat is under the table."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["over", "flew", "A", "plane", "the house"], "a": "A plane flew over the house."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["under", "something", "There's", "this", "stone"], "a": "There's something under this stone."},
  ] },
  38: { core: "in은 안에 가만히 있는 것. into는 안으로 들어가는 화살표, out of는 밖으로 나오는 화살표.", qs: [
    {"t": "scene", "ctx": "EP.38, 낡은 창고에서", "q": "하늘: We're going ______ the dark.\n도윤: Someone just ran ______ the storeroom!", "hint": "어둠 속으로 들어가고, 창고 밖으로 뛰어나갔다", "opts": ["into / out of", "out of / into", "in / on", "from / to"], "a": "into / out of", "why": "어둠 속으로 들어가고, 창고 밖으로 뛰어나갔다."},
    {"t": "choice", "q": "`Water turned ______ ice.` (물이 얼음으로 변했다)", "opts": ["into", "in", "at", "on"], "a": "into", "why": "물이라는 경계를 나와 얼음이라는 경계 안으로 들어갔다."},
    {"t": "choice", "q": "in과 into의 차이는?", "opts": ["in은 안에 있음, into는 안으로 들어감", "in은 밖, into는 안", "둘은 똑같다", "in은 움직임, into는 멈춤"], "a": "in은 안에 있음, into는 안으로 들어감"},
    {"t": "order", "words": ["into", "He", "room", "walked", "the"], "q": "단어를 순서대로 놓으세요", "a": "He walked into the room."},
    {"t": "order", "words": ["out of", "Get", "car", "the"], "q": "단어를 순서대로 놓으세요", "a": "Get out of the car."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["out of", "money", "I", "ran"], "a": "I ran out of money."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["pool", "jumped", "the", "into", "She"], "a": "She jumped into the pool."},
  ] },
  39: { core: "up은 위로 가는 화살표, down은 아래로 가는 화살표. 높이뿐 아니라 숫자와 마음의 오르내림도.", qs: [
    {"t": "scene", "ctx": "EP.39, 종탑 나선 계단에서", "q": "하늘: Come on! ______ the stairs!\n도윤: Look. Someone is walking ______ the hill.", "hint": "계단은 올라가고, 언덕은 내려간다", "opts": ["Up / down", "Down / up", "In / on", "Over / under"], "a": "Up / down", "why": "계단은 위로 올라가고, 언덕은 아래로 내려간다."},
    {"t": "choice", "q": "`Turn ______ the volume.` (볼륨을 키워)", "opts": ["up", "down", "off", "at"], "a": "up", "why": "숫자가 위로 올라가니 up."},
    {"t": "choice", "q": "`Calm ______.` (진정해)", "opts": ["down", "up", "over", "into"], "a": "down", "why": "들뜬 마음이 아래로 가라앉는다."},
    {"t": "order", "words": ["stairs", "Go", "the", "up"], "q": "단어를 순서대로 놓으세요", "a": "Go up the stairs."},
    {"t": "order", "words": ["hill", "the", "Walk", "down"], "q": "단어를 순서대로 놓으세요", "a": "Walk down the hill."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["stairs", "the", "down", "Come"], "a": "Come down the stairs."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the hill", "is", "walking", "Someone", "down"], "a": "Someone is walking down the hill."},
  ] },
  40: { core: "전치사는 그림이다. with 붙어서 함께 · by 곁 · from 꼬리 · about 둘레 · over 위 · under 밑 · into 안으로 · out of 밖으로 · up 위로 · down 아래로.", qs: [
    {"t": "scene", "ctx": "EP.40, 종탑 아래 새벽에 단서를 정리하며", "q": "하늘: A truck ______ the gate. A key ______ the stone. A lantern ______ the hill.", "opts": ["by / under / down", "with / over / up", "from / into / out of", "about / at / on"], "a": "by / under / down", "why": "문 곁에 트럭, 돌 밑에 열쇠, 언덕 아래로 내려가는 등불."},
    {"t": "choice", "q": "`The letter came ______ my grandfather.` (할아버지에게서 왔다)", "opts": ["from", "by", "over", "up"], "a": "from", "why": "할아버지 손에서 출발했다. 꼬리 = from."},
    {"t": "choice", "q": "그림이 잘못 짝지어진 것은?", "opts": ["with = 붙어서 함께", "from = 화살표의 꼬리", "about = 정확한 한 점", "into = 안으로 들어가는 화살표"], "a": "about = 정확한 한 점", "why": "about은 한 점의 둘레. 정확한 한 점은 at이다."},
    {"t": "order", "words": ["from", "This", "my grandfather", "is"], "q": "단어를 순서대로 놓으세요", "a": "This is from my grandfather."},
    {"t": "order", "words": ["a key", "under", "There's", "the stone"], "q": "단어를 순서대로 놓으세요", "a": "There's a key under the stone."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["ran", "the storeroom", "Someone", "out of"], "a": "Someone ran out of the storeroom."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["about", "story", "an old", "There's", "the bell"], "a": "There's an old story about the bell."},
  ] },
  41: { core: "through = 한쪽으로 들어가서 반대쪽으로 나오는 터널. into는 들어가서 끝나고, through는 빠져나간다.", qs: [
    {"t": "scene", "ctx": "EP.41, 안개 낀 어시장에서", "q": "도윤: I can't see ______ this fog.", "opts": ["through", "by", "for", "about"], "a": "through", "why": "안개를 뚫고 반대쪽까지 보려는데 안 보인다. 뚫고 지나가는 시선 = through."},
    {"t": "choice", "q": "`The train goes ______ a tunnel.` (기차가 터널을 통과한다)", "opts": ["through", "at", "of", "off"], "a": "through", "why": "한쪽으로 들어가서 반대쪽으로 나온다."},
    {"t": "choice", "q": "into와 through의 차이는?", "opts": ["into는 들어가서 끝나고, through는 반대쪽으로 나온다", "into는 위로 넘고, through는 밑으로 간다", "둘은 똑같은 뜻이다", "into는 나오는 것이고, through는 들어가는 것이다"], "a": "into는 들어가서 끝나고, through는 반대쪽으로 나온다"},
    {"t": "order", "words": ["through", "We", "the market", "walked"], "q": "단어를 순서대로 놓으세요", "a": "We walked through the market."},
    {"t": "order", "words": ["looked", "She", "the window", "through"], "q": "단어를 순서대로 놓으세요", "a": "She looked through the window."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the night", "through", "talked", "We"], "a": "We talked through the night."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a tunnel", "goes", "through", "The train"], "a": "The train goes through a tunnel."},
  ] },
  42: { core: "between = 둘 사이에 끼어 있다, among = 여럿 속에 섞여 있다.", qs: [
    {"t": "scene", "ctx": "EP.42, 빽빽한 부두에서", "q": "도윤: ______ all these boats? Impossible.\n하늘: The smallest boat is ______ those two big ones.", "hint": "배 오십 척 속에서 찾고, 작은 배는 큰 배 두 척 사이에 끼어 있다", "opts": ["Among / between", "Between / among", "Through / between", "Among / over"], "a": "Among / between", "why": "여럿 속은 among, 딱 둘 사이는 between."},
    {"t": "choice", "q": "`She is the tallest ______ her friends.` (친구들 중에서 그녀가 제일 크다)", "opts": ["among", "between", "by", "off"], "a": "among", "why": "친구 여럿 속에서 견준다."},
    {"t": "choice", "q": "`Sit ______ Mina and me.` (미나와 나 사이에 앉아)", "opts": ["between", "among", "through", "over"], "a": "between", "why": "양쪽에 하나씩, 딱 둘이다."},
    {"t": "order", "words": ["between", "cat", "is", "The", "the two boxes"], "q": "단어를 순서대로 놓으세요", "a": "The cat is between the two boxes."},
    {"t": "order", "words": ["Mina", "and", "me", "between", "Sit"], "q": "단어를 순서대로 놓으세요", "a": "Sit between Mina and me."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the bank", "between", "and", "the school", "is", "The shop"], "a": "The shop is between the bank and the school."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["my hat", "found", "among", "I", "the coats"], "a": "I found my hat among the coats."},
  ] },
  43: { core: "before = 줄의 앞, after = 줄의 뒤. 시간도 순서도 같은 줄이다.", qs: [
    {"t": "scene", "ctx": "EP.43, 관리실 모니터 앞에서", "q": "소이: ______ two, the gate is empty.\n하늘: ______ the truck, the video jumps.", "hint": "트럭이 오기 전에는 문이 비어 있고, 트럭이 온 뒤에 영상이 튄다", "opts": ["Before / After", "After / Before", "Before / Among", "Along / After"], "a": "Before / After", "why": "2시보다 앞은 before, 트럭보다 뒤는 after."},
    {"t": "choice", "q": "`Wash your hands ______ dinner.` (저녁 먹기 전에 손을 씻어)", "opts": ["before", "after", "between", "through"], "a": "before", "why": "저녁이라는 자리보다 줄 앞이다."},
    {"t": "choice", "q": "`Come ______ six.` (6시 정각은 안 되고, 6시가 되기 전에 와)", "opts": ["before", "by", "after", "at"], "a": "before", "why": "by six는 6시 정각도 통과하고, before six는 6시 정각이 못 들어온다."},
    {"t": "order", "words": ["before", "dinner", "Wash", "your hands"], "q": "단어를 순서대로 놓으세요", "a": "Wash your hands before dinner."},
    {"t": "order", "words": ["call", "I", "school", "after", "my mom"], "q": "단어를 순서대로 놓으세요", "a": "I call my mom after school."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the movie", "talked", "after", "We"], "a": "We talked after the movie."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["before", "two", "The gate", "empty", "is"], "a": "The gate is empty before two."},
  ] },
  44: { core: "above = 선보다 위, below = 선보다 아래. 거리는 상관없고 높이만 본다.", qs: [
    {"t": "scene", "ctx": "EP.44, 유리 바닥 보트 위에서", "q": "하늘: The sun is ______ us. The light goes all the way down.\n소이: Look. ______ that rock.", "hint": "해는 우리 위에 있고, 붉은 끈은 바위 아래에서 흔들린다", "opts": ["above / Below", "below / Above", "above / Among", "through / Below"], "a": "above / Below", "why": "해는 우리보다 높은 곳, 끈은 바위보다 낮은 곳이다."},
    {"t": "choice", "q": "`The temperature is ______ zero.` (기온이 영하야)", "opts": ["below", "above", "among", "through"], "a": "below", "why": "0이라는 눈금선보다 아래다."},
    {"t": "choice", "q": "above와 over의 차이로 맞는 것은?", "opts": ["above는 높이만 위쪽이고, over는 바로 위를 넘어가는 그림이다", "above는 아래쪽이고, over는 위쪽이다", "둘은 서로 반대말이다", "above는 시간에만 쓴다"], "a": "above는 높이만 위쪽이고, over는 바로 위를 넘어가는 그림이다"},
    {"t": "order", "words": ["above", "the sea", "is", "The sun"], "q": "단어를 순서대로 놓으세요", "a": "The sun is above the sea."},
    {"t": "order", "words": ["the boat", "swim", "below", "The fish"], "q": "단어를 순서대로 놓으세요", "a": "The fish swim below the boat."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["zero", "below", "The temperature", "is"], "a": "The temperature is below zero."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["mine", "Her name", "is", "above", "on the list"], "a": "Her name is above mine on the list."},
  ] },
  45: { core: "around = 가운데를 빙 둘러 있거나 한 바퀴 돌아서 간다.", qs: [
    {"t": "scene", "ctx": "EP.45, 밀물이 차오르는 방파제에서", "q": "하늘: Keep moving. We can rest ______ the corner.", "opts": ["around", "through", "among", "between"], "a": "around", "why": "모퉁이를 돌아서 그 뒤로 간다. 돌아서 = around."},
    {"t": "choice", "q": "`We sat ______ the fire.` (우리는 불 둘레에 둘러앉았다)", "opts": ["around", "through", "above", "between"], "a": "around", "why": "불이 가운데, 사람이 동그랗게."},
    {"t": "choice", "q": "`It's ______ three o'clock.` (3시쯤이야)에 함께 쓸 수 있는 두 단어는?", "opts": ["about, around", "through, into", "above, below", "between, among"], "a": "about, around", "why": "시각과 숫자에서는 about과 around를 바꿔 쓴다."},
    {"t": "order", "words": ["around", "sat", "We", "the fire"], "q": "단어를 순서대로 놓으세요", "a": "We sat around the fire."},
    {"t": "order", "words": ["around", "the lake", "walked", "I"], "q": "단어를 순서대로 놓으세요", "a": "I walked around the lake."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the corner", "around", "We", "rest", "can"], "a": "We can rest around the corner."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["around", "the lake", "The path", "goes"], "a": "The path goes around the lake."},
  ] },
  46: { core: "across = 이쪽에서 저쪽으로 가로질러, along = 길게 뻗은 것을 따라.", qs: [
    {"t": "scene", "ctx": "EP.46, 작은 배로 만을 건너 등대로", "q": "소이: It's a long way ______ the bay.\n소이: Run ______ the pier! It leads to the lighthouse.", "hint": "만은 이쪽에서 저쪽으로 건너고, 부두는 길을 따라 달린다", "opts": ["across / along", "along / across", "through / across", "across / above"], "a": "across / along", "why": "만의 한쪽 끝에서 반대쪽 끝으로 건너고, 길게 뻗은 부두를 따라 달린다."},
    {"t": "choice", "q": "`Walk ______ the street.` (길을 건너)", "opts": ["across", "along", "among", "off"], "a": "across", "why": "길 한쪽에서 반대쪽으로 간다."},
    {"t": "choice", "q": "`There are trees ______ the road.` (길을 따라 나무가 서 있다)", "opts": ["along", "across", "between", "above"], "a": "along", "why": "길이 뻗은 방향으로 늘어서 있다."},
    {"t": "order", "words": ["across", "rowed", "We", "the bay"], "q": "단어를 순서대로 놓으세요", "a": "We rowed across the bay."},
    {"t": "order", "words": ["along", "walked", "She", "the pier"], "q": "단어를 순서대로 놓으세요", "a": "She walked along the pier."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the street", "across", "Walk"], "a": "Walk across the street."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the road", "along", "There are", "trees"], "a": "There are trees along the road."},
  ] },
  47: { core: "behind = 가려지는 뒤, beside = 나란히 서는 옆.", qs: [
    {"t": "scene", "ctx": "EP.47, 등대 아래에서", "q": "하늘: Someone is ______ the lighthouse.\n강 할아버지: Stand ______ me, Soi.", "opts": ["behind / beside", "through / beside", "behind / among", "above / between"], "a": "behind / beside", "why": "등대 뒤쪽 그늘에 누가 있고, 소이는 곁에 나란히 서라고 한다."},
    {"t": "choice", "q": "`The cat is ______ the door.` (고양이는 문 뒤에 있다)", "opts": ["behind", "beside", "among", "through"], "a": "behind", "why": "문에 가려서 안 보인다."},
    {"t": "choice", "q": "`She stood ______ me.` (그녀는 내 바로 옆에 나란히 섰다)", "opts": ["beside", "behind", "through", "across"], "a": "beside", "why": "가려지는 게 아니라 나란히 선다."},
    {"t": "order", "words": ["behind", "cat", "is", "The", "the door"], "q": "단어를 순서대로 놓으세요", "a": "The cat is behind the door."},
    {"t": "order", "words": ["stood", "She", "beside", "me"], "q": "단어를 순서대로 놓으세요", "a": "She stood beside me."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["went", "The sun", "the clouds", "behind"], "a": "The sun went behind the clouds."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the tree", "behind", "is", "hiding", "Who"], "a": "Who is hiding behind the tree?"},
  ] },
  48: { core: "이번 달 그림은 길과 자리다. 열두 개를 지도처럼 겹쳐 본다.", qs: [
    {"t": "scene", "ctx": "EP.48, 등대 앞에서 강 할아버지가 시간을 말하며", "q": "강 할아버지: Come back when the tide is low. ______ six in the morning.\n하늘: Six o'clock. The bell is ______ the water.", "hint": "새벽 여섯 시가 되기 전에 오고, 종은 물 아래에 있다", "opts": ["Before / below", "After / above", "Before / above", "Behind / below"], "a": "Before / below", "why": "6시보다 앞은 before, 물 수면보다 아래는 below."},
    {"t": "choice", "q": "그림이 잘못 짝지어진 것은?", "opts": ["through = 들어가서 반대쪽으로 나옴", "between = 여럿 속에 섞임", "across = 이쪽에서 저쪽으로 건넘", "behind = 가려서 안 보이는 뒤"], "a": "between = 여럿 속에 섞임", "why": "여럿 속에 섞이는 건 among이다. between은 딱 둘 사이."},
    {"t": "choice", "q": "`Walk ______ the pier.` (부두를 따라 걸어)", "opts": ["along", "through", "among", "behind"], "a": "along", "why": "길게 뻗은 부두를 따라간다."},
    {"t": "order", "words": ["through", "went", "We", "the market"], "q": "단어를 순서대로 놓으세요", "a": "We went through the market."},
    {"t": "order", "words": ["below", "the water", "The bell", "is"], "q": "단어를 순서대로 놓으세요", "a": "The bell is below the water."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["along", "the pier", "ran", "We"], "a": "We ran along the pier."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["six", "before", "Come back"], "a": "Come back before six."},
  ] },
  49: { core: "during은 일이 벌어지는 시간의 띠 안이다. 길이(두 시간)는 for, 사건(영화·폭풍)은 during.", qs: [
    {"t": "scene", "ctx": "EP.49, 썰물의 새벽 갯바위에서", "q": "도윤: What did you do ______ the storm?", "hint": "폭풍이 부는 동안 뭘 했느냐고 묻는다", "opts": ["during", "with", "from", "against"], "a": "during", "why": "폭풍이라는 일이 벌어지는 시간의 띠 안이다. 사건 앞은 during."},
    {"t": "choice", "q": "`Don't talk ______ the movie.` (영화 하는 동안 떠들지 마)", "opts": ["during", "for", "toward", "beyond"], "a": "during", "why": "영화는 사건이다. 길이가 아니라 무슨 일이냐가 오면 during."},
    {"t": "choice", "q": "`I slept ______ two hours.` (두 시간 동안 잤어)", "opts": ["for", "during", "since", "against"], "a": "for", "why": "두 시간은 길이다. 길이는 for, 사건은 during."},
    {"t": "order", "words": ["the night", "during", "It", "rained"], "q": "단어를 순서대로 놓으세요", "a": "It rained during the night."},
    {"t": "order", "words": ["the movie", "during", "talk", "Don't"], "q": "단어를 순서대로 놓으세요", "a": "Don't talk during the movie."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the storm", "during", "rang", "bell", "The"], "a": "The bell rang during the storm."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["you", "did", "What", "the storm", "during", "do"], "a": "What did you do during the storm?"},
  ] },
  50: { core: "until은 끝 말뚝까지 쭉, since는 시작 말뚝에서 지금까지 쭉 이어진다.", qs: [
    {"t": "scene", "ctx": "EP.50, 관리실에서 이사회 소식을 듣고", "q": "강 할아버지: The board meets next Friday. The bell stays hidden ______ Friday.", "hint": "금요일까지 쭉 숨겨 둔다는 뜻", "opts": ["until", "since", "from", "against"], "a": "until", "why": "금요일이 끝 말뚝이다. 그때까지 쭉 이어지면 until."},
    {"t": "choice", "q": "`Wait here ______ six.` (6시까지 쭉 여기서 기다려)", "opts": ["until", "by", "since", "during"], "a": "until", "why": "기다림이 쭉 이어지다가 6시에 끝난다. 한 번 해내면 끝나는 by와 다르다."},
    {"t": "choice", "q": "`I have lived here ______ 2020.` (2020년부터 지금까지 여기 살았어)", "opts": ["since", "until", "during", "against"], "a": "since", "why": "2020이 시작 말뚝이고 줄이 지금까지 이어진다."},
    {"t": "order", "words": ["until", "here", "six", "Wait"], "q": "단어를 순서대로 놓으세요", "a": "Wait here until six."},
    {"t": "order", "words": ["since", "2020", "lived", "have", "here", "I"], "q": "단어를 순서대로 놓으세요", "a": "I have lived here since 2020."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["until", "We", "rang", "the bell", "waited"], "a": "We waited until the bell rang."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["since", "Monday", "has", "here", "She", "been"], "a": "She has been here since Monday."},
  ] },
  51: { core: "without은 with가 빠진 빈자리다. 있어야 할 것이 없다.", qs: [
    {"t": "scene", "ctx": "EP.51, 보건소 복도에서 여섯 시에", "q": "소이: Nothing comes. He can't sleep ______ that sound.", "hint": "그 소리가 없으면 잠을 못 잔다는 뜻", "opts": ["without", "with", "by", "from"], "a": "without", "why": "그 소리가 빠진 자리가 비었다. with(함께)가 빠지면 without."},
    {"t": "choice", "q": "`I can't live ______ music.` (음악 없이는 못 살아)", "opts": ["without", "with", "during", "toward"], "a": "without", "why": "음악이 있어야 할 자리가 비면 without."},
    {"t": "choice", "q": "`She left ______ saying goodbye.` (그녀는 작별 인사도 없이 떠났어)", "opts": ["without", "until", "during", "toward"], "a": "without", "why": "without 뒤의 동작은 saying처럼 -ing 꼴이다."},
    {"t": "order", "words": ["without", "an umbrella", "out", "go", "Don't"], "q": "단어를 순서대로 놓으세요", "a": "Don't go out without an umbrella."},
    {"t": "order", "words": ["without", "music", "sleep", "can't", "I"], "q": "단어를 순서대로 놓으세요", "a": "I can't sleep without music."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["without", "goodbye", "saying", "left", "She"], "a": "She left without saying goodbye."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["without", "sugar", "coffee", "drinks", "He"], "a": "He drinks coffee without sugar."},
  ] },
  52: { core: "against는 맞대고 미는 힘이다. 기댈 때도, 반대할 때도, 겨룰 때도 같은 그림.", qs: [
    {"t": "scene", "ctx": "EP.52, 정문 앞에서 Mr. Park와", "q": "Mr. Park: Gone? The board voted. Seven for, one ______.", "hint": "일곱은 찬성, 하나는 반대라는 뜻", "opts": ["against", "above", "among", "along"], "a": "against", "why": "찬성 일곱, 반대 하나. 계획과 반대쪽에 선 표는 against."},
    {"t": "choice", "q": "`I voted ______ the plan.` (나는 그 계획에 반대표를 던졌어)", "opts": ["against", "for", "by", "from"], "a": "against", "why": "계획과 반대쪽에 서 있다."},
    {"t": "choice", "q": "on과 against의 차이는?", "opts": ["on은 그냥 닿아 있음, against는 힘을 싣고 맞대고 있음", "on은 힘을 싣고 맞댐, against는 그냥 닿아 있음", "둘은 똑같다", "on은 위, against는 아래"], "a": "on은 그냥 닿아 있음, against는 힘을 싣고 맞대고 있음"},
    {"t": "order", "words": ["against", "the wall", "leans", "He"], "q": "단어를 순서대로 놓으세요", "a": "He leans against the wall."},
    {"t": "order", "words": ["against", "Team B", "played", "We"], "q": "단어를 순서대로 놓으세요", "a": "We played against Team B."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["against", "the window", "blew", "wind", "The"], "a": "The wind blew against the window."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["against", "the plan", "voted", "Who"], "a": "Who voted against the plan?"},
  ] },
  53: { core: "like는 닮은 모습을 비추는 거울, as는 진짜 역할을 다는 명찰이다.", qs: [
    {"t": "scene", "ctx": "EP.53, 종탑 꼭대기에서 편지를 읽으며", "q": "소이: The bell is ______ a heart. When it stops, the village stops.", "hint": "종은 심장처럼 마을을 뛰게 한다. 진짜 심장은 아니다", "opts": ["like", "as", "from", "against"], "a": "like", "why": "진짜 심장이 아니라 닮았을 뿐이다. 거울에 비친 모습이니 like."},
    {"t": "choice", "q": "`He works ______ a teacher.` (그는 교사로 일해)", "opts": ["as", "like", "against", "toward"], "a": "as", "why": "진짜 교사라는 명찰을 달고 있다."},
    {"t": "choice", "q": "`He works like a boss.`의 뜻은?", "opts": ["그는 사장으로 일한다", "그는 사장처럼 일한다 (사장이 아닐 수 있다)", "그는 사장을 좋아한다", "그는 사장과 함께 일한다"], "a": "그는 사장처럼 일한다 (사장이 아닐 수 있다)"},
    {"t": "order", "words": ["like", "a bird", "sings", "She"], "q": "단어를 순서대로 놓으세요", "a": "She sings like a bird."},
    {"t": "order", "words": ["as", "a teacher", "works", "He"], "q": "단어를 순서대로 놓으세요", "a": "He works as a teacher."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["as", "a chair", "this box", "Use"], "a": "Use this box as a chair."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["like", "summer", "feels", "It"], "a": "It feels like summer."},
  ] },
  54: { core: "because of는 이유를 등에 업고, despite는 걸림돌을 지나쳐 간다.", qs: [
    {"t": "scene", "ctx": "EP.54, 저녁 갯바위에서 금을 보며", "q": "강 할아버지: It got bigger ______ the sea water.", "hint": "바닷물 때문에 금이 커졌다", "opts": ["because of", "despite", "until", "without"], "a": "because of", "why": "바닷물이 이유다. 이유를 등에 업으면 because of."},
    {"t": "choice", "q": "`We stayed home ______ the rain.` (비 때문에 집에 있었어)", "opts": ["because of", "despite", "because", "during"], "a": "because of", "why": "뒤가 명사(the rain)라서 because of. because 혼자는 뒤에 문장이 온다."},
    {"t": "choice", "q": "`She smiled ______ the pain.` (아팠는데도 웃었어)", "opts": ["despite", "because of", "because", "until"], "a": "despite", "why": "아픔이라는 걸림돌을 지나쳐서 웃었다."},
    {"t": "order", "words": ["because of", "the rain", "home", "stayed", "We"], "q": "단어를 순서대로 놓으세요", "a": "We stayed home because of the rain."},
    {"t": "order", "words": ["despite", "the pain", "smiled", "She"], "q": "단어를 순서대로 놓으세요", "a": "She smiled despite the pain."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the rain", "we", "played", "outside", "Despite"], "a": "Despite the rain, we played outside."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["because of", "the storm", "cancelled", "was", "game", "The"], "a": "The game was cancelled because of the storm."},
  ] },
  55: { core: "toward는 쪽을 가리키며 가는 중, beyond는 선을 넘은 저 너머다.", qs: [
    {"t": "scene", "ctx": "EP.55, 새벽 부두에서 종을 끌어오며", "q": "도윤: It's coming ______ us!", "hint": "종이 우리 쪽으로 다가오는 중이다", "opts": ["toward", "beyond", "against", "without"], "a": "toward", "why": "우리 쪽을 가리키며 오는 중이다. 도착이 아니라 방향이라 toward."},
    {"t": "choice", "q": "`The school is ______ that hill.` (학교는 저 언덕 너머에 있어)", "opts": ["beyond", "toward", "because of", "despite"], "a": "beyond", "why": "언덕이라는 선을 넘은 저편이다."},
    {"t": "choice", "q": "`He is walking toward the sea.`의 뜻으로 맞는 것은?", "opts": ["바다 쪽으로 걸어가는 중이다", "바다에 도착했다", "바다 안에 있다", "바다 너머로 넘어갔다"], "a": "바다 쪽으로 걸어가는 중이다", "why": "toward는 쪽을 가리킨다. 도착은 to."},
    {"t": "order", "words": ["toward", "the pier", "turning", "is", "boat", "The"], "q": "단어를 순서대로 놓으세요", "a": "The boat is turning toward the pier."},
    {"t": "order", "words": ["beyond", "that hill", "is", "school", "The"], "q": "단어를 순서대로 놓으세요", "a": "The school is beyond that hill."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["toward", "the light", "Walk"], "a": "Walk toward the light."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["beyond", "the horizon", "rose", "sun", "The"], "a": "The sun rose beyond the horizon."},
  ] },
  56: { core: "전치사는 그림이 모인 지도다. 이번 달은 시간, 까닭, 방향.", qs: [
    {"t": "scene", "ctx": "EP.56, 종소리가 처음 울린 아침", "q": "하늘: ______ the crack, it sounds ______ home.", "hint": "금이 갔는데도 집처럼 들린다", "opts": ["Despite / like", "Despite / as", "Because of / like", "Because of / as"], "a": "Despite / like", "why": "금이 갔는데도라서 despite, 집을 닮은 소리라서 like."},
    {"t": "choice", "q": "그림이 잘못 짝지어진 것은?", "opts": ["during = 일이 벌어지는 시간의 띠", "without = 빠져서 남은 빈자리", "against = 맞대고 미는 힘", "toward = 도착점에 닿음"], "a": "toward = 도착점에 닿음", "why": "toward는 그쪽을 가리키며 가는 중이다. 도착점에 닿는 건 to."},
    {"t": "choice", "q": "`I'll wait ______ six.` (6시까지 쭉 기다릴게)", "opts": ["until", "by", "since", "during"], "a": "until"},
    {"t": "order", "words": ["since", "Monday", "quiet", "been", "has", "It"], "q": "단어를 순서대로 놓으세요", "a": "It has been quiet since Monday."},
    {"t": "order", "words": ["the crack", "it", "sounds", "home", "like", "Despite"], "q": "단어를 순서대로 놓으세요", "a": "Despite the crack, it sounds like home."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["as", "a bell keeper", "works", "She"], "a": "She works as a bell keeper."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["without", "her", "ring", "can't", "it", "We"], "a": "We can't ring it without her."},
  ] },
};
