// 연습문제 — 과당 7문제
// t: scene 장면(4지선다) · choice 고르기(4지선다) · order 순서 맞추기

const quizData = {
  1: { core: "영어는 **순서**가 뜻이다. 주어 → 동사 → 목적어.", qs: [
    {"t":"order","ctx":"EP.1, 민준이 못난이에게 다가가 말하며","q":"민준의 대사 '나는 네가 필요해.'를 평서문으로 순서대로 놓으세요","words":["you","I","need"],"a":"I need you.","why":"주어 I 바로 뒤에 동사. 세 칸이 순서대로 찬다."},
    {"t":"order","q":"'미나가 준을 사랑해.'를 평서문으로 순서대로 놓으세요","words":["Jun","Mina","loves"],"a":"Mina loves Jun.","why":"사랑하는 쪽(주어)이 맨 앞. Mina가 앞이라 미나가 사랑한다."},
    {"t":"order","q":"'준이 미나를 사랑해.'를 평서문으로 순서대로 놓으세요","words":["loves","Mina","Jun"],"a":"Jun loves Mina.","why":"같은 단어인데 Jun이 앞이라 사랑하는 쪽이 바뀐다."},
    {"t":"order","q":"'준이 미나를 좋아해.'를 평서문으로 순서대로 놓으세요","words":["Mina","Jun","likes"],"a":"Jun likes Mina.","why":"좋아하는 사람이 맨 앞, 대상이 맨 뒤."},
    {"t":"order","q":"'나는 피자를 먹어.'를 평서문으로 순서대로 놓으세요","words":["pizza","I","eat"],"a":"I eat pizza.","why":"주어 → 동사 → 목적어. 먹는 사람이 먼저."},
    {"t":"order","q":"'우리는 영어를 공부해.'를 평서문으로 순서대로 놓으세요","words":["English","We","study"],"a":"We study English.","why":"공부하는 사람(We)이 맨 앞. 영어가 맨 뒤."},
    {"t":"order","q":"'내 여동생은 그림을 그려.'를 평서문으로 순서대로 놓으세요","words":["draws","pictures","My sister"],"a":"My sister draws pictures.","why":"우리말처럼 동사를 맨 뒤에 두지 않는다. 동사는 주어 바로 뒤."}
  ] },
  2: { core: "문장 앞 **기관차 두 칸**(주어 → 동사)이 뼈대. 뒤는 짐칸.", qs: [
    {"t":"order","ctx":"EP.2, 삼돌이가 민준을 밀어내며","q":"삼돌이의 대사 '나는 그룹은 안 해.'를 평서문으로 순서대로 놓으세요","words":["do groups","don't","I"],"a":"I don't do groups.","why":"주어 I 바로 뒤에 동사 don't do. groups는 뒤에 실린 짐."},
    {"t":"order","q":"'개가 달려.'를 평서문으로 순서대로 놓으세요","words":["runs","dog","The"],"a":"The dog runs.","why":"주어 The dog 바로 뒤에 동사 runs. 기관차 두 칸이 앞에 선다."},
    {"t":"order","q":"'내 친구는 서울에 살아.'를 평서문으로 순서대로 놓으세요","words":["Seoul","lives in","My friend"],"a":"My friend lives in Seoul.","why":"My friend → lives가 앞 두 칸. in Seoul은 뒤에 실린 짐칸."},
    {"t":"order","q":"'준은 버스 정류장에서 기다려.'를 평서문으로 순서대로 놓으세요","words":["the bus stop","Jun","waits at"],"a":"Jun waits at the bus stop.","why":"뼈대는 Jun waits. at the bus stop은 뒤에 실린 짐칸이다."},
    {"t":"order","q":"'새는 아침에 노래해.'를 평서문으로 순서대로 놓으세요","words":["the morning","sings in","bird","The"],"a":"The bird sings in the morning.","why":"뼈대는 The bird sings. in the morning은 짐칸이라 맨 뒤."},
    {"t":"order","q":"'우리 팀은 방과 후에 연습해.'를 평서문으로 순서대로 놓으세요","words":["school","practices after","team","Our"],"a":"Our team practices after school.","why":"기관차 Our team practices가 먼저, after school은 뒤 짐칸."},
    {"t":"order","q":"'우리 할아버지는 공원에서 걸으셔.'를 평서문으로 순서대로 놓으세요","words":["the park","walks in","grandfather","My"],"a":"My grandfather walks in the park.","why":"우리말은 동사가 맨 끝이지만 영어는 주어 바로 뒤에 동사(walks)."}
  ] },
  3: { core: "주어 → 동사 → 목적어 **세 칸 틀**에 낱말만 갈아 끼운다.", qs: [
    {"t":"order","ctx":"EP.3, 민준이 못난이의 노트를 다 읽었다며","q":"민준의 대사 '나는 그걸 읽었어.'를 평서문으로 순서대로 놓으세요","words":["it","read","I"],"a":"I read it.","why":"I(주어) → read(동사) → it(목적어). 세 칸이 순서대로 찬다."},
    {"t":"order","q":"'나는 김밥을 먹어.'를 평서문으로 순서대로 놓으세요","words":["gimbap","I","eat"],"a":"I eat gimbap.","why":"나 → 먹는다 → 김밥을. 동사가 두 번째 칸이다."},
    {"t":"order","q":"'나는 음악을 좋아해.'를 평서문으로 순서대로 놓으세요","words":["music","like","I"],"a":"I like music.","why":"틀은 그대로, 낱말만 갈아 끼운다. 동사는 두 번째."},
    {"t":"order","q":"'나는 내 작은 강아지를 사랑해.'를 평서문으로 순서대로 놓으세요","words":["my little dog","I","love"],"a":"I love my little dog.","why":"목적어 my little dog은 낱말이 셋이어도 세 번째 한 칸."},
    {"t":"order","q":"'우리 엄마가 저녁을 요리해.'를 평서문으로 순서대로 놓으세요","words":["dinner","cooks","My mom"],"a":"My mom cooks dinner.","why":"주어 My mom → 동사 cooks → 목적어 dinner. 순서가 뜻이다."},
    {"t":"order","q":"'엠마가 창문을 열어.'를 평서문으로 순서대로 놓으세요","words":["window","opens","Emma","the"],"a":"Emma opens the window.","why":"Emma(주어) → opens(동사) → the window(목적어)."},
    {"t":"order","q":"'미나는 자기 새 노래를 써.'를 평서문으로 순서대로 놓으세요","words":["song","her","writes","new","Mina"],"a":"Mina writes her new song.","why":"우리말처럼 동사를 맨 끝에 두지 않는다. 동사는 두 번째 칸."}
  ] },
  4: { core: "긴 주어는 **한 덩어리**. He·She·It·They로 바꿔 보면 진짜 동사가 남는다.", qs: [
    {"t":"order","ctx":"EP.4, 삼돌이가 한참 뒤 종이를 보며","q":"삼돌이의 대사 '이 종이에 적힌 말은 나쁘지 않아.'를 평서문으로 순서대로 놓으세요","words":["bad","are","The words on this page","not"],"a":"The words on this page are not bad.","why":"긴 첫 칸 The words on this page를 다 채운 뒤에 동사 are."},
    {"t":"order","q":"'빨간 모자를 쓴 남자는 행복해.'를 평서문으로 순서대로 놓으세요","words":["happy","is","The man with a red hat"],"a":"The man with a red hat is happy.","why":"긴 첫 칸 전체가 주어. 그 뒤에 나오는 is가 동사다."},
    {"t":"order","q":"'밤에 짖는 개는 내 침대에서 자.'를 평서문으로 순서대로 놓으세요","words":["my bed","sleeps on","The dog that barks at night"],"a":"The dog that barks at night sleeps on my bed.","why":"barks는 설명 속 동사. 덩어리를 It으로 바꾸면 sleeps가 남는다."},
    {"t":"order","q":"'홀에서 노래하는 여자아이가 내 여동생이야.'를 「여자아이」가 주어인 평서문으로 순서대로 놓으세요","words":["my sister","The girl who sings in the hall","is"],"a":"The girl who sings in the hall is my sister.","why":"The girl who sings in the hall → She. 남는 동사 is."},
    {"t":"order","q":"'미나가 쓴 노래는 길지 않아.'를 평서문으로 순서대로 놓으세요","words":["long","is","The song that Mina wrote","not"],"a":"The song that Mina wrote is not long.","why":"wrote는 설명 속 동사. 덩어리 뒤의 is가 진짜 동사, not은 그 뒤."},
    {"t":"order","q":"'우리 차를 고치는 남자는 아주 친절해.'를 「남자」가 주어인 평서문으로 순서대로 놓으세요","words":["kind","is","The man who fixes our car","very"],"a":"The man who fixes our car is very kind.","why":"fixes는 덩어리 안 동사. 덩어리 다음 is가 진짜 동사다."},
    {"t":"order","q":"'옆집에 사는 사람들은 아주 친절해.'를 평서문으로 순서대로 놓으세요","words":["very","who live next door","friendly","are","The people"],"a":"The people who live next door are very friendly.","why":"live는 who 설명 속 동사. 우리말처럼 꾸밈을 앞에 두지 않고 The people 뒤에."}
  ] },
  5: { core: "셀 수 있는 것엔 **딱지**. 하나면 a(an) 같은 앞말, 여럿이면 -s.", qs: [
    {"t":"order","ctx":"EP.5, 삼돌이가 혼자 추겠다고 버티며","q":"삼돌이의 대사 '나는 팀이 필요 없어.'를 평서문으로 순서대로 놓으세요","words":["a team","don't","need","I"],"a":"I don't need a team.","why":"team은 하나라서 앞에 a. 하나인 명사는 혼자 서지 못한다."},
    {"t":"order","q":"'나는 개가 한 마리 있어.'를 평서문으로 순서대로 놓으세요","words":["a dog","have","I"],"a":"I have a dog.","why":"한 마리라서 a 딱지. 딱지가 하나 붙은 명사."},
    {"t":"order","q":"'나는 개가 두 마리 있어.'를 평서문으로 순서대로 놓으세요","words":["two dogs","have","I"],"a":"I have two dogs.","why":"두 마리 이상이라 dogs. two가 있어도 s 딱지는 필요하다."},
    {"t":"order","q":"'나는 생각이 하나 있어.'를 평서문으로 순서대로 놓으세요","words":["an idea","have","I"],"a":"I have an idea.","why":"idea는 모음 소리로 시작해서 a가 아니라 an."},
    {"t":"order","q":"'우리는 의자가 두 개 필요해.'를 평서문으로 순서대로 놓으세요","words":["chairs","need","two","We"],"a":"We need two chairs.","why":"여럿이니까 chairs에 s 딱지. 순서는 주어 → 동사 → 목적어."},
    {"t":"order","q":"'엠마는 오렌지를 하나 먹어.'를 평서문으로 순서대로 놓으세요","words":["orange","an","eats","Emma"],"a":"Emma eats an orange.","why":"orange는 모음 소리라서 an 딱지. 딱지는 명사 바로 앞."},
    {"t":"order","q":"'준은 큰 우산을 하나 갖고 있어.'를 평서문으로 순서대로 놓으세요","words":["umbrella","a","big","has","Jun"],"a":"Jun has a big umbrella.","why":"a는 바로 뒤 낱말 big의 소리를 따른다. 동사는 우리말처럼 끝에 안 둔다."}
  ] },
  6: { core: "숫자 **스위치**: 하나면 is + a, 여럿이면 are + s.", qs: [
    {"t":"order","ctx":"EP.6, 민준이 떠나는 삼돌이의 등에 대고","q":"민준의 대사 '이 동아리에는 회원이 세 명 있어.'를 평서문으로 순서대로 놓으세요","words":["three members","This club","has"],"a":"This club has three members.","why":"세 명이라 members에 s. 숫자가 셋이면 여럿 스위치."},
    {"t":"order","q":"'책이 한 권 있어.'를 평서문으로 순서대로 놓으세요","words":["book","a","There is"],"a":"There is a book.","why":"하나라서 is + a book. 스위치가 단수 쪽."},
    {"t":"order","q":"'달걀이 두 개 있어.'를 평서문으로 순서대로 놓으세요","words":["eggs","two","There are"],"a":"There are two eggs.","why":"two가 붙으면 여럿. be 동사는 are, 명사는 eggs."},
    {"t":"order","q":"'아이가 세 명 있어.'를 평서문으로 순서대로 놓으세요","words":["children","three","There are"],"a":"There are three children.","why":"child의 복수는 children. 여럿이니까 are."},
    {"t":"order","q":"'열쇠가 두 개 있어.'를 평서문으로 순서대로 놓으세요","words":["keys","two","There are"],"a":"There are two keys.","why":"여럿 스위치니까 be 동사도 are, 명사도 keys."},
    {"t":"order","q":"'큰 개가 두 마리 있어.'를 평서문으로 순서대로 놓으세요","words":["dogs","big","two","There are"],"a":"There are two big dogs.","why":"숫자 → 꾸밈말 → 명사 순서. 여럿이라 are + dogs."},
    {"t":"order","q":"'남은 사람이 많지 않아.'를 평서문으로 순서대로 놓으세요","words":["left","people","There are","many","not"],"a":"There are not many people left.","why":"people은 여럿이라 are. 「남은 사람」 순서로 left를 앞에 두기 쉽다."}
  ] },
  7: { core: "세는 건 **알갱이**, 못 세는 물은 **그릇**에 담아 센다.", qs: [
    {"t":"order","ctx":"EP.7, 못난이가 민준 옆에 앉아 빈 캔들을 보며","q":"못난이의 대사 '너 커피를 세 캔이나 마셨어.'를 「너」로 시작하는 평서문으로 순서대로 놓으세요","words":["of coffee","three cans","You","drank"],"a":"You drank three cans of coffee.","why":"세는 건 커피가 아니라 그릇(cans). 그래서 three cans of coffee."},
    {"t":"order","q":"'나는 물이 있어.'를 평서문으로 순서대로 놓으세요","words":["water","have","I"],"a":"I have water.","why":"water는 못 세니 a도 s도 없이 그대로 온다."},
    {"t":"order","q":"'나는 사과가 두 개 있어.'를 평서문으로 순서대로 놓으세요","words":["two apples","have","I"],"a":"I have two apples.","why":"apple은 알갱이라 셀 수 있다. 두 개니까 apples."},
    {"t":"order","q":"'우리는 돈이 필요해.'를 평서문으로 순서대로 놓으세요","words":["money","We","need"],"a":"We need money.","why":"money는 못 세는 것. a도 s도 안 붙는다."},
    {"t":"order","q":"'나는 달걀이 두 개 필요해.'를 평서문으로 순서대로 놓으세요","words":["eggs","two","need","I"],"a":"I need two eggs.","why":"달걀은 세는 알갱이. 두 개라서 eggs."},
    {"t":"order","q":"'엠마는 우유 한 잔을 원해.'를 평서문으로 순서대로 놓으세요","words":["a glass","of milk","wants","Emma"],"a":"Emma wants a glass of milk.","why":"milk는 못 세니 그릇을 센다. 그릇이 하나라서 a glass."},
    {"t":"order","q":"'나는 물 두 잔이 필요해.'를 평서문으로 순서대로 놓으세요","words":["of","water","two glasses","need","I"],"a":"I need two glasses of water.","why":"우리말은 「물 두 잔」이라 물이 먼저. 영어는 그릇이 먼저: two glasses of water."}
  ] },
  8: { core: "**자리**를 지키고, **숫자**를 밝히고, he·she·it 뒤 동사에 **s**.", qs: [
    {"t":"order","ctx":"EP.8, 삼돌이가 한참 뒤 픽 웃으며","q":"삼돌이의 대사 '그 애는 그걸 생각해 봐.'를 평서문으로 순서대로 놓으세요","words":["about it","She","thinks"],"a":"She thinks about it.","why":"She는 나·너가 아닌 하나(3인칭 단수). 그래서 동사에 s: thinks."},
    {"t":"order","q":"'그는 피자를 좋아해.'를 평서문으로 순서대로 놓으세요","words":["pizza","likes","He"],"a":"He likes pizza.","why":"He는 3인칭 단수라서 동사에 s: likes."},
    {"t":"order","q":"'그들은 피자를 좋아해.'를 평서문으로 순서대로 놓으세요","words":["like","pizza","They"],"a":"They like pizza.","why":"They는 여럿이라 동사에 s가 없다. like 그대로."},
    {"t":"order","q":"'너는 물이 필요해.'를 평서문으로 순서대로 놓으세요","words":["water","need","You"],"a":"You need water.","why":"You는 한 명이어도 s가 없다. water도 a·s가 없다."},
    {"t":"order","q":"'개가 공원에서 달려.'를 평서문으로 순서대로 놓으세요","words":["the park","runs in","dog","The"],"a":"The dog runs in the park.","why":"The dog는 it으로 바뀐다. 그래서 runs. in the park는 뒤 짐칸."},
    {"t":"order","q":"'내 여동생은 개가 두 마리 있어.'를 평서문으로 순서대로 놓으세요","words":["two dogs","has","sister","My"],"a":"My sister has two dogs.","why":"My sister는 she로 바뀐다. 그래서 have가 haves 아닌 has로 바뀐다."},
    {"t":"order","q":"'그녀는 우유 한 잔을 마셔.'를 평서문으로 순서대로 놓으세요","words":["of","milk","a glass","She","drinks"],"a":"She drinks a glass of milk.","why":"우리말처럼 동사를 끝에 두지 않는다. She 뒤 동사엔 s: drinks."}
  ] },
  9: { core: "be 동사는 뜻이 없는 **빈 컵**. 주어와 상태를 등호처럼 잇는다.", qs: [
    {"t":"order","ctx":"EP.9, 돌아온 삼돌이가 씩 웃으며","q":"삼돌이의 대사 '나 돌아왔어.'를 평서문으로 순서대로 놓으세요","words":["back","I","am"],"a":"I am back.","why":"am은 뜻 없이 I와 back을 잇는 등호. 돌아온 상태를 담았다."},
    {"t":"order","q":"'나는 행복해.'를 평서문으로 순서대로 놓으세요","words":["happy","am","I"],"a":"I am happy.","why":"빈 컵 am이 I와 happy를 잇는다. I = happy."},
    {"t":"order","q":"'그녀는 키가 커.'를 평서문으로 순서대로 놓으세요","words":["tall","is","She"],"a":"She is tall.","why":"is도 뜻 없이 She = tall을 잇는다."},
    {"t":"order","q":"'그는 내 선생님이야.'를 평서문으로 순서대로 놓으세요","words":["my teacher","He","is"],"a":"He is my teacher.","why":"컵에는 상태뿐 아니라 이름(my teacher)도 담긴다."},
    {"t":"order","q":"'그 방은 비어 있어.'를 평서문으로 순서대로 놓으세요","words":["empty","The room","is"],"a":"The room is empty.","why":"방 = 비어 있음. be는 주어와 상태 사이에서 잇는다."},
    {"t":"order","q":"'너는 내 가장 친한 친구야.'를 평서문으로 순서대로 놓으세요","words":["best friend","are","You","my"],"a":"You are my best friend.","why":"You 다음엔 are. You = my best friend로 등호처럼 잇는다."},
    {"t":"order","q":"'네 새 신발은 정말 예뻐.'를 평서문으로 순서대로 놓으세요","words":["very nice","are","Your","new shoes"],"a":"Your new shoes are very nice.","why":"함정: 우리말은 '정말 예뻐'가 끝이라 be를 끝에 두기 쉽다. be는 사이에."}
  ] },
  10: { core: "행동은 **손발**의 일, 상태는 be가 다는 **명찰**. be 뒤에 상태 말이 오면 상태다.", qs: [
    {"t":"order","ctx":"EP.10, 무너진 민준이 애써 버티며","q":"민준의 대사 '나 괜찮아.'를 평서문으로 순서대로 놓으세요","words":["fine","I","am"],"a":"I am fine.","why":"괜찮다는 건 행동이 아니라 명찰(상태). 그런데 손은 떨리고 있다."},
    {"t":"order","q":"'나는 피곤해.'를 평서문으로 순서대로 놓으세요","words":["tired","am","I"],"a":"I am tired.","why":"am tired는 달리는 행동이 아니라 지금 달린 명찰이다."},
    {"t":"order","q":"'그녀는 선생님이야.'를 평서문으로 순서대로 놓으세요","words":["a teacher","She","is"],"a":"She is a teacher.","why":"선생님이라는 명찰도 be가 잇는다."},
    {"t":"order","q":"'그는 체육관에 있어.'를 평서문으로 순서대로 놓으세요","words":["in the gym","He","is"],"a":"He is in the gym.","why":"「~에 있다」도 명찰. 장소가 지금의 상태를 알려 준다."},
    {"t":"order","q":"'그 아이들은 배고파.'를 평서문으로 순서대로 놓으세요","words":["hungry","The kids","are"],"a":"The kids are hungry.","why":"여럿이라 are. 배고픔은 행동이 아니라 상태다."},
    {"t":"order","q":"'내 형은 아주 피곤해.'를 평서문으로 순서대로 놓으세요","words":["very tired","is","brother","My"],"a":"My brother is very tired.","why":"주어(My brother) 바로 뒤에 be, 그 뒤에 명찰(very tired)."},
    {"t":"order","q":"'내 새 선생님은 아주 친절해.'를 평서문으로 순서대로 놓으세요","words":["very kind","is","teacher","My","new"],"a":"My new teacher is very kind.","why":"함정: 우리말은 '친절해'가 끝이라 be를 끝에 두기 쉽다. be는 주어 뒤."}
  ] },
  11: { core: "**좌석 셋**: I는 am, 한 명·하나는 is, You와 여럿은 are.", qs: [
    {"t":"order","ctx":"EP.11, 웃음을 참지 못하면서","q":"삼돌이의 대사 '나 안 웃고 있어.'를 평서문으로 순서대로 놓으세요","words":["laughing","not","I","am"],"a":"I am not laughing.","why":"주어가 I니까 am 자리. not은 be 바로 뒤에 온다."},
    {"t":"order","q":"'그들은 내 사촌이야.'를 평서문으로 순서대로 놓으세요","words":["my cousins","are","They"],"a":"They are my cousins.","why":"여럿(They)이라 are 자리에 앉는다."},
    {"t":"order","q":"'그는 내 남동생이야.'를 평서문으로 순서대로 놓으세요","words":["my brother","is","He"],"a":"He is my brother.","why":"한 명(He)이라 is 자리."},
    {"t":"order","q":"'우리는 준비됐어.'를 평서문으로 순서대로 놓으세요","words":["ready","are","We"],"a":"We are ready.","why":"We도 여럿 자리 are. am은 I 전용석이다."},
    {"t":"order","q":"'미나와 준은 친구야.'를 평서문으로 순서대로 놓으세요","words":["friends","are","Mina and Jun"],"a":"Mina and Jun are friends.","why":"둘이니까 여럿 자리 are. 한 명씩일 때만 is."},
    {"t":"order","q":"'그 영화는 아주 길어.'를 평서문으로 순서대로 놓으세요","words":["very long","is","movie","The"],"a":"The movie is very long.","why":"movie는 하나라서 is 자리."},
    {"t":"order","q":"'내 두 여동생은 아주 키가 커.'를 평서문으로 순서대로 놓으세요","words":["very tall","are","My two","sisters"],"a":"My two sisters are very tall.","why":"함정: sisters는 여럿이라 are. 끝에 be를 두지 말고 주어 바로 뒤에."}
  ] },
  12: { core: "진행형은 **사진 한 장**. be + -ing, 지금 이 순간의 모습.", qs: [
    {"t":"order","ctx":"EP.12, 화이트보드에 쓰던 민준이","q":"민준의 대사 '나는 네 노래를 쓰고 있어.'를 평서문으로 순서대로 놓으세요","words":["your song","writing","I'm"],"a":"I'm writing your song.","why":"be(I'm) + -ing. 쓰는 중인 순간을 사진처럼 붙잡는다."},
    {"t":"order","q":"'나는 춤추고 있어.'를 평서문으로 순서대로 놓으세요","words":["dancing","am","I"],"a":"I am dancing.","why":"am + dancing. 지금 이 순간의 사진 한 장."},
    {"t":"order","q":"'그녀는 노래하고 있어.'를 평서문으로 순서대로 놓으세요","words":["singing","is","She"],"a":"She is singing.","why":"is + singing. 틀(be)과 행동(-ing)이 한 쌍이다."},
    {"t":"order","q":"'그들은 춤추고 있어.'를 평서문으로 순서대로 놓으세요","words":["dancing","are","They"],"a":"They are dancing.","why":"여럿이면 틀이 are로 바뀐다. -ing는 그대로."},
    {"t":"order","q":"'아기가 울고 있어.'를 평서문으로 순서대로 놓으세요","words":["crying","is","The baby"],"a":"The baby is crying.","why":"울고 있는 지금 모습. be 없이 -ing만 쓰면 문장이 안 선다."},
    {"t":"order","q":"'우리는 영어를 공부하고 있어.'를 평서문으로 순서대로 놓으세요","words":["studying English","are","We"],"a":"We are studying English.","why":"We는 are 틀. 그 안에 studying이 들어간다."},
    {"t":"order","q":"'내 여동생은 피아노를 연습하고 있어.'를 평서문으로 순서대로 놓으세요","words":["practicing","the piano","is","sister","My"],"a":"My sister is practicing the piano.","why":"함정: 동사가 끝인 우리말과 달리 be + -ing가 주어 바로 뒤에 온다."}
  ] },
  13: { core: "**결과표**: 누가 했는지보다 지금 어떤 결과인지를 말한다.", qs: [
    {"t":"order","ctx":"EP.13, 삼돌이가 민준을 노려보며","q":"삼돌이의 대사 '내 동작이 빠졌어.'를 평서문으로 순서대로 놓으세요","words":["dropped","My move","is"],"a":"My move is dropped.","why":"뺀 사람이 아니라 빠진 결과를 말한다. be + 과거분사(dropped)."},
    {"t":"order","q":"'창문이 깨져 있어.'를 평서문으로 순서대로 놓으세요","words":["broken","The window","is"],"a":"The window is broken.","why":"부순 사람은 말하지 않고 깨진 결과만 말한다."},
    {"t":"order","q":"'가게가 닫혀 있어.'를 평서문으로 순서대로 놓으세요","words":["is","closed","The shop"],"a":"The shop is closed.","why":"지금 문이 닫혀 있다는 결과. be + closed."},
    {"t":"order","q":"'파일이 저장돼 있어.'를 평서문으로 순서대로 놓으세요","words":["saved","is","The file"],"a":"The file is saved.","why":"누가 저장했든 저장된 결과가 중요하다."},
    {"t":"order","q":"'창문은 깨지지 않았어.'를 평서문으로 순서대로 놓으세요","words":["broken","is","The window","not"],"a":"The window is not broken.","why":"not은 be 바로 뒤에 온다. be + not + 과거분사."},
    {"t":"order","q":"'보고서는 끝나지 않았어.'를 평서문으로 순서대로 놓으세요","words":["finished","The report","not","is"],"a":"The report is not finished.","why":"끝난 결과가 아니라는 말. be + not + 과거분사."},
    {"t":"order","q":"'그 음식은 안 익었어.'를 평서문으로 순서대로 놓으세요","words":["cooked","is","The food","not"],"a":"The food is not cooked.","why":"함정: 우리말은 '안 익었어'로 끝난다. 영어는 be + not + 과거분사 순서."}
  ] },
  14: { core: "be going to = **이미 출발한 발걸음**. 앞으로 일어날 일을 말한다.", qs: [
    {"t":"order","ctx":"EP.14, 삼돌이가 엔딩을 불안해하며","q":"삼돌이의 대사 '엔딩은 실패할 거야!'를 평서문으로 순서대로 놓으세요","words":["fail","is","The ending","going to"],"a":"The ending is going to fail!","why":"is + going to + 동사. 발이 이미 실패 쪽으로 향했다고 느끼는 거다."},
    {"t":"order","q":"'비가 올 거야.'를 평서문으로 순서대로 놓으세요","words":["rain","is","going to","It"],"a":"It is going to rain.","why":"구름이라는 눈앞의 신호로 아는 일. be + going to + 동사."},
    {"t":"order","q":"'아기가 울 것 같아.'를 평서문으로 순서대로 놓으세요","words":["cry","The baby","is","going to"],"a":"The baby is going to cry.","why":"눈앞에 보이는 신호로 아는 일. going to 뒤는 동사 원래 모양."},
    {"t":"order","q":"'나는 노래 안 할 거야.'를 평서문으로 순서대로 놓으세요","words":["sing","not going to","am","I"],"a":"I am not going to sing.","why":"not은 be 바로 뒤에 온다. going to 뒤는 동사 원래 모양."},
    {"t":"order","q":"'그녀는 떠나지 않을 거야.'를 평서문으로 순서대로 놓으세요","words":["leave","She","is","not going to"],"a":"She is not going to leave.","why":"not going to가 be 바로 뒤에 온다. 우리말 '~하지 않을 거야'와 순서가 다르다."},
    {"t":"order","q":"'우리 팀이 이길 거야.'를 평서문으로 순서대로 놓으세요","words":["win","going to","Our","team","is"],"a":"Our team is going to win.","why":"team은 하나라서 is. 그 뒤에 going to + 동사."},
    {"t":"order","q":"'우리 부모님은 내 이모를 방문할 거야.'를 평서문으로 순서대로 놓으세요","words":["visit","my aunt","are","going to","My","parents"],"a":"My parents are going to visit my aunt.","why":"함정: 우리말은 '방문할 거야'가 끝. 영어는 going to를 동사 앞에 둔다."}
  ] },
  15: { core: "과거 be는 **어제 칸**으로 옮긴 be. am·is는 was, are는 were.", qs: [
    {"t":"order","ctx":"EP.15, 민준이 삼돌이에게 인정하며","q":"민준의 대사 '네 말이 맞았어.'를 평서문으로 순서대로 놓으세요","words":["right","You","were"],"a":"You were right.","why":"You는 오늘 are였으니 어제 칸에서는 were."},
    {"t":"order","q":"'나는 집에 있었어.'를 평서문으로 순서대로 놓으세요","words":["at home","was","I"],"a":"I was at home.","why":"I는 오늘 am이었으니 어제 칸에서는 was."},
    {"t":"order","q":"'우리는 식탁에 있었어.'를 평서문으로 순서대로 놓으세요","words":["at the table","were","We"],"a":"We were at the table.","why":"We의 are를 어제 칸으로 옮기면 were."},
    {"t":"order","q":"'그는 가수였어.'를 평서문으로 순서대로 놓으세요","words":["a singer","was","He"],"a":"He was a singer.","why":"He는 is였으니 어제는 was. 그때의 모습을 말한다."},
    {"t":"order","q":"'그녀는 아주 피곤했어.'를 평서문으로 순서대로 놓으세요","words":["very tired","was","She"],"a":"She was very tired.","why":"She는 was. 지금은 어떤지 이 문장은 말하지 않는다."},
    {"t":"order","q":"'우리 부모님은 아주 행복했어.'를 평서문으로 순서대로 놓으세요","words":["very happy","were","parents","My"],"a":"My parents were very happy.","why":"parents는 여럿이라 were. 어제 칸에서도 자리표는 그대로."},
    {"t":"order","q":"'내 두 형제는 아주 키가 컸어.'를 평서문으로 순서대로 놓으세요","words":["very tall","were","brothers","My","two"],"a":"My two brothers were very tall.","why":"함정: brothers가 둘이라 were. 끝에 be를 두지 말고 주어 바로 뒤에."}
  ] },
  16: { core: "be 하나에 다섯 얼굴: 상태·진행·수동·미래·과거. 뒤에 오는 말이나 be의 모양이 정한다.", qs: [
    {"t":"order","ctx":"EP.16, 걸레질을 멈춘 못난이가 노트를 말하며","q":"못난이의 대사 '그것들은 내 목소리야.'를 평서문으로 순서대로 놓으세요","words":["my voice","are","They"],"a":"They are my voice.","why":"상태 얼굴: 여럿(They)이라 are. be가 They와 my voice를 등호처럼 잇는다."},
    {"t":"order","q":"'그는 보고 있어.'를 평서문으로 순서대로 놓으세요","words":["watching","is","He"],"a":"He is watching.","why":"진행 얼굴: be + -ing. 지금 이 순간의 사진 한 장."},
    {"t":"order","q":"'나는 배고파.'를 평서문으로 순서대로 놓으세요","words":["hungry","am","I"],"a":"I am hungry.","why":"상태 얼굴: I는 am. 배고픔은 지금 달린 명찰."},
    {"t":"order","q":"'그녀는 피곤했어.'를 평서문으로 순서대로 놓으세요","words":["tired","was","She"],"a":"She was tired.","why":"과거 얼굴: be의 모양이 어제 칸(was)으로 바뀐다."},
    {"t":"order","q":"'우리는 춤출 거야.'를 평서문으로 순서대로 놓으세요","words":["dance","We","are","going to"],"a":"We are going to dance.","why":"미래 얼굴: be + going to + 동사. We는 are 자리."},
    {"t":"order","q":"'문이 잠겨 있어.'를 평서문으로 순서대로 놓으세요","words":["locked","is","door","The"],"a":"The door is locked.","why":"수동 얼굴: be + 과거분사. 누가 했는지 말고 지금 결과."},
    {"t":"order","q":"'시험은 쉬울 거야.'를 평서문으로 순서대로 놓으세요","words":["easy","going to","is","The test","be"],"a":"The test is going to be easy.","why":"함정: going to 뒤에 be가 한 번 더 온다. 우리말 '식을 거야'처럼 몰지 않는다."}
  ] },
  17: { core: "have는 소유가 아니라 **끈**. 물건·사람·시간·꿈을 나와 잇는다.", qs: [
    {"t":"order","ctx":"EP.17, 삼돌이가 옥상에서 옛날 이야기를 꺼내며","q":"삼돌이의 대사 '나한테도 그런 곳이 있었어.'를 평서문으로 순서대로 놓으세요","words":["a place","had","I"],"a":"I had a place.","why":"I 바로 뒤에 had. 나와 그런 곳이 끈으로 이어져 있었다."},
    {"t":"order","q":"'나는 펜이 있어.'를 평서문으로 순서대로 놓으세요","words":["a pen","have","I"],"a":"I have a pen.","why":"끈 끝에 물건이 매달린다. I 바로 뒤에 have."},
    {"t":"order","q":"'그녀에게는 꿈이 있어.'를 평서문으로 순서대로 놓으세요","words":["a dream","She","has"],"a":"She has a dream.","why":"주어가 She면 have가 has로 바뀐다. 끈은 그대로다."},
    {"t":"order","q":"'나에게는 문제가 있어.'를 평서문으로 순서대로 놓으세요","words":["a problem","I","have"],"a":"I have a problem.","why":"문제도 손에 안 잡히지만 끈으로 나와 이어진다."},
    {"t":"order","q":"'나는 계획이 없어.'를 평서문으로 순서대로 놓으세요","words":["no","plan","I","have"],"a":"I have no plan.","why":"have no는 끈이 없다는 뜻. no는 have 바로 뒤에 온다."},
    {"t":"order","q":"'내 여동생은 새 휴대폰이 있어.'를 평서문으로 순서대로 놓으세요","words":["new phone","a","My sister","has"],"a":"My sister has a new phone.","why":"주어가 My sister(she)라 has. 물건도 끈 끝에 매달린다."},
    {"t":"order","q":"'민준에게는 여동생이 둘 있어.'를 평서문으로 순서대로 놓으세요","words":["sisters","has","two","Minjun","younger"],"a":"Minjun has two younger sisters.","why":"함정. 우리말은 '있다'가 맨 끝. 영어는 has를 주어 바로 뒤에 둔다."}
  ] },
  18: { core: "현재완료는 **다리**. have + 과거분사로 지난 일을 지금과 잇는다.", qs: [
    {"t":"order","ctx":"EP.18, 밤새 쓴 노트를 민준에게 내밀며","q":"못난이의 대사 '나 그거 다 끝냈어.'를 평서문으로 순서대로 놓으세요","words":["it","I've","finished"],"a":"I've finished it.","why":"끝낸 일이 지금도 곁에 있다. I've 뒤에 과거분사 finished."},
    {"t":"order","q":"'나는 밤새 깨어 있었어.'를 평서문으로 순서대로 놓으세요","words":["up all night","I've","stayed"],"a":"I've stayed up all night.","why":"I've = I have. 그 뒤에 과거분사 stayed가 온다."},
    {"t":"order","q":"'나는 그걸 어젯밤에 썼어.'를 평서문으로 순서대로 놓으세요","words":["it last night","wrote","I"],"a":"I wrote it last night.","why":"어젯밤처럼 때가 딱 있으면 과거형. have는 안 쓴다."},
    {"t":"order","q":"'나는 그걸 다 써 놨어.'를 평서문으로 순서대로 놓으세요","words":["have written","it","I"],"a":"I have written it.","why":"다 써서 지금도 곁에 있다. have 뒤에 과거분사 written."},
    {"t":"order","q":"'그들은 집에 가 버렸어.'를 평서문으로 순서대로 놓으세요","words":["gone","They","home","have"],"a":"They have gone home.","why":"have 뒤에 과거분사 gone. 지금 여기 없다는 결과가 남는다."},
    {"t":"order","q":"'그녀는 두리안을 아직 안 먹었어.'를 평서문으로 순서대로 놓으세요","words":["durian","She","not","eaten","has"],"a":"She has not eaten durian.","why":"부정은 has 바로 뒤에 not. 그 뒤에 과거분사 eaten."},
    {"t":"order","q":"'나는 서울에 가 본 적이 없어.'를 평서문으로 순서대로 놓으세요","words":["to Seoul","not","I","been","have"],"a":"I have not been to Seoul.","why":"함정. 우리말은 '적이 없어'가 끝. 영어는 have not been 순서로 잇는다."}
  ] },
  19: { core: "have to는 해야 할 일을 **짐**처럼 멘다. 규칙이 얹어도, 스스로 느껴도.", qs: [
    {"t":"order","ctx":"EP.19, 떠나려던 못난이에게 민준이 말하며","q":"민준의 대사 '너 갈 필요 없어.'를 평서문으로 순서대로 놓으세요","words":["go","have","don't","You","to"],"a":"You don't have to go.","why":"안 해도 된다는 말. don't가 have to 앞에 온다(짐이 없다)."},
    {"t":"order","q":"'나는 가야 해.'를 평서문으로 순서대로 놓으세요","words":["go","I","have to"],"a":"I have to go.","why":"가야 할 일을 짐처럼 메고 있다. have to 뒤에는 동사."},
    {"t":"order","q":"'그는 일해야 해.'를 평서문으로 순서대로 놓으세요","words":["work","He","has to"],"a":"He has to work.","why":"주어가 He면 have to가 has to로 바뀐다."},
    {"t":"order","q":"'나는 이 노래를 끝내야 해.'를 평서문으로 순서대로 놓으세요","words":["finish this song","I","have to"],"a":"I have to finish this song.","why":"꼭 해야 한다고 느끼는 일도 have to. 짐은 안에서도 온다."},
    {"t":"order","q":"'너는 교복을 입어야 해.'를 평서문으로 순서대로 놓으세요","words":["wear a uniform","You","have to"],"a":"You have to wear a uniform.","why":"학교 규칙 같은 밖의 이유도 have to로 말한다."},
    {"t":"order","q":"'내 여동생은 수학을 공부해야 해.'를 평서문으로 순서대로 놓으세요","words":["math","My sister","study","has to"],"a":"My sister has to study math.","why":"주어가 My sister(she)라 has to. 뒤에는 동사 study."},
    {"t":"order","q":"'너는 나를 도울 필요 없어.'를 평서문으로 순서대로 놓으세요","words":["help","have to","me","You","don't"],"a":"You don't have to help me.","why":"함정. 우리말은 '필요 없어'로 부정이 끝. 영어는 don't가 have to 앞."}
  ] },
  20: { core: "have + 명사는 그 명사가 든 **경험 상자**를 연다는 말이다.", qs: [
    {"t":"order","ctx":"EP.20, 넘어진 못난이를 보며 삼돌이가 웃다가","q":"삼돌이의 대사 '우리 좀 쉬자.'를 평서문으로 순서대로 놓으세요","words":["a break","have","Let's"],"a":"Let's have a break.","why":"쉬는 시간이라는 경험 상자를 연다. have + 명사."},
    {"t":"order","q":"'나는 저녁을 먹어.'를 평서문으로 순서대로 놓으세요","words":["dinner","I","have"],"a":"I have dinner.","why":"밥 먹기도 경험 상자. have 뒤에 dinner만 바꾸면 된다."},
    {"t":"order","q":"'나는 샤워를 해.'를 평서문으로 순서대로 놓으세요","words":["a shower","I","have"],"a":"I have a shower.","why":"샤워도 have 뒤에 명사를 놓아 말한다."},
    {"t":"order","q":"'우리 뭐 좀 마시자.'를 평서문으로 순서대로 놓으세요","words":["drink","a","have","Let's"],"a":"Let's have a drink.","why":"마시는 경험 상자를 연다. Let's 뒤에 have."},
    {"t":"order","q":"'그들은 즐거운 시간을 보내.'를 평서문으로 순서대로 놓으세요","words":["good time","They","a","have"],"a":"They have a good time.","why":"즐거운 시간이라는 경험 상자. a를 잊지 않는다."},
    {"t":"order","q":"'그는 긴 수다를 떨어.'를 평서문으로 순서대로 놓으세요","words":["long","a","chat","He","has"],"a":"He has a long chat.","why":"주어가 He라 has. 명사 chat 앞에 a long이 붙는다."},
    {"t":"order","q":"'우리 좋은 시간 보내자.'를 평서문으로 순서대로 놓으세요","words":["time","good","Let's","a","have"],"a":"Let's have a good time.","why":"함정. 우리말은 '보내자'가 끝. 영어는 have가 명사 앞에 온다."}
  ] },
  21: { core: "have는 방 안에 **있는** 것, get은 문턱을 **넘는** 순간이다.", qs: [
    {"t":"order","ctx":"EP.21, 복도에서 삼돌이가 뒤늦게 마음을 전하며","q":"삼돌이의 대사 '나 네 말 알아들었어.'를 평서문으로 순서대로 놓으세요","words":["what you said","I","got"],"a":"I got what you said.","why":"네 말이 문턱을 넘어 내 마음에 들어왔다. get의 과거 got."},
    {"t":"order","q":"'나는 돈을 받았어.'를 평서문으로 순서대로 놓으세요","words":["money","got","I"],"a":"I got money.","why":"돈이 들어온 순간이라 got. have면 원래 있던 돈이다."},
    {"t":"order","q":"'나는 피곤해져.'를 평서문으로 순서대로 놓으세요","words":["tired","I","get"],"a":"I get tired.","why":"피곤하지 않던 몸이 피곤해진다. get + 형용사."},
    {"t":"order","q":"'나는 편지를 받았어.'를 평서문으로 순서대로 놓으세요","words":["letter","a","I","got"],"a":"I got a letter.","why":"없던 편지가 들어왔다. got 뒤에 받은 것이 온다."},
    {"t":"order","q":"'그들은 강아지를 얻었어.'를 평서문으로 순서대로 놓으세요","words":["puppy","a","They","got"],"a":"They got a puppy.","why":"강아지가 그들에게 생긴 순간이라 got."},
    {"t":"order","q":"'우리는 새 선생님이 생겼어.'를 평서문으로 순서대로 놓으세요","words":["new","We","teacher","a","got"],"a":"We got a new teacher.","why":"없던 선생님이 생겼다. 생기는 순간은 get의 과거 got."},
    {"t":"order","q":"'내 여동생은 아주 화가 나.'를 평서문으로 순서대로 놓으세요","words":["very","angry","sister","gets","My"],"a":"My sister gets very angry.","why":"함정. 우리말은 '화가 나'로 동사가 끝. 영어는 gets가 주어 바로 뒤."}
  ] },
  22: { core: "take는 **손 뻗기**. 사람도 일도 무언가를 손으로 집어 갖는다.", qs: [
    {"t":"order","ctx":"EP.22, 동아리실에서 민준이 혼자 정한 일을 밝히며","q":"민준의 대사 '나는 늦은 순서를 잡았어.'를 평서문으로 순서대로 놓으세요","words":["the","late slot","took","I"],"a":"I took the late slot.","why":"손을 뻗어 늦은 순서를 직접 집었다. take의 과거 took."},
    {"t":"order","q":"'나는 버스를 타.'를 평서문으로 순서대로 놓으세요","words":["the bus","take","I"],"a":"I take the bus.","why":"손을 뻗어 버스를 잡아탄다. take는 무언가를 집어 갖는 손."},
    {"t":"order","q":"'시간이 걸려.'를 평서문으로 순서대로 놓으세요","words":["time","takes","It"],"a":"It takes time.","why":"이번엔 일이 주어. 일이 시간을 가져간다. 그래서 걸린다."},
    {"t":"order","q":"'나는 산책할게.'를 평서문으로 순서대로 놓으세요","words":["walk","a","take","I'll"],"a":"I'll take a walk.","why":"산책이라는 행동을 집어 든다. take + 명사."},
    {"t":"order","q":"'한 시간 걸려.'를 평서문으로 순서대로 놓으세요","words":["an","hour","takes","It"],"a":"It takes an hour.","why":"일이 한 시간을 가져간다. 주어가 It이라 takes."},
    {"t":"order","q":"'내 남동생은 버스를 타.'를 평서문으로 순서대로 놓으세요","words":["the","bus","My","takes","brother"],"a":"My brother takes the bus.","why":"주어가 My brother(he)라 takes. 손을 뻗어 버스를 잡아탄다."},
    {"t":"order","q":"'나는 한 시간 걸려.'를 평서문으로 순서대로 놓으세요","words":["me","one","hour","It","takes"],"a":"It takes me one hour.","why":"함정. 우리말은 '나는'으로 시작. 영어는 It이 주어, 사람은 takes 뒤."}
  ] },
  23: { core: "have는 사진, get은 영상, take는 손. 같은 대상도 동사로 그림이 달라진다.", qs: [
    {"t":"order","ctx":"EP.23, 연습 후 거울 앞에서 삼돌이가 못난이에게","q":"삼돌이의 대사 '너는 가사를 가지고 있어.'를 평서문으로 순서대로 놓으세요","words":["words","You","have","the"],"a":"You have the words.","why":"가사는 이미 네 안에 있는 상태. 상태는 have."},
    {"t":"order","q":"'나는 일자리를 얻었어.'를 평서문으로 순서대로 놓으세요","words":["a job","got","I"],"a":"I got a job.","why":"일자리가 내게 오는 과정이라 got."},
    {"t":"order","q":"'나는 그 일자리를 받아들였어.'를 평서문으로 순서대로 놓으세요","words":["the job","took","I"],"a":"I took the job.","why":"손을 뻗어 그 일을 집어 왔다. 행동이라 took."},
    {"t":"order","q":"'나는 일자리가 있어.'를 평서문으로 순서대로 놓으세요","words":["a","job","have","I"],"a":"I have a job.","why":"지금 일자리가 있는 상태. 상태는 have."},
    {"t":"order","q":"'그녀는 버스를 타.'를 평서문으로 순서대로 놓으세요","words":["the","bus","She","takes"],"a":"She takes the bus.","why":"손 뻗는 행동이라 take. 주어가 She라 takes."},
    {"t":"order","q":"'그는 새 휴대폰을 얻었어.'를 평서문으로 순서대로 놓으세요","words":["new","phone","a","He","got"],"a":"He got a new phone.","why":"새 폰이 그에게 오는 과정이라 got."},
    {"t":"order","q":"'삼촌은 새 일자리를 받아들였어.'를 평서문으로 순서대로 놓으세요","words":["new","job","My uncle","took","a"],"a":"My uncle took a new job.","why":"함정. 우리말은 '받아들였어'가 끝. 영어는 took이 주어 바로 뒤."}
  ] },
  24: { core: "have는 이어진 상태, get은 오는 변화, take는 내가 집는 행동.", qs: [
    {"t":"order","ctx":"EP.24, 공연 전날 밤 아무도 집에 안 가고","q":"못난이의 대사 '우리 시간 있어.'를 평서문으로 순서대로 놓으세요","words":["time","We","have"],"a":"We have time.","why":"시간이 우리에게 이어져 있다. 끈으로 이은 것은 have."},
    {"t":"order","q":"'나는 배가 고파져.'를 평서문으로 순서대로 놓으세요","words":["hungry","I","get"],"a":"I get hungry.","why":"배고프지 않던 몸이 문턱을 넘는다. get + 형용사."},
    {"t":"order","q":"'나는 사진을 찍어.'를 평서문으로 순서대로 놓으세요","words":["a picture","take","I"],"a":"I take a picture.","why":"손을 뻗어 사진을 내 쪽으로 가져온다. take + 명사."},
    {"t":"order","q":"'나는 서울에 가 본 적이 있어.'를 평서문으로 순서대로 놓으세요","words":["to Seoul","been","I","have"],"a":"I have been to Seoul.","why":"지난 일이 다리를 건너 지금 내게 있다. have + 과거분사."},
    {"t":"order","q":"'우리는 쉬었어.'를 평서문으로 순서대로 놓으세요","words":["took","We","a","break"],"a":"We took a break.","why":"쉬는 시간을 손으로 집어 왔다. take의 과거 took."},
    {"t":"order","q":"'그녀는 잠을 자야 해.'를 평서문으로 순서대로 놓으세요","words":["some sleep","She","get","has to"],"a":"She has to get some sleep.","why":"짐(has to)을 메고 있고, 잠은 내게 들어와야 한다(get)."},
    {"t":"order","q":"'우리 엄마는 버스를 타야 해.'를 평서문으로 순서대로 놓으세요","words":["take","a","bus","My mom","has to"],"a":"My mom has to take a bus.","why":"함정. 우리말은 '타야 해'가 끝. 영어는 has to를 앞에 둔다."}
  ] },
  25: { core: "to는 **화살표**. 몸도 물건도 마음도 도착점으로 간다.", qs: [
    {"t":"order","ctx":"EP.25, 삼돌이가 사라진 아침, 못난이가 벌떡 일어나며","q":"못난이의 대사 '나는 그녀를 찾아야 해.'를 평서문으로 순서대로 놓으세요","words":["find","her","I","to","need"],"a":"I need to find her.","why":"찾는 일은 아직 안 했다. 마음이 먼저 to 화살표를 탔다."},
    {"t":"order","q":"'나는 자고 싶어.'를 평서문으로 순서대로 놓으세요","words":["sleep","want","to","I"],"a":"I want to sleep.","why":"마음이 '자기'로 먼저 간다. to 뒤에 아직 안 한 행동이 온다."},
    {"t":"order","q":"'그는 나에게 왔어.'를 He로 시작하는 평서문으로 순서대로 놓으세요","words":["me","to","He","came"],"a":"He came to me.","why":"몸이 움직여 to 뒤의 사람에게 도착한다. 화살촉 끝은 me."},
    {"t":"order","q":"'나는 그것을 엄마께 보낼 거야.'를 평서문으로 순서대로 놓으세요","words":["my mom","I'll","to","it","send"],"a":"I'll send it to my mom.","why":"카드가 날아가 엄마에게 도착한다. 도착점이 to 뒤에 온다."},
    {"t":"order","q":"'그녀는 공원으로 걸어가.'를 평서문으로 순서대로 놓으세요","words":["walks","the","She","park","to"],"a":"She walks to the park.","why":"몸이 화살표를 따라 공원에 도착한다. to 바로 뒤가 도착점."},
    {"t":"order","q":"'그는 나에게 인사해.'를 He로 시작하는 평서문으로 순서대로 놓으세요","words":["hello","me","says","He","to"],"a":"He says hello to me.","why":"인사말이 날아가 me에게 도착한다. 말도 화살표를 탄다."},
    {"t":"order","q":"'그녀는 너에게 말하고 싶어 해.'를 평서문으로 순서대로 놓으세요","words":["you","talk to","She","to","wants"],"a":"She wants to talk to you.","why":"함정: 우리말은 '너에게'가 먼저지만 영어는 talk to you로 to + 사람이 뒤."}
  ] },
  26: { core: "to는 아직 안 한 일로 가는 화살표, -ing는 이미 한 일 돌아보기.", qs: [
    {"t":"order","ctx":"EP.26, 옥상에서 삼돌이가 못난이에게","q":"삼돌이의 대사 '작별 인사하러 올라왔어.'를 I로 시작하는 평서문으로 순서대로 놓으세요","words":["goodbye","came up","I","say","to"],"a":"I came up to say goodbye.","why":"인사는 아직 안 했다. to가 앞으로 할 행동을 가리킨다."},
    {"t":"order","q":"'나는 그녀를 만난 게 기억나.'를 평서문으로 순서대로 놓으세요","words":["her","meeting","I","remember"],"a":"I remember meeting her.","why":"이미 만난 일이라 -ing. her를 앞에 두면 뜻이 달라진다."},
    {"t":"order","q":"'나는 그걸 잠근 게 기억나.'를 평서문으로 순서대로 놓으세요","words":["locking","remember","it","I"],"a":"I remember locking it.","why":"이미 잠근 일이라 -ing. 뒤를 돌아보는 그림이다."},
    {"t":"order","q":"'나는 그걸 잠그는 걸 잊지 않을게.'를 평서문으로 순서대로 놓으세요","words":["lock","I'll","it","to","remember"],"a":"I'll remember to lock it.","why":"잠그는 건 앞으로 할 일. to 화살표가 앞으로 간다."},
    {"t":"order","q":"'우리는 부산에 가기로 계획해.'를 평서문으로 순서대로 놓으세요","words":["visit","plan","We","Busan","to"],"a":"We plan to visit Busan.","why":"계획한 행동은 아직 안 했다. to 뒤에 동사 원래 모양."},
    {"t":"order","q":"'그는 그녀에게 전화하는 걸 잊었어.'를 평서문으로 순서대로 놓으세요","words":["call","forgot","He","her","to"],"a":"He forgot to call her.","why":"해야 할 앞일을 못 했다. forgot to + 동사가 그 그림이다."},
    {"t":"order","q":"'내 여동생은 영어를 배우고 싶어 해.'를 평서문으로 순서대로 놓으세요","words":["English","to","My","wants","sister","learn"],"a":"My sister wants to learn English.","why":"함정: 우리말은 '영어를'이 앞이지만 영어는 to learn 뒤에 English."}
  ] },
  27: { core: "for는 **마음의 방향**. 마음이 향한 사람이나 이유 앞에 온다.", qs: [
    {"t":"order","ctx":"EP.27, 복도에서 삼돌이가 민준에게","q":"삼돌이의 대사 '기다려 줘서 고마워.'를 평서문으로 순서대로 놓으세요","words":["waiting","Thanks","for"],"a":"Thanks for waiting.","why":"고마운 마음이 '기다려 준 일'을 향한다. for 뒤가 이유."},
    {"t":"order","q":"'이건 너를 위한 거야.'를 평서문으로 순서대로 놓으세요","words":["you","for","It's"],"a":"It's for you.","why":"마음이 you를 향한다. for 뒤에 향한 사람이 온다."},
    {"t":"order","q":"'그건 아빠를 위한 거야.'를 평서문으로 순서대로 놓으세요","words":["dad","my","It's","for"],"a":"It's for my dad.","why":"케이크를 받을 아빠 쪽으로 마음이 향한다."},
    {"t":"order","q":"'케이크 고마워요.'를 평서문으로 순서대로 놓으세요","words":["cake","the","Thank","for","you"],"a":"Thank you for the cake.","why":"고마운 마음이 케이크를 향한다. for 뒤가 고마운 이유."},
    {"t":"order","q":"'나는 내 동생을 기다리고 있어.'를 평서문으로 순서대로 놓으세요","words":["sister","waiting","I'm","my","for"],"a":"I'm waiting for my sister.","why":"몸은 여기 있어도 마음은 동생을 향한다. 기다림도 for."},
    {"t":"order","q":"'그 표는 그를 위한 거야.'를 평서문으로 순서대로 놓으세요","words":["him","ticket","is","The","for"],"a":"The ticket is for him.","why":"표를 받을 사람 쪽으로 마음이 향한다."},
    {"t":"order","q":"'그 케이크는 누구를 위한 거야?'를 for를 문장 끝에 두는 일상 말투의 질문으로 순서대로 놓으세요","words":["for","cake","Who","the","is"],"a":"Who is the cake for?","why":"함정: 우리말은 '누구를 위한'이지만 영어는 for가 문장 끝에 남는다."}
  ] },
  28: { core: "in은 **테두리**. 공간·때·상황, 테두리 안이면 in이다.", qs: [
    {"t":"order","ctx":"EP.28, 무대 직전 셋이 손을 포개고","q":"민준의 대사 '우리 이 일 함께 하는 거야.'를 평서문으로 순서대로 놓으세요","words":["in","this together","We're"],"a":"We're in this together.","why":"셋이 같은 테두리 안에 들어와 있다. in + 그 상황."},
    {"t":"order","q":"'그는 수업 중이야.'를 평서문으로 순서대로 놓으세요","words":["class","in","He's"],"a":"He's in class.","why":"수업이라는 테두리 안에 들어 있다."},
    {"t":"order","q":"'그건 네 가방 안에 있어.'를 평서문으로 순서대로 놓으세요","words":["bag","your","It's","in"],"a":"It's in your bag.","why":"가방이라는 눈에 보이는 테두리 안이다."},
    {"t":"order","q":"'나는 서두르는 중이야.'를 평서문으로 순서대로 놓으세요","words":["hurry","in","I'm","a"],"a":"I'm in a hurry.","why":"서두름이라는 상황 테두리 안에 들어 있다."},
    {"t":"order","q":"'파티는 저녁에 있어.'를 평서문으로 순서대로 놓으세요","words":["the evening","is","The","party","in"],"a":"The party is in the evening.","why":"저녁이라는 시간 테두리 안에 파티가 들어 있다."},
    {"t":"order","q":"'모두가 방 안에 있어.'를 평서문으로 순서대로 놓으세요","words":["room","in","the","is","Everyone"],"a":"Everyone is in the room.","why":"방이라는 테두리 안에 모두가 들어 있다."},
    {"t":"order","q":"'내 남동생은 음악에 관심이 있어.'를 평서문으로 순서대로 놓으세요","words":["music","in","brother","interested","My","is"],"a":"My brother is interested in music.","why":"함정: 우리말은 '음악에'지만 영어는 interested 뒤에 in + 음악."}
  ] },
  29: { core: "at은 **핀 하나**. 장소·시각·눈길을 딱 한 점에 꽂는다.", qs: [
    {"t":"order","ctx":"EP.29, 삐끗한 민준이 굳은 채 속으로","q":"민준의 속말 '모두가 나를 보고 있어.'를 평서문으로 순서대로 놓으세요","words":["at","looking","is","Everyone","me"],"a":"Everyone is looking at me.","why":"모든 눈길이 민준이라는 한 점에 꽂혔다. 눈길도 at."},
    {"t":"order","q":"'그는 집에 있어.'를 평서문으로 순서대로 놓으세요","words":["home","at","He's"],"a":"He's at home.","why":"집이라는 한 점에 있다. 장소를 콕 찍었다."},
    {"t":"order","q":"'나는 정문에 있어.'를 평서문으로 순서대로 놓으세요","words":["gate","the","I'm","at"],"a":"I'm at the gate.","why":"정문이라는 정확한 한 점에 핀을 꽂았다."},
    {"t":"order","q":"'나는 그 가수를 보고 있어.'를 평서문으로 순서대로 놓으세요","words":["singer","at","the","looking","I'm"],"a":"I'm looking at the singer.","why":"눈길이 가수 한 사람에게 꽂힌다. 초점 하나가 at."},
    {"t":"order","q":"'그녀는 노래를 잘해.'를 평서문으로 순서대로 놓으세요","words":["singing","at","She","good","is"],"a":"She is good at singing.","why":"잘하는 점 하나를 콕 찍는다. good at + 분야."},
    {"t":"order","q":"'우리는 버스 정류장에 있어.'를 평서문으로 순서대로 놓으세요","words":["bus stop","the","We","at","are"],"a":"We are at the bus stop.","why":"정류장이라는 정확한 한 점. 장소도 핀 하나."},
    {"t":"order","q":"'그들은 내 농담에 웃었어.'를 평서문으로 순서대로 놓으세요","words":["joke","laughed","my","at","They"],"a":"They laughed at my joke.","why":"함정: 우리말은 '농담에'라 at이 안 보이지만 영어는 laughed at."}
  ] },
  30: { core: "on은 **접촉**. 벽에도 활동에도 딱 붙어 있으면 on이다.", qs: [
    {"t":"order","ctx":"EP.30, 못난이가 눈빛을 주고받고 백업하며","q":"못난이의 대사 '나는 박자를 타고 있어.'를 평서문으로 순서대로 놓으세요","words":["beat","I'm","on","the"],"a":"I'm on the beat.","why":"박자에 딱 붙어 있다는 뜻. 활동·상태에 붙으면 on."},
    {"t":"order","q":"'그건 금요일이야.'를 평서문으로 순서대로 놓으세요","words":["Friday","on","It's"],"a":"It's on Friday.","why":"금요일이라는 날에 딱 붙어 있다."},
    {"t":"order","q":"'그건 벽에 붙어 있어.'를 평서문으로 순서대로 놓으세요","words":["wall","the","It's","on"],"a":"It's on the wall.","why":"벽에 닿아 붙어 있다. 위가 아니라 접촉이다."},
    {"t":"order","q":"'나는 다이어트 중이야.'를 평서문으로 순서대로 놓으세요","words":["diet","on","a","I'm"],"a":"I'm on a diet.","why":"다이어트라는 활동에 붙어 있다. 상태도 접촉."},
    {"t":"order","q":"'그녀는 여행 중이야.'를 평서문으로 순서대로 놓으세요","words":["trip","on","is","She","a"],"a":"She is on a trip.","why":"여행이라는 활동에 딱 붙어 있다."},
    {"t":"order","q":"'그 공연은 금요일이야.'를 평서문으로 순서대로 놓으세요","words":["Friday","show","The","on","is"],"a":"The show is on Friday.","why":"달력의 금요일에 공연이 딱 붙어 있다."},
    {"t":"order","q":"'컵은 탁자 위에 있어.'를 The cup으로 시작하는 평서문으로 순서대로 놓으세요","words":["the table","The","is","cup","on"],"a":"The cup is on the table.","why":"함정: 우리말 '탁자 위에'는 뒤에 붙지만 영어 on은 명사 앞. 닿아 있어서 on."}
  ] },
  31: { core: "of는 머릿속 관계, off는 붙은 게 떨어짐. 둘 다 '떨어져 나옴'.", qs: [
    {"t":"order","ctx":"EP.31, 삼돌이가 남는다고 밝힌 뒤 못난이가 코를 훌쩍이며","q":"못난이의 대사 '나는 네가 자랑스러워.'를 평서문으로 순서대로 놓으세요","words":["of","proud","you","I'm"],"a":"I'm proud of you.","why":"자랑스러운 마음이 you에게서 나온다. 머릿속 관계는 of."},
    {"t":"order","q":"'뚜껑이 벗겨져 있어.'를 평서문으로 순서대로 놓으세요","words":["off","lid","is","The"],"a":"The lid is off.","why":"뚜껑이 붙어 있던 자리에서 떨어져 있다. 떨어진 상태는 off."},
    {"t":"order","q":"'나는 자전거에서 떨어졌어.'를 평서문으로 순서대로 놓으세요","words":["bike","fell","my","off","I"],"a":"I fell off my bike.","why":"자전거에 붙어 있던 몸이 실제로 떨어졌다. 몸의 동작은 off."},
    {"t":"order","q":"'그건 차 한 잔이야.'를 평서문으로 순서대로 놓으세요","words":["tea","of","a","It's","cup"],"a":"It's a cup of tea.","why":"차라는 큰 것에서 나온 한 잔. 머릿속 관계라 of."},
    {"t":"order","q":"'그녀는 담에서 뛰어내렸어.'를 평서문으로 순서대로 놓으세요","words":["wall","jumped","She","off","the"],"a":"She jumped off the wall.","why":"담에 붙어 있던 몸이 떨어져 나왔다. 몸의 동작이라 off."},
    {"t":"order","q":"'그는 내 친구들 중 한 명이야.'를 평서문으로 순서대로 놓으세요","words":["mine","friend","of","He","a","is"],"a":"He is a friend of mine.","why":"'내 친구들'에서 나온 한 명. 머릿속 관계라 of."},
    {"t":"order","q":"'그녀는 우리 팀의 주장이야.'를 평서문으로 순서대로 놓으세요","words":["team","captain","of","She","the","our","is"],"a":"She is the captain of our team.","why":"함정: 우리말은 '우리 팀의 주장'이지만 영어는 the captain of our team."}
  ] },
  32: { core: "전치사는 단어가 아니라 **그림**이다. 그림만 고르면 된다.", qs: [
    {"t":"order","ctx":"EP.32, 편의점 앞 계단에서 못난이가 캔을 들고","q":"못난이의 대사 '우리는 같은 팀이야.'를 평서문으로 순서대로 놓으세요","words":["same","team","the","We're","in"],"a":"We're in the same team.","why":"같은 팀이라는 테두리 안에 있다. 테두리면 in. 그림만 고르면 된다."},
    {"t":"order","q":"'나는 수영하고 싶어.'를 평서문으로 순서대로 놓으세요","words":["swim","I","to","want"],"a":"I want to swim.","why":"'수영'이라는 앞일을 향해 가는 화살표. to 뒤에 동사가 온다."},
    {"t":"order","q":"'그건 선반 위에 있어.'를 평서문으로 순서대로 놓으세요","words":["shelf","the","on","It's"],"a":"It's on the shelf.","why":"선반에 닿아 있다. 접촉이면 on."},
    {"t":"order","q":"'이 선물은 그녀를 위한 거야.'를 평서문으로 순서대로 놓으세요","words":["her","gift","is","This","for"],"a":"This gift is for her.","why":"마음이 그녀를 향한다. 마음의 방향은 for."},
    {"t":"order","q":"'그녀는 부엌에 있어.'를 평서문으로 순서대로 놓으세요","words":["kitchen","in","She","the","is"],"a":"She is in the kitchen.","why":"부엌이라는 테두리 안에 있다. 테두리는 in."},
    {"t":"order","q":"'그녀는 체스를 잘해.'를 평서문으로 순서대로 놓으세요","words":["chess","at","good","is","She"],"a":"She is good at chess.","why":"잘하는 점 하나를 콕 찍는다. 한 점은 at."},
    {"t":"order","q":"'그녀는 버스를 기다리고 있어.'를 평서문으로 순서대로 놓으세요","words":["bus","for","waiting","the","She","is"],"a":"She is waiting for the bus.","why":"함정: 우리말은 '버스를'이라 for가 안 보이지만 영어는 waiting for."}
  ] },
  33: { core: "with = 나한테 딱 붙어서 함께. 사람이든 도구든 붙어 있으면 with.", qs: [
    {"t": "scene", "ctx": "EP.33, 종탑 아래 이른 아침", "q": "도윤: Okay. I'm coming ______ my camera.", "opts": ["with", "by", "from", "about"], "a": "with", "why": "카메라를 몸에 붙여서 같이 간다. 붙어서 함께 = with."},
    {"t": "choice", "q": "with의 그림은?", "opts": ["화살표", "붙어서 함께", "한 점", "경계 안"], "a": "붙어서 함께"},
    {"t": "choice", "q": "`I write ______ a pencil.` 빈칸은?", "opts": ["with", "from", "at", "of"], "a": "with", "why": "연필이 손에 붙어서 같이 움직인다."},
    {"t": "order", "words": ["with", "me", "Come"], "q": "단어를 순서대로 놓으세요", "a": "Come with me."},
    {"t": "order", "words": ["a pencil", "with", "write", "I"], "q": "단어를 순서대로 놓으세요", "a": "I write with a pencil."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["school", "with", "I", "my friend", "go to"], "a": "I go to school with my friend."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a red hat", "with", "girl", "The"], "a": "The girl with a red hat"},
  ] },
  34: { core: "by = 바로 곁. 곁에 있으니 옆 자리도, 방법도, 만든 사람도, 시한까지도 된다.", qs: [
    {"t": "scene", "ctx": "EP.34, 관리실 창가에서", "q": "강 할아버지: I sat ______ the window all night.", "opts": ["by", "from", "into", "about"], "a": "by", "why": "창문 바로 곁에 앉았다. 곁 = by."},
    {"t": "choice", "q": "`Come back ______ six.` (6시까지 돌아와)", "opts": ["by", "with", "from", "of"], "a": "by", "why": "6시라는 시각 곁까지 다가오면 된다. 늦어도 그때까지."},
    {"t": "choice", "q": "`This song was written ______ Mina.` (이 노래는 미나가 썼어)", "opts": ["by", "on", "in", "off"], "a": "by", "why": "노래 곁에 있는 사람, 곧 만든 사람이다."},
    {"t": "order", "words": ["by", "sits", "She", "the window"], "q": "단어를 순서대로 놓으세요", "a": "She sits by the window."},
    {"t": "order", "words": ["by", "train", "went", "there", "We"], "q": "단어를 순서대로 놓으세요", "a": "We went there by train."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["it", "by", "did", "myself", "I"], "a": "I did it by myself."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["six", "back", "by", "Come"], "a": "Come back by six."},
  ] },
  35: { core: "from = 화살표의 꼬리, 출발한 곳. to가 머리라면 from은 꼬리.", qs: [
    {"t": "scene", "ctx": "EP.35, 학교 뒷담장에서 소이를 만나", "q": "도윤: Where are you ______?\n소이: Busan. I came ______ Busan last week.", "opts": ["from / from", "to / to", "for / from", "at / of"], "a": "from / from", "why": "어디서 출발했는지 묻고 답한다. 꼬리 = from."},
    {"t": "choice", "q": "화살표의 꼬리, 출발한 곳을 가리키는 전치사는?", "opts": ["to", "from", "at", "in"], "a": "from"},
    {"t": "choice", "q": "`The gift is ______ my mom.` (엄마가 준 선물이야)", "opts": ["from", "to", "at", "in"], "a": "from", "why": "엄마 손에서 출발한 선물이다."},
    {"t": "order", "words": ["from", "I'm", "Korea"], "q": "단어를 순서대로 놓으세요", "a": "I'm from Korea."},
    {"t": "order", "words": ["cows", "from", "comes", "Milk"], "q": "단어를 순서대로 놓으세요", "a": "Milk comes from cows."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the fire", "from", "away", "Stay"], "a": "Stay away from the fire."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["from", "tower", "the", "fell", "It"], "a": "It fell from the tower."},
  ] },
  36: { core: "at은 정확한 한 점, about은 그 둘레를 빙 돈다. 그래서 '대략'과 '~에 대해'가 된다.", qs: [
    {"t": "scene", "ctx": "EP.36, 빈 교실에서 단서를 정리하며", "q": "하늘: What do you know ______ the bell?\n소이: There's an old story ______ it.", "opts": ["about / about", "at / on", "for / about", "to / of"], "a": "about / about", "why": "종 둘레를 맴도는 이야기다. 둘레 = about."},
    {"t": "choice", "q": "`It's ______ three o'clock.` (대략 3시쯤이야)", "opts": ["about", "in", "for", "of"], "a": "about", "why": "3시 한 점이 아니라 그 둘레다."},
    {"t": "choice", "q": "at과 about의 차이는?", "opts": ["at은 한 점, about은 둘레", "at은 둘레, about은 한 점", "둘 다 한 점", "둘 다 둘레"], "a": "at은 한 점, about은 둘레"},
    {"t": "order", "words": ["about", "talk", "Let's", "the plan"], "q": "단어를 순서대로 놓으세요", "a": "Let's talk about the plan."},
    {"t": "order", "words": ["a dog", "is", "book", "about", "This"], "q": "단어를 순서대로 놓으세요", "a": "This book is about a dog."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["about", "you", "are", "thinking", "What"], "a": "What are you thinking about?"},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["students", "twenty", "came", "About"], "a": "About twenty students came."},
  ] },
  37: { core: "over = 떨어져서 위로 넘는다, under = 그 밑에. on은 닿아 있고 over는 떨어져 있다.", qs: [
    {"t": "scene", "ctx": "EP.37, 뒷문 밖 울타리 앞", "q": "하늘: Then we go ______ the fence.\n도윤: There's something ______ this stone.", "hint": "울타리는 넘어가고, 돌은 밑을 들여다본다", "opts": ["over / under", "under / over", "on / in", "at / by"], "a": "over / under", "why": "울타리 위로 넘고, 돌 아래를 본다. 위 = over, 아래 = under."},
    {"t": "choice", "q": "`A plane flew ______ the house.` (닿지 않고 집 위를 날았다)", "opts": ["over", "on", "under", "into"], "a": "over", "why": "닿아 있으면 on, 떨어져서 위로 지나가면 over."},
    {"t": "choice", "q": "`The cat is under the table.`의 뜻은?", "opts": ["고양이가 식탁 위에 있다", "고양이가 식탁 밑에 있다", "고양이가 식탁 옆에 있다", "고양이가 식탁 안에 있다"], "a": "고양이가 식탁 밑에 있다"},
    {"t": "order", "words": ["over", "fence", "Jump", "the"], "q": "단어를 순서대로 놓으세요", "a": "Jump over the fence."},
    {"t": "order", "words": ["under", "cat", "is", "The", "the table"], "q": "단어를 순서대로 놓으세요", "a": "The cat is under the table."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["over", "flew", "A", "plane", "the house"], "a": "A plane flew over the house."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["under", "something", "There's", "this", "stone"], "a": "There's something under this stone."},
  ] },
  38: { core: "in은 안에 가만히 있는 것. into는 안으로 들어가는 화살표, out of는 밖으로 나오는 화살표.", qs: [
    {"t": "scene", "ctx": "EP.38, 낡은 창고에서", "q": "하늘: We're going ______ the dark.\n도윤: Someone just ran ______ the storeroom!", "hint": "어둠 속으로 들어가고, 창고 밖으로 뛰어나갔다", "opts": ["into / out of", "out of / into", "in / on", "from / to"], "a": "into / out of", "why": "어둠 속으로 들어가고, 창고 밖으로 뛰어나갔다."},
    {"t": "choice", "q": "`Water turned ______ ice.` (물이 얼음으로 변했다)", "opts": ["into", "in", "at", "on"], "a": "into", "why": "물이라는 경계를 나와 얼음이라는 경계 안으로 들어갔다."},
    {"t": "choice", "q": "in과 into의 차이는?", "opts": ["in은 안에 있음, into는 안으로 들어감", "in은 밖, into는 안", "둘은 똑같다", "in은 움직임, into는 멈춤"], "a": "in은 안에 있음, into는 안으로 들어감"},
    {"t": "order", "words": ["into", "He", "room", "walked", "the"], "q": "단어를 순서대로 놓으세요", "a": "He walked into the room."},
    {"t": "order", "words": ["out of", "Get", "car", "the"], "q": "단어를 순서대로 놓으세요", "a": "Get out of the car."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["out of", "money", "I", "ran"], "a": "I ran out of money."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["pool", "jumped", "the", "into", "She"], "a": "She jumped into the pool."},
  ] },
  39: { core: "up은 위로 가는 화살표, down은 아래로 가는 화살표. 높이뿐 아니라 숫자와 마음의 오르내림도.", qs: [
    {"t": "scene", "ctx": "EP.39, 종탑 나선 계단에서", "q": "하늘: Come on! ______ the stairs!\n도윤: Look. Someone is walking ______ the hill.", "hint": "계단은 올라가고, 언덕은 내려간다", "opts": ["Up / down", "Down / up", "In / on", "Over / under"], "a": "Up / down", "why": "계단은 위로 올라가고, 언덕은 아래로 내려간다."},
    {"t": "choice", "q": "`Turn ______ the volume.` (볼륨을 키워)", "opts": ["up", "down", "off", "at"], "a": "up", "why": "숫자가 위로 올라가니 up."},
    {"t": "choice", "q": "`Calm ______.` (진정해)", "opts": ["down", "up", "over", "into"], "a": "down", "why": "들뜬 마음이 아래로 가라앉는다."},
    {"t": "order", "words": ["stairs", "Go", "the", "up"], "q": "단어를 순서대로 놓으세요", "a": "Go up the stairs."},
    {"t": "order", "words": ["hill", "the", "Walk", "down"], "q": "단어를 순서대로 놓으세요", "a": "Walk down the hill."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["stairs", "the", "down", "Come"], "a": "Come down the stairs."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the hill", "is", "walking", "Someone", "down"], "a": "Someone is walking down the hill."},
  ] },
  40: { core: "전치사는 그림이다. with 붙어서 함께 · by 곁 · from 꼬리 · about 둘레 · over 위 · under 밑 · into 안으로 · out of 밖으로 · up 위로 · down 아래로.", qs: [
    {"t": "scene", "ctx": "EP.40, 종탑 아래 새벽에 단서를 정리하며", "q": "하늘: A truck ______ the gate. A key ______ the stone. A lantern ______ the hill.", "opts": ["by / under / down", "with / over / up", "from / into / out of", "about / at / on"], "a": "by / under / down", "why": "문 곁에 트럭, 돌 밑에 열쇠, 언덕 아래로 내려가는 등불."},
    {"t": "choice", "q": "`The letter came ______ my grandfather.` (할아버지에게서 왔다)", "opts": ["from", "by", "over", "up"], "a": "from", "why": "할아버지 손에서 출발했다. 꼬리 = from."},
    {"t": "choice", "q": "그림이 잘못 짝지어진 것은?", "opts": ["with = 붙어서 함께", "from = 화살표의 꼬리", "about = 정확한 한 점", "into = 안으로 들어가는 화살표"], "a": "about = 정확한 한 점", "why": "about은 한 점의 둘레. 정확한 한 점은 at이다."},
    {"t": "order", "words": ["from", "This", "my grandfather", "is"], "q": "단어를 순서대로 놓으세요", "a": "This is from my grandfather."},
    {"t": "order", "words": ["a key", "under", "There's", "the stone"], "q": "단어를 순서대로 놓으세요", "a": "There's a key under the stone."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["ran", "the storeroom", "Someone", "out of"], "a": "Someone ran out of the storeroom."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["about", "story", "an old", "There's", "the bell"], "a": "There's an old story about the bell."},
  ] },
  41: { core: "through = 한쪽으로 들어가서 반대쪽으로 나오는 터널. into는 들어가서 끝나고, through는 빠져나간다.", qs: [
    {"t": "scene", "ctx": "EP.41, 안개 낀 어시장에서", "q": "도윤: I can't see ______ this fog.", "opts": ["through", "by", "for", "about"], "a": "through", "why": "안개를 뚫고 반대쪽까지 보려는데 안 보인다. 뚫고 지나가는 시선 = through."},
    {"t": "choice", "q": "`The train goes ______ a tunnel.` (기차가 터널을 통과한다)", "opts": ["through", "at", "of", "off"], "a": "through", "why": "한쪽으로 들어가서 반대쪽으로 나온다."},
    {"t": "choice", "q": "into와 through의 차이는?", "opts": ["into는 들어가서 끝나고, through는 반대쪽으로 나온다", "into는 위로 넘고, through는 밑으로 간다", "둘은 똑같은 뜻이다", "into는 나오는 것이고, through는 들어가는 것이다"], "a": "into는 들어가서 끝나고, through는 반대쪽으로 나온다"},
    {"t": "order", "words": ["through", "We", "the market", "walked"], "q": "단어를 순서대로 놓으세요", "a": "We walked through the market."},
    {"t": "order", "words": ["looked", "She", "the window", "through"], "q": "단어를 순서대로 놓으세요", "a": "She looked through the window."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the night", "through", "talked", "We"], "a": "We talked through the night."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["a tunnel", "goes", "through", "The train"], "a": "The train goes through a tunnel."},
  ] },
  42: { core: "between = 둘 사이에 끼어 있다, among = 여럿 속에 섞여 있다.", qs: [
    {"t": "scene", "ctx": "EP.42, 빽빽한 부두에서", "q": "도윤: ______ all these boats? Impossible.\n하늘: The smallest boat is ______ those two big ones.", "hint": "배 오십 척 속에서 찾고, 작은 배는 큰 배 두 척 사이에 끼어 있다", "opts": ["Among / between", "Between / among", "Through / between", "Among / over"], "a": "Among / between", "why": "여럿 속은 among, 딱 둘 사이는 between."},
    {"t": "choice", "q": "`She is the tallest ______ her friends.` (친구들 중에서 그녀가 제일 크다)", "opts": ["among", "between", "by", "off"], "a": "among", "why": "친구 여럿 속에서 견준다."},
    {"t": "choice", "q": "`Sit ______ Mina and me.` (미나와 나 사이에 앉아)", "opts": ["between", "among", "through", "over"], "a": "between", "why": "양쪽에 하나씩, 딱 둘이다."},
    {"t": "order", "words": ["between", "cat", "is", "The", "the two boxes"], "q": "단어를 순서대로 놓으세요", "a": "The cat is between the two boxes."},
    {"t": "order", "words": ["a river", "between", "There", "is", "the two towns"], "q": "단어를 순서대로 놓으세요", "a": "There is a river between the two towns."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the two mountains", "between", "is", "The lake"], "a": "The lake is between the two mountains."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["my hat", "found", "among", "I", "the coats"], "a": "I found my hat among the coats."},
  ] },
  43: { core: "before = 줄의 앞, after = 줄의 뒤. 시간도 순서도 같은 줄이다.", qs: [
    {"t": "scene", "ctx": "EP.43, 관리실 모니터 앞에서", "q": "소이: ______ two, the gate is empty.\n하늘: ______ the truck, the video jumps.", "hint": "트럭이 오기 전에는 문이 비어 있고, 트럭이 온 뒤에 영상이 튄다", "opts": ["Before / After", "After / Before", "Before / Among", "Along / After"], "a": "Before / After", "why": "2시보다 앞은 before, 트럭보다 뒤는 after."},
    {"t": "choice", "q": "`Wash your hands ______ dinner.` (저녁 먹기 전에 손을 씻어)", "opts": ["before", "after", "between", "through"], "a": "before", "why": "저녁이라는 자리보다 줄 앞이다."},
    {"t": "choice", "q": "`Come ______ six.` (6시 정각은 안 되고, 6시가 되기 전에 와)", "opts": ["before", "by", "after", "at"], "a": "before", "why": "by six는 6시 정각도 통과하고, before six는 6시 정각이 못 들어온다."},
    {"t": "order", "words": ["before", "dinner", "Wash", "your hands"], "q": "단어를 순서대로 놓으세요", "a": "Wash your hands before dinner."},
    {"t": "order", "words": ["call", "I", "school", "after", "my mom"], "q": "단어를 순서대로 놓으세요", "a": "I call my mom after school."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the movie", "talked", "after", "We"], "a": "We talked after the movie."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["before", "two", "The gate", "empty", "is"], "a": "The gate is empty before two."},
  ] },
  44: { core: "above = 선보다 위, below = 선보다 아래. 거리는 상관없고 높이만 본다.", qs: [
    {"t": "scene", "ctx": "EP.44, 유리 바닥 보트 위에서", "q": "하늘: The sun is ______ us. The light goes all the way down.\n소이: Look. ______ that rock.", "hint": "해는 우리 위에 있고, 붉은 끈은 바위 아래에서 흔들린다", "opts": ["above / Below", "below / Above", "above / Among", "through / Below"], "a": "above / Below", "why": "해는 우리보다 높은 곳, 끈은 바위보다 낮은 곳이다."},
    {"t": "choice", "q": "`The temperature is ______ zero.` (기온이 영하야)", "opts": ["below", "above", "among", "through"], "a": "below", "why": "0이라는 눈금선보다 아래다."},
    {"t": "choice", "q": "above와 over의 차이로 맞는 것은?", "opts": ["above는 가만히 더 높은 곳이고, over는 위를 넘어 지나가는 그림이다", "above는 아래쪽이고, over는 위쪽이다", "둘은 서로 반대말이다", "above는 시간에만 쓴다"], "a": "above는 가만히 더 높은 곳이고, over는 위를 넘어 지나가는 그림이다"},
    {"t": "order", "words": ["above", "the sea", "is", "The sun"], "q": "단어를 순서대로 놓으세요", "a": "The sun is above the sea."},
    {"t": "order", "words": ["the boat", "swim", "below", "The fish"], "q": "단어를 순서대로 놓으세요", "a": "The fish swim below the boat."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["zero", "below", "The temperature", "is"], "a": "The temperature is below zero."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["mine", "Her name", "is", "above", "on the list"], "a": "Her name is above mine on the list."},
  ] },
  45: { core: "around = 가운데를 빙 둘러 있거나 한 바퀴 돌아서 간다.", qs: [
    {"t": "scene", "ctx": "EP.45, 밀물이 차오르는 방파제에서", "q": "하늘: Keep moving. We can rest ______ the corner.", "opts": ["around", "through", "among", "between"], "a": "around", "why": "모퉁이를 돌아서 그 뒤로 간다. 돌아서 = around."},
    {"t": "choice", "q": "`We sat ______ the fire.` (우리는 불 둘레에 둘러앉았다)", "opts": ["around", "through", "above", "between"], "a": "around", "why": "불이 가운데, 사람이 동그랗게."},
    {"t": "choice", "q": "`It's ______ three o'clock.` (3시쯤이야)에 함께 쓸 수 있는 두 단어는?", "opts": ["about, around", "through, into", "above, below", "between, among"], "a": "about, around", "why": "시각과 숫자에서는 about과 around를 바꿔 쓴다."},
    {"t": "order", "words": ["around", "sat", "We", "the fire"], "q": "단어를 순서대로 놓으세요", "a": "We sat around the fire."},
    {"t": "order", "words": ["around", "the lake", "walked", "I"], "q": "단어를 순서대로 놓으세요", "a": "I walked around the lake."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the corner", "around", "We", "rest", "can"], "a": "We can rest around the corner."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["around", "the lake", "The path", "goes"], "a": "The path goes around the lake."},
  ] },
  46: { core: "across = 이쪽에서 저쪽으로 가로질러, along = 길게 뻗은 것을 따라.", qs: [
    {"t": "scene", "ctx": "EP.46, 작은 배로 만을 건너 등대로", "q": "소이: It's a long way ______ the bay.\n소이: Run ______ the pier! It leads to the lighthouse.", "hint": "만은 이쪽에서 저쪽으로 건너고, 부두는 길을 따라 달린다", "opts": ["across / along", "along / across", "through / across", "across / above"], "a": "across / along", "why": "만의 한쪽 끝에서 반대쪽 끝으로 건너고, 길게 뻗은 부두를 따라 달린다."},
    {"t": "choice", "q": "`Walk ______ the street.` (길을 건너)", "opts": ["across", "along", "among", "off"], "a": "across", "why": "길 한쪽에서 반대쪽으로 간다."},
    {"t": "choice", "q": "`There are trees ______ the road.` (길을 따라 나무가 서 있다)", "opts": ["along", "across", "between", "above"], "a": "along", "why": "길이 뻗은 방향으로 늘어서 있다."},
    {"t": "order", "words": ["across", "rowed", "We", "the bay"], "q": "단어를 순서대로 놓으세요", "a": "We rowed across the bay."},
    {"t": "order", "words": ["along", "walked", "She", "the pier"], "q": "단어를 순서대로 놓으세요", "a": "She walked along the pier."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the street", "across", "Walk"], "a": "Walk across the street."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the road", "along", "There are", "trees"], "a": "There are trees along the road."},
  ] },
  47: { core: "behind = 뒤쪽(가려질 때가 많다), beside = 나란히 서는 옆.", qs: [
    {"t": "scene", "ctx": "EP.47, 등대 아래에서", "q": "하늘: Someone is ______ the lighthouse.\n강 할아버지: Stand ______ me, Soi.", "opts": ["behind / beside", "through / beside", "behind / among", "above / between"], "a": "behind / beside", "why": "등대 뒤쪽 그늘에 누가 있고, 소이는 곁에 나란히 서라고 한다."},
    {"t": "choice", "q": "`The cat is ______ the door.` (고양이는 문 뒤에 있다)", "opts": ["behind", "beside", "among", "through"], "a": "behind", "why": "문에 가려서 안 보인다."},
    {"t": "choice", "q": "`She stood ______ me.` (그녀는 내 바로 옆에 나란히 섰다)", "opts": ["beside", "behind", "through", "across"], "a": "beside", "why": "가려지는 게 아니라 나란히 선다."},
    {"t": "order", "words": ["behind", "cat", "is", "The", "the door"], "q": "단어를 순서대로 놓으세요", "a": "The cat is behind the door."},
    {"t": "order", "words": ["stood", "She", "beside", "me"], "q": "단어를 순서대로 놓으세요", "a": "She stood beside me."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["went", "The sun", "the clouds", "behind"], "a": "The sun went behind the clouds."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the tree", "behind", "is", "hiding", "Who"], "a": "Who is hiding behind the tree?"},
  ] },
  48: { core: "이번 달 그림은 길과 자리다. 열두 개를 지도처럼 겹쳐 본다.", qs: [
    {"t": "scene", "ctx": "EP.48, 등대 앞에서 강 할아버지가 시간을 말하며", "q": "강 할아버지: Come back when the tide is low. ______ six in the morning.\n하늘: Six o'clock. The bell is ______ the water.", "hint": "새벽 여섯 시가 되기 전에 오고, 종은 물 아래에 있다", "opts": ["Before / below", "After / above", "Before / above", "Behind / below"], "a": "Before / below", "why": "6시보다 앞은 before, 물 수면보다 아래는 below."},
    {"t": "choice", "q": "그림이 잘못 짝지어진 것은?", "opts": ["through = 들어가서 반대쪽으로 나옴", "between = 여럿 속에 섞임", "across = 이쪽에서 저쪽으로 건넘", "behind = 가려서 안 보이는 뒤"], "a": "between = 여럿 속에 섞임", "why": "여럿 속에 섞이는 건 among이다. between은 딱 둘 사이."},
    {"t": "choice", "q": "`Walk ______ the pier.` (부두를 따라 걸어)", "opts": ["along", "through", "among", "behind"], "a": "along", "why": "길게 뻗은 부두를 따라간다."},
    {"t": "order", "words": ["through", "went", "We", "the market"], "q": "단어를 순서대로 놓으세요", "a": "We went through the market."},
    {"t": "order", "words": ["below", "the water", "The bell", "is"], "q": "단어를 순서대로 놓으세요", "a": "The bell is below the water."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["along", "the pier", "ran", "We"], "a": "We ran along the pier."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["six", "before", "Come back"], "a": "Come back before six."},
  ] },
  49: { core: "during은 일이 벌어지는 시간의 띠 안이다. 길이(두 시간)는 for, 사건(영화·폭풍)은 during.", qs: [
    {"t": "scene", "ctx": "EP.49, 썰물의 새벽 갯바위에서", "q": "도윤: What did you do ______ the storm?", "hint": "폭풍이 부는 동안 뭘 했느냐고 묻는다", "opts": ["during", "with", "from", "against"], "a": "during", "why": "폭풍이라는 일이 벌어지는 시간의 띠 안이다. 사건 앞은 during."},
    {"t": "choice", "q": "`Don't talk ______ the movie.` (영화 하는 동안 떠들지 마)", "opts": ["during", "for", "toward", "beyond"], "a": "during", "why": "영화는 사건이다. 길이가 아니라 무슨 일이냐가 오면 during."},
    {"t": "choice", "q": "`I slept ______ two hours.` (두 시간 동안 잤어)", "opts": ["for", "during", "since", "against"], "a": "for", "why": "두 시간은 길이다. 길이는 for, 사건은 during."},
    {"t": "order", "words": ["the night", "during", "It", "rained"], "q": "단어를 순서대로 놓으세요", "a": "It rained during the night."},
    {"t": "order", "words": ["the movie", "during", "talk", "Don't"], "q": "단어를 순서대로 놓으세요", "a": "Don't talk during the movie."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the storm", "during", "rang", "bell", "The"], "a": "The bell rang during the storm."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["you", "did", "What", "the storm", "during", "do"], "a": "What did you do during the storm?"},
  ] },
  50: { core: "until은 끝 말뚝까지 쭉, since는 시작 말뚝에서 지금까지 쭉 이어진다.", qs: [
    {"t": "scene", "ctx": "EP.50, 관리실에서 이사회 소식을 듣고", "q": "강 할아버지: The board meets next Friday. The bell stays hidden ______ Friday.", "hint": "금요일까지 쭉 숨겨 둔다는 뜻", "opts": ["until", "since", "from", "against"], "a": "until", "why": "금요일이 끝 말뚝이다. 그때까지 쭉 이어지면 until."},
    {"t": "choice", "q": "`Wait here ______ six.` (6시까지 쭉 여기서 기다려)", "opts": ["until", "by", "since", "during"], "a": "until", "why": "기다림이 쭉 이어지다가 6시에 끝난다. 한 번 해내면 끝나는 by와 다르다."},
    {"t": "choice", "q": "`I have lived here ______ 2020.` (2020년부터 지금까지 여기 살았어)", "opts": ["since", "until", "during", "against"], "a": "since", "why": "2020이 시작 말뚝이고 줄이 지금까지 이어진다."},
    {"t": "order", "words": ["until", "here", "six", "Wait"], "q": "단어를 순서대로 놓으세요", "a": "Wait here until six."},
    {"t": "order", "words": ["since", "2020", "lived", "have", "here", "I"], "q": "단어를 순서대로 놓으세요", "a": "I have lived here since 2020."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["until", "We", "noon", "waited"], "a": "We waited until noon."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["since", "Monday", "has", "here", "She", "been"], "a": "She has been here since Monday."},
  ] },
  51: { core: "without은 with가 빠진 빈자리다. 있어야 할 것이 없다.", qs: [
    {"t": "scene", "ctx": "EP.51, 보건소 복도에서 여섯 시에", "q": "소이: Nothing comes. He can't sleep ______ that sound.", "hint": "그 소리가 없으면 잠을 못 잔다는 뜻", "opts": ["without", "with", "by", "from"], "a": "without", "why": "그 소리가 빠진 자리가 비었다. with(함께)가 빠지면 without."},
    {"t": "choice", "q": "`I can't live ______ music.` (음악 없이는 못 살아)", "opts": ["without", "with", "during", "toward"], "a": "without", "why": "음악이 있어야 할 자리가 비면 without."},
    {"t": "choice", "q": "`She left ______ saying goodbye.` (그녀는 작별 인사도 없이 떠났어)", "opts": ["without", "until", "during", "toward"], "a": "without", "why": "without 뒤의 동작은 saying처럼 -ing 꼴이다."},
    {"t": "order", "words": ["without", "an umbrella", "out", "go", "Don't"], "q": "단어를 순서대로 놓으세요", "a": "Don't go out without an umbrella."},
    {"t": "order", "words": ["without", "music", "sleep", "can't", "I"], "q": "단어를 순서대로 놓으세요", "a": "I can't sleep without music."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["without", "goodbye", "saying", "left", "She"], "a": "She left without saying goodbye."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["without", "sugar", "coffee", "drinks", "He"], "a": "He drinks coffee without sugar."},
  ] },
  52: { core: "against는 맞대고 미는 힘이다. 기댈 때도, 반대할 때도, 겨룰 때도 같은 그림.", qs: [
    {"t": "scene", "ctx": "EP.52, 정문 앞에서 Mr. Park와", "q": "Mr. Park: Gone? The board is ready. Seven for, one ______.", "hint": "일곱은 찬성, 하나는 반대라는 뜻", "opts": ["against", "above", "among", "along"], "a": "against", "why": "찬성 일곱, 반대 하나. 계획과 반대쪽에 선 표는 against."},
    {"t": "choice", "q": "`I voted ______ the plan.` (나는 그 계획에 반대표를 던졌어)", "opts": ["against", "for", "by", "from"], "a": "against", "why": "계획과 반대쪽에 서 있다."},
    {"t": "choice", "q": "on과 against의 차이는?", "opts": ["on은 그냥 닿아 있음, against는 힘을 싣고 맞대고 있음", "on은 힘을 싣고 맞댐, against는 그냥 닿아 있음", "둘은 똑같다", "on은 위, against는 아래"], "a": "on은 그냥 닿아 있음, against는 힘을 싣고 맞대고 있음"},
    {"t": "order", "words": ["against", "the wall", "leans", "He"], "q": "단어를 순서대로 놓으세요", "a": "He leans against the wall."},
    {"t": "order", "words": ["against", "Team B", "played", "We"], "q": "단어를 순서대로 놓으세요", "a": "We played against Team B."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["against", "the window", "blew", "wind", "The"], "a": "The wind blew against the window."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["against", "the plan", "voted", "Who"], "a": "Who voted against the plan?"},
  ] },
  53: { core: "like는 닮은 모습을 비추는 거울, as는 진짜 역할을 다는 명찰이다.", qs: [
    {"t": "scene", "ctx": "EP.53, 종탑 꼭대기에서 편지를 읽으며", "q": "소이: The bell is ______ a heart. When it stops, the village stops.", "hint": "종은 심장처럼 마을을 뛰게 한다. 진짜 심장은 아니다", "opts": ["like", "as", "from", "against"], "a": "like", "why": "진짜 심장이 아니라 닮았을 뿐이다. 거울에 비친 모습이니 like."},
    {"t": "choice", "q": "`He works ______ a teacher.` (그는 교사로 일해)", "opts": ["as", "like", "against", "toward"], "a": "as", "why": "진짜 교사라는 명찰을 달고 있다."},
    {"t": "choice", "q": "`He works like a boss.`의 뜻은?", "opts": ["그는 사장으로 일한다", "그는 사장처럼 일한다 (사장이 아닐 수 있다)", "그는 사장을 좋아한다", "그는 사장과 함께 일한다"], "a": "그는 사장처럼 일한다 (사장이 아닐 수 있다)"},
    {"t": "order", "words": ["like", "a bird", "sings", "She"], "q": "단어를 순서대로 놓으세요", "a": "She sings like a bird."},
    {"t": "order", "words": ["as", "a teacher", "works", "He"], "q": "단어를 순서대로 놓으세요", "a": "He works as a teacher."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["as", "a chair", "this box", "Use"], "a": "Use this box as a chair."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["like", "summer", "feels", "It"], "a": "It feels like summer."},
  ] },
  54: { core: "because of는 이유를 등에 업고, despite는 걸림돌을 지나쳐 간다.", qs: [
    {"t": "scene", "ctx": "EP.54, 저녁 갯바위에서 금을 보며", "q": "강 할아버지: It got bigger ______ the sea water.", "hint": "바닷물 때문에 금이 커졌다", "opts": ["because of", "despite", "until", "without"], "a": "because of", "why": "바닷물이 이유다. 이유를 등에 업으면 because of."},
    {"t": "choice", "q": "`We stayed home ______ the rain.` (비 때문에 집에 있었어)", "opts": ["because of", "despite", "because", "during"], "a": "because of", "why": "뒤가 명사(the rain)라서 because of. because 혼자는 뒤에 문장이 온다."},
    {"t": "choice", "q": "`She smiled ______ the pain.` (아팠는데도 웃었어)", "opts": ["despite", "because of", "because", "until"], "a": "despite", "why": "아픔이라는 걸림돌을 지나쳐서 웃었다."},
    {"t": "order", "words": ["because of", "the rain", "home", "stayed", "We"], "q": "단어를 순서대로 놓으세요", "a": "We stayed home because of the rain."},
    {"t": "order", "words": ["despite", "the pain", "smiled", "She"], "q": "단어를 순서대로 놓으세요", "a": "She smiled despite the pain."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["the rain", "we", "played", "outside", "Despite"], "a": "Despite the rain, we played outside."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["because of", "the storm", "cancelled", "was", "game", "The"], "a": "The game was cancelled because of the storm."},
  ] },
  55: { core: "toward는 쪽을 가리키며 가는 중, beyond는 선을 넘은 저 너머다.", qs: [
    {"t": "scene", "ctx": "EP.55, 새벽 부두에서 종을 끌어오며", "q": "도윤: It's coming ______ us!", "hint": "종이 우리 쪽으로 다가오는 중이다", "opts": ["toward", "beyond", "against", "without"], "a": "toward", "why": "우리 쪽을 가리키며 오는 중이다. 도착이 아니라 방향이라 toward."},
    {"t": "choice", "q": "`The school is ______ that hill.` (학교는 저 언덕 너머에 있어)", "opts": ["beyond", "toward", "because of", "despite"], "a": "beyond", "why": "언덕이라는 선을 넘은 저편이다."},
    {"t": "choice", "q": "`He is walking toward the sea.`의 뜻으로 맞는 것은?", "opts": ["바다 쪽으로 걸어가는 중이다", "바다에 도착했다", "바다 안에 있다", "바다 너머로 넘어갔다"], "a": "바다 쪽으로 걸어가는 중이다", "why": "toward는 쪽을 가리킨다. 도착은 to."},
    {"t": "order", "words": ["toward", "the pier", "turning", "is", "boat", "The"], "q": "단어를 순서대로 놓으세요", "a": "The boat is turning toward the pier."},
    {"t": "order", "words": ["beyond", "that hill", "is", "school", "The"], "q": "단어를 순서대로 놓으세요", "a": "The school is beyond that hill."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["toward", "the light", "Walk"], "a": "Walk toward the light."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["beyond", "the horizon", "sailed", "boat", "The"], "a": "The boat sailed beyond the horizon."},
  ] },
  56: { core: "전치사는 그림이 모인 지도다. 이번 달 그림이 그 지도에 더해졌다.", qs: [
    {"t": "scene", "ctx": "EP.56, 종소리가 처음 울린 아침", "q": "하늘: ______ the crack, it sounds ______ home.", "hint": "금이 갔는데도 집처럼 들린다", "opts": ["Despite / like", "Despite / as", "Because of / like", "Because of / as"], "a": "Despite / like", "why": "금이 갔는데도라서 despite, 집을 닮은 소리라서 like."},
    {"t": "choice", "q": "그림이 잘못 짝지어진 것은?", "opts": ["during = 일이 벌어지는 시간의 띠", "without = 빠져서 남은 빈자리", "against = 맞대고 미는 힘", "toward = 도착점에 닿음"], "a": "toward = 도착점에 닿음", "why": "toward는 그쪽을 가리키며 가는 중이다. 도착점에 닿는 건 to."},
    {"t": "choice", "q": "`I'll wait ______ six.` (6시까지 쭉 기다릴게)", "opts": ["until", "by", "since", "during"], "a": "until"},
    {"t": "order", "words": ["since", "Monday", "quiet", "been", "has", "It"], "q": "단어를 순서대로 놓으세요", "a": "It has been quiet since Monday."},
    {"t": "order", "words": ["the crack", "it", "sounds", "home", "like", "Despite"], "q": "단어를 순서대로 놓으세요", "a": "Despite the crack, it sounds like home."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["as", "a bell keeper", "works", "She"], "a": "She works as a bell keeper."},
    {"t": "order", "q": "단어를 순서대로 놓으세요", "words": ["without", "her", "ring", "can't", "it", "We"], "a": "We can't ring it without her."},
  ] },
};
